We'll use this script to compare lines from the two sites.

A reminder that for a double to be a greater value on PrizePicks than DraftKings, 
the two bets must multiply to a value lesser than three.

In [14]:
# from draft_kings import get_dk_data# this will run the script that scrapes the data into the json file we will use
import sys
sys.path.append('..')  # Add the parent directory to the sys.path
from constants import *
from pp_scrape import get_data

In [15]:
import json, csv, math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [16]:
COLLEGE_BASKETBALL = "20"
MLB = "2"
NBA = "7"

# get_dk_data("mlb") # this will run the script that scrapes the data into the json file we will use
get_data(MLB) # this will run the script that scrapes the data into the json file we will use

191 0
xx

[{'name': 'Daniel Schneemann', 'opponent': 'SD', 'Hits+Runs+RBIs': 0.5},
 {'name': 'Shane Baz',
  'opponent': 'PIT',
  'Walks Allowed': 1.5,
  'Pitcher Fantasy Score': 26.5,
  'Pitcher Strikeouts': 5},
 {'name': 'Michael Lorenzen',
  'opponent': 'MIL',
  'Hits Allowed': 4.5,
  'Pitcher Fantasy Score': 22.5,
  'Pitcher Strikeouts': 4},
 {'name': 'Corbin Burnes',
  'opponent': 'NYY',
  'Pitcher Fantasy Score': 28.5,
  'Pitcher Strikeouts': 5},
 {'name': 'Jose Berrios',
  'opponent': 'WSH',
  'Walks Allowed': 1.5,
  'Pitcher Fantasy Score': 33.5,
  'Pitcher Strikeouts': 5},
 {'name': 'Chad Patrick',
  'opponent': 'KC',
  'Earned Runs Allowed': 1.5,
  'Pitching Outs': 11.5,
  'Pitcher Strikeouts': 3},
 {'name': 'Shane Smith',
  'opponent': 'MIN',
  'Hits Allowed': 3.5,
  'Walks Allowed': 1.5,
  'Pitcher Strikeouts': 4},
 {'name': 'Matthew Liberatore',
  'opponent': 'LAA',
  'Pitching Outs': 13.5,
  'Pitcher Fantasy Score': 21.5,
  'Pitcher Strikeouts': 4},
 {'name': 'Will Warren',
  'opponent': 'AZ',
  'Pitcher Fantasy Score': 22.5,
  'Pitcher Strikeouts': 4},
 {'name': 'Michael King',
  'opponent': 'CLE',
  'Earned Runs Allowed': 1.5,
  'Pitching Outs': 16.5,
  'Pitcher Fantasy Score': 31.5,
  'Pitcher Strikeouts': 5.5},
 {'name': 'Luis Severino',
  'opponent': 'CHC',
  'Earned Runs Allowed': 2.5,
  'Pitcher Strikeouts': 5},
 {'name': 'Kyle Hendricks', 'opponent': 'STL', 'Pitcher Fantasy Score': 16.5},
 {'name': 'Cody Bellinger', 'opponent': 'AZ', 'Hitter Fantasy Score': 6.5},
 {'name': 'Logan Webb',
  'opponent': 'HOU',
  'Pitcher Fantasy Score': 28.5,
  'Pitcher Strikeouts': 4.5},
 {'name': 'Ketel Marte',
  'opponent': 'NYY',
  'Hitter Fantasy Score': 6.5,
  'Hits+Runs+RBIs': 1.5},
 {'name': 'Paul Goldschmidt', 'opponent': 'AZ', 'Hitter Fantasy Score': 5.5},
 {'name': 'Corbin Carroll',
  'opponent': 'NYY',
  'Hitter Fantasy Score': 6.5,
  'Hits+Runs+RBIs': 1.5},
 {'name': 'Logan Gilbert',
  'opponent': 'DET',
  'Pitcher Fantasy Score': 41.5,
  'Pitcher Strikeouts': 8},
 {'name': 'Yandy Diaz', 'opponent': 'PIT', 'Hitter Fantasy Score': 6.5},
 {'name': 'Casey Mize',
  'opponent': 'SEA',
  'Pitcher Fantasy Score': 25.5,
  'Pitcher Strikeouts': 4.5},
 {'name': 'Oneil Cruz',
  'opponent': 'TB',
  'Hitter Fantasy Score': 7,
  'Hits+Runs+RBIs': 1.5},
 {'name': 'Chris Sale',
  'opponent': 'LAD',
  'Pitcher Fantasy Score': 32.5,
  'Pitcher Strikeouts': 6},
 {'name': 'Bryan Reynolds',
  'opponent': 'TB',
  'Hitter Fantasy Score': 7,
  'Hits+Runs+RBIs': 1.5},
 {'name': 'Jackson Chourio',
  'opponent': 'KC',
  'Hitter Fantasy Score': 6.5,
  'Runs': 0.5},
 {'name': 'Bobby Witt Jr.',
  'opponent': 'MIL',
  'Hitter Fantasy Score': 7.5,
  'Total Bases': 1.5,
  'Runs': 0.5},
 {'name': 'Jonathan India',
  'opponent': 'MIL',
  'Hitter Fantasy Score': 6.5,
  'Hits+Runs+RBIs': 1.5},
 {'name': 'Luis Robert', 'opponent': 'MIN', 'Hitter Fantasy Score': 6.5},
 {'name': 'Lars Nootbaar', 'opponent': 'LAA', 'Hitter Fantasy Score': 6.5},
 {'name': 'Dustin May',
  'opponent': 'ATL',
  'Earned Runs Allowed': 1.5,
  'Pitcher Strikeouts': 4},
 {'name': 'Mike Trout', 'opponent': 'STL', 'Hitter Fantasy Score': 7},
 {'name': 'Yordan Alvarez', 'opponent': 'SF', 'Hitter Fantasy Score': 7},
 {'name': 'Jose Altuve',
  'opponent': 'SF',
  'Hitter Fantasy Score': 6.5,
  'Hits+Runs+RBIs': 1.5},
 {'name': 'Matt Chapman',
  'opponent': 'HOU',
  'Hitter Fantasy Score': 6.5,
  'Runs': 0.5},
 {'name': 'Fernando Tatis Jr.',
  'opponent': 'CLE',
  'Hitter Fantasy Score': 8.5,
  'Runs': 0.5},
 {'name': 'Jose Ramirez',
  'opponent': 'SD',
  'Hitter Fantasy Score': 7,
  'Hits+Runs+RBIs': 1.5},
 {'name': 'Steven Kwan', 'opponent': 'SD', 'Hitter Fantasy Score': 6.5},
 {'name': 'Manny Machado',
  'opponent': 'CLE',
  'Hitter Fantasy Score': 6.5,
  'Hits+Runs+RBIs': 1.5},
 {'name': 'Jackson Merrill',
  'opponent': 'CLE',
  'Hitter Fantasy Score': 6,
  'Hits+Runs+RBIs': 1.5},
 {'name': 'Julio Rodriguez', 'opponent': 'DET', 'Hitter Fantasy Score': 6.5},
 {'name': 'Randy Arozarena',
  'opponent': 'DET',
  'Hitter Fantasy Score': 6.5,
  'Hits+Runs+RBIs': 1.5},
 {'name': 'Riley Greene', 'opponent': 'SEA', 'Hitter Fantasy Score': 5},
 {'name': 'Cal Raleigh', 'opponent': 'DET', 'Hitter Fantasy Score': 6.5},
 {'name': 'Kyle Tucker',
  'opponent': 'ATH',
  'Hitter Fantasy Score': 7.5,
  'Runs': 0.5,
  'Walks': 0.5},
 {'name': 'Brent Rooker',
  'opponent': 'CHC',
  'Hitter Fantasy Score': 6.5,
  'Hits+Runs+RBIs': 1.5},
 {'name': 'Seiya Suzuki',
  'opponent': 'ATH',
  'Hitter Fantasy Score': 5.5,
  'Hits+Runs+RBIs': 1.5},
 {'name': 'Lawrence Butler', 'opponent': 'CHC', 'Hitter Fantasy Score': 6.5},
 {'name': 'Ian Happ',
  'opponent': 'ATH',
  'Hitter Fantasy Score': 5.5,
  'Runs': 0.5,
  'Hits+Runs+RBIs': 1.5},
 {'name': 'Shohei Ohtani',
  'opponent': 'ATL',
  'Hitter Fantasy Score': 8.5,
  'Runs': 0.5,
  'Hits+Runs+RBIs': 1.5},
 {'name': 'Oswaldo Cabrera', 'opponent': 'AZ', 'Total Bases': 0.5},
 {'name': 'Austin Wells', 'opponent': 'AZ', 'Total Bases': 0.5},
 {'name': 'Mookie Betts',
  'opponent': 'ATL',
  'Hitter Fantasy Score': 6.5,
  'Hits+Runs+RBIs': 1.5},
 {'name': 'Matt Olson',
  'opponent': 'LAD',
  'Hitter Fantasy Score': 6,
  'Walks': 0.5},
 {'name': 'Geraldo Perdomo', 'opponent': 'NYY', 'Total Bases': 0.5},
 {'name': 'Marcell Ozuna',
  'opponent': 'LAD',
  'Hitter Fantasy Score': 6,
  'Hits+Runs+RBIs': 1.5},
 {'name': 'Ben Rice', 'opponent': 'AZ', 'Total Bases': 0.5},
 {'name': 'Austin Riley',
  'opponent': 'LAD',
  'Hitter Fantasy Score': 6,
  'Hits+Runs+RBIs': 1.5},
 {'name': 'Thomas Harrington',
  'opponent': 'TB',
  'Pitcher Strikeouts': 3.5,
  'Pitching Outs': 12.5},
 {'name': 'Enmanuel Valdez', 'opponent': 'TB', 'Total Bases': 0.5},
 {'name': 'Bo Bichette', 'opponent': 'WSH', 'Total Bases': 1.5, 'Runs': 0.5},
 {'name': 'Anthony Santander', 'opponent': 'WSH', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Vladimir Guerrero Jr.',
  'opponent': 'WSH',
  'Runs': 0.5,
  'Total Bases': 1.5},
 {'name': 'Trevor Williams', 'opponent': 'TOR', 'Pitcher Strikeouts': 3},
 {'name': 'CJ Abrams', 'opponent': 'TOR', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Ernie Clement', 'opponent': 'WSH', 'Hits+Runs+RBIs': 1.5},
 {'name': 'George Springer', 'opponent': 'WSH', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Brandon Lowe', 'opponent': 'PIT', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Curtis Mead', 'opponent': 'PIT', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Jake Mangum', 'opponent': 'PIT', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Junior Caminero', 'opponent': 'PIT', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Keibert Ruiz', 'opponent': 'TOR', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Luis Garcia', 'opponent': 'TOR', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Byron Buxton', 'opponent': 'CWS', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Jo Adell', 'opponent': 'STL', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Salvador Perez', 'opponent': 'MIL', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Jose Iglesias', 'opponent': 'CLE', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Dansby Swanson', 'opponent': 'ATH', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Kyle Isbel', 'opponent': 'MIL', 'Total Bases': 0.5},
 {'name': 'MJ Melendez', 'opponent': 'MIL', 'Total Bases': 0.5},
 {'name': 'Simeon Woods Richardson',
  'opponent': 'CWS',
  'Pitcher Strikeouts': 4.5},
 {'name': 'Carlos Correa', 'opponent': 'CWS', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Matt Wallner', 'opponent': 'CWS', 'Runs': 0.5},
 {'name': 'Ryan Jeffers', 'opponent': 'CWS', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Victor Scott II', 'opponent': 'LAA', 'Hits+Runs+RBIs': 1.5},
 {'name': 'LaMonte Wade Jr.',
  'opponent': 'HOU',
  'Walks': 0.5,
  'Hits+Runs+RBIs': 1.5},
 {'name': 'Jung Hoo Lee', 'opponent': 'HOU', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Willy Adames',
  'opponent': 'HOU',
  'Runs': 0.5,
  'Hits+Runs+RBIs': 1.5},
 {'name': 'Hayden Wesneski', 'opponent': 'SF', 'Pitcher Strikeouts': 4},
 {'name': 'Yainer Diaz', 'opponent': 'SF', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Christian Walker', 'opponent': 'SF', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Heliot Ramos', 'opponent': 'HOU', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Jeremy Pena', 'opponent': 'SF', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Isaac Paredes', 'opponent': 'SF', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Kyle Manzardo', 'opponent': 'SD', 'Total Bases': 0.5},
 {'name': 'Logan Allen', 'opponent': 'SD', 'Pitcher Strikeouts': 3},
 {'name': 'Brayan Rocchio', 'opponent': 'SD', 'Total Bases': 0.5},
 {'name': 'Bo Naylor', 'opponent': 'SD', 'Total Bases': 0.5},
 {'name': 'Luis Arraez', 'opponent': 'CLE', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Xander Bogaerts', 'opponent': 'CLE', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Trey Sweeney', 'opponent': 'SEA', 'Total Bases': 0.5},
 {'name': 'Rowdy Tellez', 'opponent': 'DET', 'Total Bases': 0.5},
 {'name': 'Jake Rogers',
  'opponent': 'SEA',
  'Total Bases': 0.5,
  'Hits+Runs+RBIs': 0.5},
 {'name': 'J.P. Crawford', 'opponent': 'DET', 'Total Bases': 0.5},
 {'name': 'Justin Steele', 'opponent': 'ATH', 'Pitcher Strikeouts': 5},
 {'name': 'Tyler Soderstrom', 'opponent': 'CHC', 'Total Bases': 0.5},
 {'name': 'Nico Hoerner', 'opponent': 'ATH', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Michael Busch', 'opponent': 'ATH', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Miguel Andujar', 'opponent': 'CHC', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Drake Baldwin', 'opponent': 'LAD', 'Total Bases': 0.5},
 {'name': 'Andy Pages', 'opponent': 'ATL', 'Total Bases': 0.5},
 {'name': 'Jarred Kelenic', 'opponent': 'LAD', 'Total Bases': 0.5},
 {'name': 'Tommy Edman', 'opponent': 'ATL', 'Hits+Runs+RBIs': 1.5},
 {'name': 'Michael Harris II', 'opponent': 'LAD', 'Hits+Runs+RBIs': 1.5}]

In [17]:
more_mlb_props = ['Correct Score', 'Most Regular Season Strikeouts',
       'Most Regular Season Hits', 'Most Regular Season Runs', 'Award Winner',
       'Most Regular Season Saves', 'Most Regular Season Home Runs',
       'Pitcher Most Regular Season Wins', 'Most Regular Season Stolen Bases',
       'To Make the Playoffs', 'Division Winner', 'League Winner', 'Winner',
       'Race To 10 Regular Season Wins',
       'Freddie Freeman - 1st Plate Appearance - Exact Result',
       'Shohei Ohtani - 1st Plate Appearance - Exact Result',
       'Seiya Suzuki - 1st Plate Appearance - Exact Result',
       'Kyle Tucker - 1st Plate Appearance - Exact Result',
       'Ian Happ - 1st Plate Appearance - Exact Result',
       'Tommy Edman - 1st Plate Appearance - Exact Result',
       'Run Line - 1st 5 Innings',
       'Both Teams to Score X+ Runs - 1st 5 Innings',
       'Total Runs - 1st 5 Innings', 'Runs - 6th Inning',
       'Runs - 5th Inning', 'Runs - 1st Inning', 'Runs - 4th Inning',
       'Runs - 9th Inning', 'Runs - 7th Inning', 'Runs - 8th Inning',
       'Runs - 3rd Inning', 'Runs - 2nd Inning', 'Race to 3 Runs',
       'Race to 5 Runs', 'Race to 6 Runs', 'Race to 7 Runs', 'Race to 4 Runs']

In [18]:
PROP_LABEL_STRING = "prop_label"
PARTICIPANT_LABEL_STRING = "participant"
CBB_DK_CSV = "draftkings_cbb.csv"
MLB_DK_CSV = "draftkings_mlb.csv"
NBA_DK_CSV = "draftkings_nba.csv"   


dk_lines = pd.read_csv(MLB_DK_CSV, encoding='latin-1')
# print(dk_lines['category'].value_counts())
# # list the items that appear multiple times
# print(dk_lines[PROP_LABEL_STRING].value_counts()[dk_lines[PROP_LABEL_STRING].value_counts() > 2].keys())
game_props = ["Game Lines", "Team Props", "Halves", "Game Props", "Total", "Innings", "Total Runs - 1st 5 Innings", "Quick Hits", "Game Leaders", "Game Lines", "Total", "Most Points", "Moneyline", "Halves", "Total 1st Half", "Moneyline 1st Half", "Quarters", "Total 1st Quarter", "Moneyline 1st Quarter", "Q1 Player Props"]
# game_props = game_props + more_mlb_props



player_lines = dk_lines[~dk_lines[PROP_LABEL_STRING].isin(game_props)]
player_lines = player_lines[~player_lines[PARTICIPANT_LABEL_STRING].isin(game_props)]
print(player_lines["category"].value_counts())


player_lines

category
Correct Score             5698
Batter Props              5362
Innings                   1452
1st X Innings             1122
1st of Game               1005
Game Lines                 991
1st Inning                 950
Combined Player Props      941
Live Batter Props          892
Team Totals                830
Plate Appearance           787
Game Props                 706
Pitcher Props              657
Live Inning Props          585
Either Player Props        564
Live Game Props            328
Awards                     225
Game Totals                198
Half Inning Props          142
Leagues                     96
Playoffs/Seeds              90
Champion                    79
Live Pitcher Props          64
Team Wins                   63
Divisions                   30
Start of Season             14
Player Season Specials       4
Series Props                 2
Name: count, dtype: int64

,providerOutcomeId,providerId,providerOfferId,label,oddsAmerican,oddsDecimal,oddsDecimalDisplay,oddsFractional,line,participant,participantType,main,sortOrder,tags,participants,category,subcategory,prop_label
0,0HC79312092N150_3,2,2_79312092,NY Mets,+120,2.200000,2.20,6/5,-1.5,NY Mets,Team,True,-1501,"['MainPointLine', 'SGP']","[{'id': '29840', 'name': 'NY Mets', 'type': 'T...",Game Lines,Game,Run Line
1,0HC79312092P150_1,2,2_79312092,MIA Marlins,-154,1.649351,1.64,50/77,1.5,MIA Marlins,Team,True,-1499,"['MainPointLine', 'SGP']","[{'id': '29953', 'name': 'MIA Marlins', 'type'...",Game Lines,Game,Run Line
6,0HC79312045N150_3,2,2_79312045,TEX Rangers,+124,2.240000,2.24,31/25,-1.5,TEX Rangers,Team,True,-1501,"['MainPointLine', 'SGP']","[{'id': '29891', 'name': 'TEX Rangers', 'type'...",Game Lines,Game,Run Line
7,0HC79312045P150_1,2,2_79312045,CIN Reds,-160,1.625000,1.62,5/8,1.5,CIN Reds,Team,True,-1499,"['MainPointLine', 'SGP']","[{'id': '29919', 'name': 'CIN Reds', 'type': '...",Game Lines,Game,Run Line
12,0HC79302366N150_3,2,2_79302366,ARI Diamondbacks,+136,2.360000,2.36,34/25,-1.5,ARI Diamondbacks,Team,True,-1501,"['MainPointLine', 'SGP']","[{'id': '29934', 'name': 'ARI Diamondbacks', '...",Game Lines,Game,Run Line
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24046,0QA241695623#200317919_13L84240Q13Q22,2,241695623,3-2,+12000,121.000000,121.00,120/1,None Specified,CIN Reds,Team,None Specified,200320919,None Specified,"[{'id': '29919', 'name': 'CIN Reds', 'type': '...",Live Inning Props,Correct Score Xth Inning,Correct Score - 8th Inning
24047,0QA241695623#200317939_13L84240Q14Q20,2,241695623,4-0,+4500,46.000000,46.00,45/1,None Specified,CIN Reds,Team,None Specified,200320939,None Specified,"[{'id': '29919', 'name': 'CIN Reds', 'type': '...",Live Inning Props,Correct Score Xth Inning,Correct Score - 8th Inning
24048,0QA241695623#200317959_13L84240Q14Q21,2,241695623,4-1,+11000,111.000000,111.00,110/1,None Specified,CIN Reds,Team,None Specified,200320959,None Specified,"[{'id': '29919', 'name': 'CIN Reds', 'type': '...",Live Inning Props,Correct Score Xth Inning,Correct Score - 8th Inning
24049,0QA241695623#200317979_13L84240Q14Q22,2,241695623,4-2,+15000,151.000000,151.00,150/1,None Specified,CIN Reds,Team,None Specified,200320979,None Specified,"[{'id': '29919', 'name': 'CIN Reds', 'type': '...",Live Inning Props,Correct Score Xth Inning,Correct Score - 8th Inning
24050,0QA241695623#200317999_13L84240Q14Q23,2,241695623,4-3,+20000,201.000000,201.00,200/1,None Specified,CIN Reds,Team,None Specified,200320999,None Specified,"[{'id': '29919', 'name': 'CIN Reds', 'type': '...",Live Inning Props,Correct Score Xth Inning,Correct Score - 8th Inning

In [19]:
print(player_lines['category'].value_counts())

player_lines = player_lines[player_lines['category'].isin(['Batter Props', 'Pitcher Props', 'Player Props', "Player Points", "Player Rebounds", "Player Assists", "Player Threes", "Player Combos", ])]
player_lines = player_lines[player_lines['participantType'] != 'Team']

print(player_lines['subcategory'].value_counts())
player_lines

category
Correct Score             5698
Batter Props              5362
Innings                   1452
1st X Innings             1122
1st of Game               1005
Game Lines                 991
1st Inning                 950
Combined Player Props      941
Live Batter Props          892
Team Totals                830
Plate Appearance           787
Game Props                 706
Pitcher Props              657
Live Inning Props          585
Either Player Props        564
Live Game Props            328
Awards                     225
Game Totals                198
Half Inning Props          142
Leagues                     96
Playoffs/Seeds              90
Champion                    79
Live Pitcher Props          64
Team Wins                   63
Divisions                   30
Start of Season             14
Player Season Specials       4
Series Props                 2
Name: count, dtype: int64
subcategory
Hits                       540
RBIs                       540
Total Bases                539
RBIs O/U                   396
Singles O/U                395
Hits O/U                   395
Total Bases O/U            395
Hits + Runs + RBIs O/U     395
Doubles O/U                394
Runs O/U                   394
Walks (Batter) O/U         368
Home Runs                  360
Stolen Bases O/U           251
Walks Allowed              188
Hits Allowed               110
Strikeouts Thrown           99
Strikeouts Thrown O/U       44
Hits Allowed O/U            44
Walks Allowed O/U           44
Earned Runs Allowed O/U     44
Outs Recorded O/U           34
To Record a Win             30
Race to Strikeouts          20
Name: count, dtype: int64

,providerOutcomeId,providerId,providerOfferId,label,oddsAmerican,oddsDecimal,oddsDecimalDisplay,oddsFractional,line,participant,participantType,main,sortOrder,tags,participants,category,subcategory,prop_label
156,0QA241678966#200235888_13L84240Q1-446308922Q20,2,241678966,1+,+225,3.250000,3.25,9/4,None Specified,Aaron Judge,Unknown,True,32588,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '32504', 'name': 'Aaron Judge', 'type'...",Batter Props,Home Runs,Aaron Judge Home Runs
157,0QA241678966#200235889_13L84240Q1475630076Q20,2,241678966,2+,+1500,16.000000,16.00,15/1,None Specified,Aaron Judge,Unknown,None Specified,160089,['SGP'],"[{'id': '32504', 'name': 'Aaron Judge', 'type'...",Batter Props,Home Runs,Aaron Judge Home Runs
158,0QA241783818#200810442_13L84240Q1-446308922Q20,2,241783818,1+,+1100,12.000000,12.00,11/1,None Specified,Alek Thomas,Unknown,True,120042,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '112685', 'name': 'Alek Thomas', 'type...",Batter Props,Home Runs,Alek Thomas Home Runs
159,0QA241783818#200810443_13L84240Q1475630076Q20,2,241783818,2+,+13000,131.000000,131.00,130/1,None Specified,Alek Thomas,Unknown,None Specified,1310043,['SGP'],"[{'id': '112685', 'name': 'Alek Thomas', 'type...",Batter Props,Home Runs,Alek Thomas Home Runs
160,0QA241678964#200235932_13L84240Q1-446308922Q20,2,241678964,1+,+900,10.000000,10.00,9/1,None Specified,Anthony Volpe,Unknown,True,100032,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '459842', 'name': 'Anthony Volpe', 'ty...",Batter Props,Home Runs,Anthony Volpe Home Runs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9576,0QA241676977#200229825_13L84240Q11925978808Q20,2,241676977,Under,-190,1.526316,1.52,10/19,18.5,Logan Gilbert,Unknown,True,18502,"['MainPointLine', '1stFavorite']","[{'id': '111248', 'name': 'Logan Gilbert', 'ty...",Pitcher Props,Outs Recorded O/U,Logan Gilbert Outs O/U
9577,0QA241687928#200275653_13L84240Q1-1655749891Q20,2,241687928,Over,-160,1.625000,1.62,5/8,17.5,Chris Sale,Unknown,True,17500,"['MainPointLine', '1stFavorite']","[{'id': '31461', 'name': 'Chris Sale', 'type':...",Pitcher Props,Outs Recorded O/U,Chris Sale Outs O/U
9578,0QA241687928#200275654_13L84240Q11295454286Q20,2,241687928,Under,+120,2.200000,2.20,6/5,17.5,Chris Sale,Unknown,True,17502,"['MainPointLine', '1stFavorite']","[{'id': '31461', 'name': 'Chris Sale', 'type':...",Pitcher Props,Outs Recorded O/U,Chris Sale Outs O/U
9579,0QA241804172#200900021_13L84240Q11993907140Q20,2,241804172,Over,+105,2.050000,2.05,21/20,14.5,Dustin May,Unknown,True,14500,"['MainPointLine', '1stFavorite']","[{'id': '32727', 'name': 'Dustin May', 'type':...",Pitcher Props,Outs Recorded O/U,Dustin May Outs O/U
9580,0QA241804172#200900022_13L84240Q1-1768265801Q20,2,241804172,Under,-145,1.689655,1.68,20/29,14.5,Dustin May,Unknown,True,14502,"['MainPointLine', '1stFavorite']","[{'id': '32727', 'name': 'Dustin May', 'type':...",Pitcher Props,Outs Recorded O/U,Dustin May Outs O/U

In [20]:
def get_stat_tracked(player_line):
    return player_line[PROP_LABEL_STRING].replace(player_line[PARTICIPANT_LABEL_STRING], '').replace("O/U", '').strip().lower()

# choose the value closest to a 50/50 split
# TODO: unders
def decide_to_skip(new_val, old_val):
    new_val_odds = 1 / float(new_val["oddsDecimal"])
    old_val_odds = 1 / float(old_val[new_val['stat_tracked'] + '_' + "Over"])

    new_val_diff = abs(new_val_odds - 0.5)
    old_val_diff = abs(old_val_odds - 0.5)

    return new_val_diff > old_val_diff

In [21]:
final_dk_db = {} #dic so we can combine lines for each player

for index, row in player_lines.iterrows():
    row['stat_tracked'] = get_stat_tracked(row)
    if row[PARTICIPANT_LABEL_STRING] not in final_dk_db:
        final_dk_db[row[PARTICIPANT_LABEL_STRING]] = {
            'name': row[PARTICIPANT_LABEL_STRING]
        }
    

    #TODO: integrate
    value = row['label'].replace("+", '').replace("-", '')
    if not value.isdigit():
        if not row['line'] or not row['line'].replace('.', '', 1).isdigit():
            continue
        over_or_under = "Over" if "Over" in row['label'] else "Under"
        final_dk_db[row[PARTICIPANT_LABEL_STRING]][row['stat_tracked']] = float(row['line'])
        final_dk_db[row[PARTICIPANT_LABEL_STRING]][row['stat_tracked'] + '_' + over_or_under] = row['oddsDecimal']
    else:
        if row['stat_tracked'] in final_dk_db[row[PARTICIPANT_LABEL_STRING]]:
            if (decide_to_skip(row, final_dk_db[row[PARTICIPANT_LABEL_STRING]])):
                continue
        value = float(value)
        over_or_under = "Over" if "+" in row['label'] else "Under"
        value = float(row['label'].replace("+", '').replace("-", ''))
        final_dk_db[row[PARTICIPANT_LABEL_STRING]][row['stat_tracked']] = value - 0.5 if over_or_under == "Over" else value + 0.5
        final_dk_db[row[PARTICIPANT_LABEL_STRING]][row['stat_tracked'] + '_' + over_or_under] = row['oddsDecimal']


final_dk_db = pd.DataFrame(final_dk_db).T
final_dk_db

,name,home runs,home runs_Over,hits,hits_Over,total bases,total bases_Over,rbis,rbis_Over,hits_Under,...,hits allowed_Under,walks allowed,walks allowed_Over,walks allowed_Under,earned runs allowed,earned runs allowed_Over,earned runs allowed_Under,outs,outs_Over,outs_Under
Aaron Judge,Aaron Judge,0.5,3.25,0.5,1.512821,1.5,2.0,0.5,2.25,2.45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Alek Thomas,Alek Thomas,0.5,12.0,0.5,1.689655,0.5,1.666667,0.5,3.15,2.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Anthony Volpe,Anthony Volpe,0.5,10.0,0.5,1.606061,0.5,1.588235,0.5,2.95,2.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Austin Wells,Austin Wells,0.5,8.0,0.5,1.833333,0.5,1.8,0.5,3.05,1.909091,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ben Rice,Ben Rice,0.5,8.5,0.5,1.909091,0.5,1.909091,0.5,3.6,1.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Luis Garcia (WAS),Luis Garcia (WAS),NaN,NaN,0.5,1.434783,1.5,2.45,0.5,3.2,2.65,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Nathaniel Lowe,Nathaniel Lowe,NaN,NaN,0.5,1.540541,0.5,1.526316,0.5,3.05,2.35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Paul DeJong,Paul DeJong,NaN,NaN,0.5,1.689655,0.5,1.689655,0.5,3.0,2.05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vladimir Guerrero Jr.,Vladimir Guerrero Jr.,NaN,NaN,1.5,2.55,1.5,1.909091,0.5,2.5,1.465116,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Will Wagner,Will Wagner,NaN,NaN,0.5,1.540541,0.5,1.526316,0.5,2.95,2.35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
final_dk_db.keys()

Index(['name', 'home runs', 'home runs_Over', 'hits', 'hits_Over',
       'total bases', 'total bases_Over', 'rbis', 'rbis_Over', 'hits_Under',
       'total bases_Under', 'rbis_Under', 'hits + runs + rbis',
       'hits + runs + rbis_Over', 'hits + runs + rbis_Under', 'runs',
       'runs_Over', 'runs_Under', 'stolen bases', 'stolen bases_Over',
       'stolen bases_Under', 'singles', 'singles_Over', 'singles_Under',
       'doubles', 'doubles_Over', 'doubles_Under', 'walks', 'walks_Over',
       'walks_Under', 'strikeouts thrown', 'strikeouts thrown_Over',
       'strikeouts thrown_Under', 'hits allowed', 'hits allowed_Over',
       'hits allowed_Under', 'walks allowed', 'walks allowed_Over',
       'walks allowed_Under', 'earned runs allowed',
       'earned runs allowed_Over', 'earned runs allowed_Under', 'outs',
       'outs_Over', 'outs_Under'],
      dtype='object')

In [23]:
prizepicks = pd.read_csv("pp_lines.csv")

merged = pd.merge(prizepicks, final_dk_db, on='name')
#get a list of all the column names
cols = merged.columns.tolist()
merged.keys()

Index(['name', 'opponent', 'Hits+Runs+RBIs', 'Walks Allowed',
       'Pitcher Fantasy Score', 'Pitcher Strikeouts', 'Hits Allowed',
       'Earned Runs Allowed', 'Pitching Outs', 'Hitter Fantasy Score', 'Runs',
       'Total Bases', 'Walks', 'home runs', 'home runs_Over', 'hits',
       'hits_Over', 'total bases', 'total bases_Over', 'rbis', 'rbis_Over',
       'hits_Under', 'total bases_Under', 'rbis_Under', 'hits + runs + rbis',
       'hits + runs + rbis_Over', 'hits + runs + rbis_Under', 'runs',
       'runs_Over', 'runs_Under', 'stolen bases', 'stolen bases_Over',
       'stolen bases_Under', 'singles', 'singles_Over', 'singles_Under',
       'doubles', 'doubles_Over', 'doubles_Under', 'walks', 'walks_Over',
       'walks_Under', 'strikeouts thrown', 'strikeouts thrown_Over',
       'strikeouts thrown_Under', 'hits allowed', 'hits allowed_Over',
       'hits allowed_Under', 'walks allowed', 'walks allowed_Over',
       'walks allowed_Under', 'earned runs allowed',
       'earned runs allowed_Over', 'earned runs allowed_Under', 'outs',
       'outs_Over', 'outs_Under'],
      dtype='object')

In [24]:
results = []

for index, row in merged.iterrows():
    # Access the values of each column in the current row
    name = row['name']

    for pp_stat_type in PP_TO_DK_STATS.keys():
        # failsafe 
        if pp_stat_type not in row:
            continue

        if float(row[pp_stat_type]) <= 0:
            continue

        if PP_TO_DK_STATS[pp_stat_type] not in row:
            continue
    
        if float(row[PP_TO_DK_STATS[pp_stat_type]]) <= 0:
            continue

        print("Passed all tests", pp_stat_type, name)

        # Create a dictionary to store the result
        result_dict = {
            'name': name,
            'stat': pp_stat_type,
            'line': row[pp_stat_type],
            'dk_line': float(row[PP_TO_DK_STATS[pp_stat_type]]),
            'dk_over_line': row[PP_TO_DK_STATS[pp_stat_type] + '_Over'],
            'dk_under_line': row[PP_TO_DK_STATS[pp_stat_type] + '_Under'] if PP_TO_DK_STATS[pp_stat_type] + '_Under' in row else 100,
        }

        # Get the dk stat type that corresponds to the current PP stat type
        dk_stat_type = PP_TO_DK_STATS[pp_stat_type]

        # Get the value of the FBref stat type for the current player
        dk_stat_value = row[dk_stat_type]



        # Append the dictionary to the results list
        results.append(result_dict)

results_df = pd.DataFrame(results)
print(results_df.head())


results_df = results_df.dropna()
# results_df = results_df.dropna() 
# # get data types for each column 
results_df

Passed all tests Hits Allowed Daniel Schneemann
Passed all tests Pitcher Strikeouts Daniel Schneemann
Passed all tests Pitching Outs Daniel Schneemann
Passed all tests Walks Allowed Daniel Schneemann
Passed all tests Hits+Runs+RBIs Daniel Schneemann
Passed all tests Total Bases Daniel Schneemann
Passed all tests Runs Daniel Schneemann
Passed all tests Walks Daniel Schneemann
Passed all tests Hits Allowed Shane Baz
Passed all tests Pitcher Strikeouts Shane Baz
Passed all tests Pitching Outs Shane Baz
Passed all tests Walks Allowed Shane Baz
Passed all tests Hits+Runs+RBIs Shane Baz
Passed all tests Total Bases Shane Baz
Passed all tests Runs Shane Baz
Passed all tests Walks Shane Baz
Passed all tests Hits Allowed Michael Lorenzen
Passed all tests Pitcher Strikeouts Michael Lorenzen
Passed all tests Pitching Outs Michael Lorenzen
Passed all tests Walks Allowed Michael Lorenzen
Passed all tests Hits+Runs+RBIs Michael Lorenzen
Passed all tests Total Bases Michael Lorenzen
Passed all tests Runs Michael Lorenzen
Passed all tests Walks Michael Lorenzen
Passed all tests Hits Allowed Corbin Burnes
Passed all tests Pitcher Strikeouts Corbin Burnes
Passed all tests Pitching Outs Corbin Burnes
Passed all tests Walks Allowed Corbin Burnes
Passed all tests Hits+Runs+RBIs Corbin Burnes
Passed all tests Total Bases Corbin Burnes
Passed all tests Runs Corbin Burnes
Passed all tests Walks Corbin Burnes
Passed all tests Hits Allowed Jose Berrios
Passed all tests Pitcher Strikeouts Jose Berrios
Passed all tests Pitching Outs Jose Berrios
Passed all tests Walks Allowed Jose Berrios
Passed all tests Hits+Runs+RBIs Jose Berrios
Passed all tests Total Bases Jose Berrios
Passed all tests Runs Jose Berrios
Passed all tests Walks Jose Berrios
Passed all tests Hits Allowed Chad Patrick
Passed all tests Pitcher Strikeouts Chad Patrick
Passed all tests Pitching Outs Chad Patrick
Passed all tests Walks Allowed Chad Patrick
Passed all tests Hits+Runs+RBIs Chad Patrick
Passed all tests Total Bases Chad Patrick
Passed all tests Runs Chad Patrick
Passed all tests Walks Chad Patrick
Passed all tests Hits Allowed Shane Smith
Passed all tests Pitcher Strikeouts Shane Smith
Passed all tests Pitching Outs Shane Smith
Passed all tests Walks Allowed Shane Smith
Passed all tests Hits+Runs+RBIs Shane Smith
Passed all tests Total Bases Shane Smith
Passed all tests Runs Shane Smith
Passed all tests Walks Shane Smith
Passed all tests Hits Allowed Matthew Liberatore
Passed all tests Pitcher Strikeouts Matthew Liberatore
Passed all tests Pitching Outs Matthew Liberatore
Passed all tests Walks Allowed Matthew Liberatore
Passed all tests Hits+Runs+RBIs Matthew Liberatore
Passed all tests Total Bases Matthew Liberatore
Passed all tests Runs Matthew Liberatore
Passed all tests Walks Matthew Liberatore
Passed all tests Hits Allowed Will Warren
Passed all tests Pitcher Strikeouts Will Warren
Passed all tests Pitching Outs Will Warren
Passed all tests Walks Allowed Will Warren
Passed all tests Hits+Runs+RBIs Will Warren
Passed all tests Total Bases Will Warren
Passed all tests Runs Will Warren
Passed all tests Walks Will Warren
Passed all tests Hits Allowed Michael King
Passed all tests Pitcher Strikeouts Michael King
Passed all tests Pitching Outs Michael King
Passed all tests Walks Allowed Michael King
Passed all tests Hits+Runs+RBIs Michael King
Passed all tests Total Bases Michael King
Passed all tests Runs Michael King
Passed all tests Walks Michael King
Passed all tests Hits Allowed Luis Severino
Passed all tests Pitcher Strikeouts Luis Severino
Passed all tests Pitching Outs Luis Severino
Passed all tests Walks Allowed Luis Severino
Passed all tests Hits+Runs+RBIs Luis Severino
Passed all tests Total Bases Luis Severino
Passed all tests Runs Luis Severino
Passed all tests Walks Luis Severino
Passed all tests Hits Allowed Kyle Hendricks
Passed all tests Pitcher Strikeouts Kyle Hendricks
Passed all tests Pitching Outs Kyle Hendricks
Passed all tests Walks Allowed Kyle Hendricks
Passed all tests Hits+Runs+RBIs Kyle Hendricks
Passed all tests Total Bases Kyle Hendricks
Passed all tests Runs Kyle Hendricks
Passed all tests Walks Kyle Hendricks
Passed all tests Hits Allowed Cody Bellinger
Passed all tests Pitcher Strikeouts Cody Bellinger
Passed all tests Pitching Outs Cody Bellinger
Passed all tests Walks Allowed Cody Bellinger
Passed all tests Hits+Runs+RBIs Cody Bellinger
Passed all tests Total Bases Cody Bellinger
Passed all tests Runs Cody Bellinger
Passed all tests Walks Cody Bellinger
Passed all tests Hits Allowed Logan Webb
Passed all tests Pitcher Strikeouts Logan Webb
Passed all tests Pitching Outs Logan Webb
Passed all tests Walks Allowed Logan Webb
Passed all tests Hits+Runs+RBIs Logan Webb
Passed all tests Total Bases Logan Webb
Passed all tests Runs Logan Webb
Passed all tests Walks Logan Webb
Passed all tests Hits Allowed Ketel Marte
Passed all tests Pitcher Strikeouts Ketel Marte
Passed all tests Pitching Outs Ketel Marte
Passed all tests Walks Allowed Ketel Marte
Passed all tests Hits+Runs+RBIs Ketel Marte
Passed all tests Total Bases Ketel Marte
Passed all tests Runs Ketel Marte
Passed all tests Walks Ketel Marte
Passed all tests Hits Allowed Paul Goldschmidt
Passed all tests Pitcher Strikeouts Paul Goldschmidt
Passed all tests Pitching Outs Paul Goldschmidt
Passed all tests Walks Allowed Paul Goldschmidt
Passed all tests Hits+Runs+RBIs Paul Goldschmidt
Passed all tests Total Bases Paul Goldschmidt
Passed all tests Runs Paul Goldschmidt
Passed all tests Walks Paul Goldschmidt
Passed all tests Hits Allowed Corbin Carroll
Passed all tests Pitcher Strikeouts Corbin Carroll
Passed all tests Pitching Outs Corbin Carroll
Passed all tests Walks Allowed Corbin Carroll
Passed all tests Hits+Runs+RBIs Corbin Carroll
Passed all tests Total Bases Corbin Carroll
Passed all tests Runs Corbin Carroll
Passed all tests Walks Corbin Carroll
Passed all tests Hits Allowed Logan Gilbert
Passed all tests Pitcher Strikeouts Logan Gilbert
Passed all tests Pitching Outs Logan Gilbert
Passed all tests Walks Allowed Logan Gilbert
Passed all tests Hits+Runs+RBIs Logan Gilbert
Passed all tests Total Bases Logan Gilbert
Passed all tests Runs Logan Gilbert
Passed all tests Walks Logan Gilbert
Passed all tests Hits Allowed Yandy Diaz
Passed all tests Pitcher Strikeouts Yandy Diaz
Passed all tests Pitching Outs Yandy Diaz
Passed all tests Walks Allowed Yandy Diaz
Passed all tests Hits+Runs+RBIs Yandy Diaz
Passed all tests Total Bases Yandy Diaz
Passed all tests Runs Yandy Diaz
Passed all tests Walks Yandy Diaz
Passed all tests Hits Allowed Casey Mize
Passed all tests Pitcher Strikeouts Casey Mize
Passed all tests Pitching Outs Casey Mize
Passed all tests Walks Allowed Casey Mize
Passed all tests Hits+Runs+RBIs Casey Mize
Passed all tests Total Bases Casey Mize
Passed all tests Runs Casey Mize
Passed all tests Walks Casey Mize
Passed all tests Hits Allowed Oneil Cruz
Passed all tests Pitcher Strikeouts Oneil Cruz
Passed all tests Pitching Outs Oneil Cruz
Passed all tests Walks Allowed Oneil Cruz
Passed all tests Hits+Runs+RBIs Oneil Cruz
Passed all tests Total Bases Oneil Cruz
Passed all tests Runs Oneil Cruz
Passed all tests Walks Oneil Cruz
Passed all tests Hits Allowed Chris Sale
Passed all tests Pitcher Strikeouts Chris Sale
Passed all tests Pitching Outs Chris Sale
Passed all tests Walks Allowed Chris Sale
Passed all tests Hits+Runs+RBIs Chris Sale
Passed all tests Total Bases Chris Sale
Passed all tests Runs Chris Sale
Passed all tests Walks Chris Sale
Passed all tests Hits Allowed Bryan Reynolds
Passed all tests Pitcher Strikeouts Bryan Reynolds
Passed all tests Pitching Outs Bryan Reynolds
Passed all tests Walks Allowed Bryan Reynolds
Passed all tests Hits+Runs+RBIs Bryan Reynolds
Passed all tests Total Bases Bryan Reynolds
Passed all tests Runs Bryan Reynolds
Passed all tests Walks Bryan Reynolds
Passed all tests Hits Allowed Jackson Chourio
Passed all tests Pitcher Strikeouts Jackson Chourio
Passed all tests Pitching Outs Jackson Chourio
Passed all tests Walks Allowed Jackson Chourio
Passed all tests Hits+Runs+RBIs Jackson Chourio
Passed all tests Total Bases Jackson Chourio
Passed all tests Runs Jackson Chourio
Passed all tests Walks Jackson Chourio
Passed all tests Hits Allowed Bobby Witt Jr.
Passed all tests Pitcher Strikeouts Bobby Witt Jr.
Passed all tests Pitching Outs Bobby Witt Jr.
Passed all tests Walks Allowed Bobby Witt Jr.
Passed all tests Hits+Runs+RBIs Bobby Witt Jr.
Passed all tests Total Bases Bobby Witt Jr.
Passed all tests Runs Bobby Witt Jr.
Passed all tests Walks Bobby Witt Jr.
Passed all tests Hits Allowed Jonathan India
Passed all tests Pitcher Strikeouts Jonathan India
Passed all tests Pitching Outs Jonathan India
Passed all tests Walks Allowed Jonathan India
Passed all tests Hits+Runs+RBIs Jonathan India
Passed all tests Total Bases Jonathan India
Passed all tests Runs Jonathan India
Passed all tests Walks Jonathan India
Passed all tests Hits Allowed Luis Robert
Passed all tests Pitcher Strikeouts Luis Robert
Passed all tests Pitching Outs Luis Robert
Passed all tests Walks Allowed Luis Robert
Passed all tests Hits+Runs+RBIs Luis Robert
Passed all tests Total Bases Luis Robert
Passed all tests Runs Luis Robert
Passed all tests Walks Luis Robert
Passed all tests Hits Allowed Lars Nootbaar
Passed all tests Pitcher Strikeouts Lars Nootbaar
Passed all tests Pitching Outs Lars Nootbaar
Passed all tests Walks Allowed Lars Nootbaar
Passed all tests Hits+Runs+RBIs Lars Nootbaar
Passed all tests Total Bases Lars Nootbaar
Passed all tests Runs Lars Nootbaar
Passed all tests Walks Lars Nootbaar
Passed all tests Hits Allowed Dustin May
Passed all tests Pitcher Strikeouts Dustin May
Passed all tests Pitching Outs Dustin May
Passed all tests Walks Allowed Dustin May
Passed all tests Hits+Runs+RBIs Dustin May
Passed all tests Total Bases Dustin May
Passed all tests Runs Dustin May
Passed all tests Walks Dustin May
Passed all tests Hits Allowed Mike Trout
Passed all tests Pitcher Strikeouts Mike Trout
Passed all tests Pitching Outs Mike Trout
Passed all tests Walks Allowed Mike Trout
Passed all tests Hits+Runs+RBIs Mike Trout
Passed all tests Total Bases Mike Trout
Passed all tests Runs Mike Trout
Passed all tests Walks Mike Trout
Passed all tests Hits Allowed Yordan Alvarez
Passed all tests Pitcher Strikeouts Yordan Alvarez
Passed all tests Pitching Outs Yordan Alvarez
Passed all tests Walks Allowed Yordan Alvarez
Passed all tests Hits+Runs+RBIs Yordan Alvarez
Passed all tests Total Bases Yordan Alvarez
Passed all tests Runs Yordan Alvarez
Passed all tests Walks Yordan Alvarez
Passed all tests Hits Allowed Jose Altuve
Passed all tests Pitcher Strikeouts Jose Altuve
Passed all tests Pitching Outs Jose Altuve
Passed all tests Walks Allowed Jose Altuve
Passed all tests Hits+Runs+RBIs Jose Altuve
Passed all tests Total Bases Jose Altuve
Passed all tests Runs Jose Altuve
Passed all tests Walks Jose Altuve
Passed all tests Hits Allowed Matt Chapman
Passed all tests Pitcher Strikeouts Matt Chapman
Passed all tests Pitching Outs Matt Chapman
Passed all tests Walks Allowed Matt Chapman
Passed all tests Hits+Runs+RBIs Matt Chapman
Passed all tests Total Bases Matt Chapman
Passed all tests Runs Matt Chapman
Passed all tests Walks Matt Chapman
Passed all tests Hits Allowed Fernando Tatis Jr.
Passed all tests Pitcher Strikeouts Fernando Tatis Jr.
Passed all tests Pitching Outs Fernando Tatis Jr.
Passed all tests Walks Allowed Fernando Tatis Jr.
Passed all tests Hits+Runs+RBIs Fernando Tatis Jr.
Passed all tests Total Bases Fernando Tatis Jr.
Passed all tests Runs Fernando Tatis Jr.
Passed all tests Walks Fernando Tatis Jr.
Passed all tests Hits Allowed Jose Ramirez
Passed all tests Pitcher Strikeouts Jose Ramirez
Passed all tests Pitching Outs Jose Ramirez
Passed all tests Walks Allowed Jose Ramirez
Passed all tests Hits+Runs+RBIs Jose Ramirez
Passed all tests Total Bases Jose Ramirez
Passed all tests Runs Jose Ramirez
Passed all tests Walks Jose Ramirez
Passed all tests Hits Allowed Steven Kwan
Passed all tests Pitcher Strikeouts Steven Kwan
Passed all tests Pitching Outs Steven Kwan
Passed all tests Walks Allowed Steven Kwan
Passed all tests Hits+Runs+RBIs Steven Kwan
Passed all tests Total Bases Steven Kwan
Passed all tests Runs Steven Kwan
Passed all tests Walks Steven Kwan
Passed all tests Hits Allowed Manny Machado
Passed all tests Pitcher Strikeouts Manny Machado
Passed all tests Pitching Outs Manny Machado
Passed all tests Walks Allowed Manny Machado
Passed all tests Hits+Runs+RBIs Manny Machado
Passed all tests Total Bases Manny Machado
Passed all tests Runs Manny Machado
Passed all tests Walks Manny Machado
Passed all tests Hits Allowed Jackson Merrill
Passed all tests Pitcher Strikeouts Jackson Merrill
Passed all tests Pitching Outs Jackson Merrill
Passed all tests Walks Allowed Jackson Merrill
Passed all tests Hits+Runs+RBIs Jackson Merrill
Passed all tests Total Bases Jackson Merrill
Passed all tests Runs Jackson Merrill
Passed all tests Walks Jackson Merrill
Passed all tests Hits Allowed Julio Rodriguez
Passed all tests Pitcher Strikeouts Julio Rodriguez
Passed all tests Pitching Outs Julio Rodriguez
Passed all tests Walks Allowed Julio Rodriguez
Passed all tests Hits+Runs+RBIs Julio Rodriguez
Passed all tests Total Bases Julio Rodriguez
Passed all tests Runs Julio Rodriguez
Passed all tests Walks Julio Rodriguez
Passed all tests Hits Allowed Randy Arozarena
Passed all tests Pitcher Strikeouts Randy Arozarena
Passed all tests Pitching Outs Randy Arozarena
Passed all tests Walks Allowed Randy Arozarena
Passed all tests Hits+Runs+RBIs Randy Arozarena
Passed all tests Total Bases Randy Arozarena
Passed all tests Runs Randy Arozarena
Passed all tests Walks Randy Arozarena
Passed all tests Hits Allowed Riley Greene
Passed all tests Pitcher Strikeouts Riley Greene
Passed all tests Pitching Outs Riley Greene
Passed all tests Walks Allowed Riley Greene
Passed all tests Hits+Runs+RBIs Riley Greene
Passed all tests Total Bases Riley Greene
Passed all tests Runs Riley Greene
Passed all tests Walks Riley Greene
Passed all tests Hits Allowed Cal Raleigh
Passed all tests Pitcher Strikeouts Cal Raleigh
Passed all tests Pitching Outs Cal Raleigh
Passed all tests Walks Allowed Cal Raleigh
Passed all tests Hits+Runs+RBIs Cal Raleigh
Passed all tests Total Bases Cal Raleigh
Passed all tests Runs Cal Raleigh
Passed all tests Walks Cal Raleigh
Passed all tests Hits Allowed Kyle Tucker
Passed all tests Pitcher Strikeouts Kyle Tucker
Passed all tests Pitching Outs Kyle Tucker
Passed all tests Walks Allowed Kyle Tucker
Passed all tests Hits+Runs+RBIs Kyle Tucker
Passed all tests Total Bases Kyle Tucker
Passed all tests Runs Kyle Tucker
Passed all tests Walks Kyle Tucker
Passed all tests Hits Allowed Brent Rooker
Passed all tests Pitcher Strikeouts Brent Rooker
Passed all tests Pitching Outs Brent Rooker
Passed all tests Walks Allowed Brent Rooker
Passed all tests Hits+Runs+RBIs Brent Rooker
Passed all tests Total Bases Brent Rooker
Passed all tests Runs Brent Rooker
Passed all tests Walks Brent Rooker
Passed all tests Hits Allowed Seiya Suzuki
Passed all tests Pitcher Strikeouts Seiya Suzuki
Passed all tests Pitching Outs Seiya Suzuki
Passed all tests Walks Allowed Seiya Suzuki
Passed all tests Hits+Runs+RBIs Seiya Suzuki
Passed all tests Total Bases Seiya Suzuki
Passed all tests Runs Seiya Suzuki
Passed all tests Walks Seiya Suzuki
Passed all tests Hits Allowed Lawrence Butler
Passed all tests Pitcher Strikeouts Lawrence Butler
Passed all tests Pitching Outs Lawrence Butler
Passed all tests Walks Allowed Lawrence Butler
Passed all tests Hits+Runs+RBIs Lawrence Butler
Passed all tests Total Bases Lawrence Butler
Passed all tests Runs Lawrence Butler
Passed all tests Walks Lawrence Butler
Passed all tests Hits Allowed Ian Happ
Passed all tests Pitcher Strikeouts Ian Happ
Passed all tests Pitching Outs Ian Happ
Passed all tests Walks Allowed Ian Happ
Passed all tests Hits+Runs+RBIs Ian Happ
Passed all tests Total Bases Ian Happ
Passed all tests Runs Ian Happ
Passed all tests Walks Ian Happ
Passed all tests Hits Allowed Shohei Ohtani
Passed all tests Pitcher Strikeouts Shohei Ohtani
Passed all tests Pitching Outs Shohei Ohtani
Passed all tests Walks Allowed Shohei Ohtani
Passed all tests Hits+Runs+RBIs Shohei Ohtani
Passed all tests Total Bases Shohei Ohtani
Passed all tests Runs Shohei Ohtani
Passed all tests Walks Shohei Ohtani
Passed all tests Hits Allowed Oswaldo Cabrera
Passed all tests Pitcher Strikeouts Oswaldo Cabrera
Passed all tests Pitching Outs Oswaldo Cabrera
Passed all tests Walks Allowed Oswaldo Cabrera
Passed all tests Hits+Runs+RBIs Oswaldo Cabrera
Passed all tests Total Bases Oswaldo Cabrera
Passed all tests Runs Oswaldo Cabrera
Passed all tests Walks Oswaldo Cabrera
Passed all tests Hits Allowed Austin Wells
Passed all tests Pitcher Strikeouts Austin Wells
Passed all tests Pitching Outs Austin Wells
Passed all tests Walks Allowed Austin Wells
Passed all tests Hits+Runs+RBIs Austin Wells
Passed all tests Total Bases Austin Wells
Passed all tests Runs Austin Wells
Passed all tests Walks Austin Wells
Passed all tests Hits Allowed Mookie Betts
Passed all tests Pitcher Strikeouts Mookie Betts
Passed all tests Pitching Outs Mookie Betts
Passed all tests Walks Allowed Mookie Betts
Passed all tests Hits+Runs+RBIs Mookie Betts
Passed all tests Total Bases Mookie Betts
Passed all tests Runs Mookie Betts
Passed all tests Walks Mookie Betts
Passed all tests Hits Allowed Matt Olson
Passed all tests Pitcher Strikeouts Matt Olson
Passed all tests Pitching Outs Matt Olson
Passed all tests Walks Allowed Matt Olson
Passed all tests Hits+Runs+RBIs Matt Olson
Passed all tests Total Bases Matt Olson
Passed all tests Runs Matt Olson
Passed all tests Walks Matt Olson
Passed all tests Hits Allowed Geraldo Perdomo
Passed all tests Pitcher Strikeouts Geraldo Perdomo
Passed all tests Pitching Outs Geraldo Perdomo
Passed all tests Walks Allowed Geraldo Perdomo
Passed all tests Hits+Runs+RBIs Geraldo Perdomo
Passed all tests Total Bases Geraldo Perdomo
Passed all tests Runs Geraldo Perdomo
Passed all tests Walks Geraldo Perdomo
Passed all tests Hits Allowed Marcell Ozuna
Passed all tests Pitcher Strikeouts Marcell Ozuna
Passed all tests Pitching Outs Marcell Ozuna
Passed all tests Walks Allowed Marcell Ozuna
Passed all tests Hits+Runs+RBIs Marcell Ozuna
Passed all tests Total Bases Marcell Ozuna
Passed all tests Runs Marcell Ozuna
Passed all tests Walks Marcell Ozuna
Passed all tests Hits Allowed Ben Rice
Passed all tests Pitcher Strikeouts Ben Rice
Passed all tests Pitching Outs Ben Rice
Passed all tests Walks Allowed Ben Rice
Passed all tests Hits+Runs+RBIs Ben Rice
Passed all tests Total Bases Ben Rice
Passed all tests Runs Ben Rice
Passed all tests Walks Ben Rice
Passed all tests Hits Allowed Austin Riley
Passed all tests Pitcher Strikeouts Austin Riley
Passed all tests Pitching Outs Austin Riley
Passed all tests Walks Allowed Austin Riley
Passed all tests Hits+Runs+RBIs Austin Riley
Passed all tests Total Bases Austin Riley
Passed all tests Runs Austin Riley
Passed all tests Walks Austin Riley
Passed all tests Hits Allowed Thomas Harrington
Passed all tests Pitcher Strikeouts Thomas Harrington
Passed all tests Pitching Outs Thomas Harrington
Passed all tests Walks Allowed Thomas Harrington
Passed all tests Hits+Runs+RBIs Thomas Harrington
Passed all tests Total Bases Thomas Harrington
Passed all tests Runs Thomas Harrington
Passed all tests Walks Thomas Harrington
Passed all tests Hits Allowed Enmanuel Valdez
Passed all tests Pitcher Strikeouts Enmanuel Valdez
Passed all tests Pitching Outs Enmanuel Valdez
Passed all tests Walks Allowed Enmanuel Valdez
Passed all tests Hits+Runs+RBIs Enmanuel Valdez
Passed all tests Total Bases Enmanuel Valdez
Passed all tests Runs Enmanuel Valdez
Passed all tests Walks Enmanuel Valdez
Passed all tests Hits Allowed Bo Bichette

,name,stat,line,dk_line,dk_over_line,dk_under_line
4,Daniel Schneemann,Hits+Runs+RBIs,0.5,0.5,1.833333,1.909091
9,Shane Baz,Pitcher Strikeouts,5.0,4.5,1.625000,2.250000
17,Michael Lorenzen,Pitcher Strikeouts,4.0,3.5,1.666667,2.150000
25,Corbin Burnes,Pitcher Strikeouts,5.0,5.5,2.050000,1.714286
33,Jose Berrios,Pitcher Strikeouts,5.0,5.5,2.300000,1.588235
...,...,...,...,...,...,...
836,Miguel Andujar,Hits+Runs+RBIs,1.5,1.5,1.952381,1.769231
845,Drake Baldwin,Total Bases,0.5,0.5,1.833333,1.869565
853,Andy Pages,Total Bases,0.5,0.5,1.769231,1.909091
861,Jarred Kelenic,Total Bases,0.5,0.5,1.952381,1.769231
868,Tommy Edman,Hits+Runs+RBIs,1.5,1.5,2.000000,1.740741

In [25]:
from scipy.stats import poisson
from scipy.optimize import minimize

def implied_odds_at_point(draft_kings_line, lambda_):
        # DraftKings line is an integer threshold (either x.5 or x.0, where x.0 has a push opportunity, so be wary)
        # use the pdf function to get the exact probability of the line
        exact_odds = poisson.pmf(draft_kings_line, lambda_)
        return ((1 - poisson.cdf(draft_kings_line, lambda_)) / (1-exact_odds))


def get_implied_odds(pp_line, draft_kings_line, draft_kings_over_line):
    # Function to solve for lambda
    def solve_lambda(lambda_):
        return abs(implied_odds_at_point(draft_kings_line, lambda_) - (1/draft_kings_over_line))

    # Optimize to find lambda
    # essentially, were setting the two sides of the minus sign to be equal
    result = minimize(solve_lambda, x0=[draft_kings_line], bounds=[(0, None)]) 
    lambda_ = result.x[0]
    print(lambda_, pp_line, draft_kings_line, draft_kings_over_line)
    
    # Calculate the probability of exceeding the pp_line
    prob_over_pp_line = (1 - poisson.cdf(pp_line, lambda_)) / (1 - poisson.pmf(pp_line, lambda_))
    return prob_over_pp_line

results_df["implied_odds"] = results_df.apply(lambda row: get_implied_odds(row["line"], row["dk_line"], row["dk_over_line"]), axis=1)

0.788457350029032 0.5 0.5 1.83333334
5.329986174497497 5.0 4.5 1.625
4.1752627250292935 4.0 3.5 1.66666667
5.598031069104649 5.0 5.5 2.05
5.289977246746375 5.0 5.5 2.3
3.4592335100200127 3.0 3.5 2.2
11.969270348967404 11.5 11.5 1.86956522
4.670908880858543 4.0 4.5 2.0
4.217577206180992 4.0 3.5 1.6451613
13.781225722603383 13.5 13.5 1.95238096
4.4853646300651855 4.0 4.5 2.15
5.74291150086564 5.5 5.5 1.95238096
17.34614646682326 16.5 16.5 1.76923077
5.289977246746375 5.0 5.5 2.3
4.7368954289694765 4.5 4.5 1.95238096
1.7923521421894872 1.5 1.5 1.86956522
1.7923521421894872 1.5 1.5 1.86956522
8.199097436462159 8.0 7.5 1.74074075
4.977532333685147 4.5 4.5 1.8
1.7555569086465337 1.5 1.5 1.90909091
6.316798179097609 6.0 6.5 2.25
1.7555569086465337 1.5 1.5 1.90909091
0.7178397857801238 0.5 0.5 1.95238096
1.8963659533191415 1.5 1.5 1.76923077
0.8329091186540821 0.5 0.5 1.76923077
1.8626930092376819 1.5 1.5 1.8
4.413251367788138 4.0 3.5 1.55555556
1.8626930092376819 1.5 1.5 1.8
0.7419373392055679 0.5 0.5 1.90909091
0.7419373392055679 0.5 0.5 1.90909091
1.7175824771235049 1.5 1.5 1.95238096
1.8963659533191415 1.5 1.5 1.76923077
1.7923521421894872 1.5 1.5 1.86956522
1.7555569086465337 1.5 1.5 1.90909091
0.765467838872946 0.5 0.5 1.86956522
0.8109302160708561 0.5 0.5 1.8
1.8280419279375388 1.5 1.5 1.83333334
1.7175824771235049 1.5 1.5 1.95238096
1.8280419279375388 1.5 1.5 1.83333334
0.765467838872946 0.5 0.5 1.86956522
1.7555569086465337 1.5 1.5 1.90909091
0.6931471755599454 0.5 0.5 2.0
0.8109302160708561 0.5 0.5 1.8
0.8109302160708561 0.5 0.5 1.8
1.7555569086465337 1.5 1.5 1.90909091
0.8329091186540821 0.5 0.5 1.76923077
0.788457350029032 0.5 0.5 1.83333334
1.7175824771235049 1.5 1.5 1.95238096
0.7419373392055679 0.5 0.5 1.90909091
1.7923521421894872 1.5 1.5 1.86956522
3.614235452869334 3.5 3.5 2.05
13.170908624945763 12.5 12.5 1.8
0.788457350029032 0.5 0.5 1.83333334
1.7923521421894872 1.5 1.5 1.86956522
0.788457350029032 0.5 0.5 1.83333334
1.8626930092376819 1.5 1.5 1.8
1.7555569086465337 1.5 1.5 1.90909091
0.765467838872946 0.5 0.5 1.86956522
3.3266052127942665 3.0 3.5 2.35
1.7923521421894872 1.5 1.5 1.86956522
1.8280419279375388 1.5 1.5 1.83333334
1.7923521421894872 1.5 1.5 1.86956522
1.8626930092376819 1.5 1.5 1.8
1.7555569086465337 1.5 1.5 1.90909091
1.8626930092376819 1.5 1.5 1.8
1.8626930092376819 1.5 1.5 1.8
1.8280419279375388 1.5 1.5 1.83333334
1.7923521421894872 1.5 1.5 1.86956522
1.7555569086465337 1.5 1.5 1.90909091
1.8280419279375388 1.5 1.5 1.83333334
1.7555569086465337 1.5 1.5 1.90909091
1.7175824771235049 1.5 1.5 1.95238096
0.8544153188689835 0.5 0.5 1.74074075
0.8329091186540821 0.5 0.5 1.76923077
4.7368954289694765 4.5 4.5 1.95238096
1.8626930092376819 1.5 1.5 1.8
0.765467838872946 0.5 0.5 1.86956522
1.7175824771235049 1.5 1.5 1.95238096
1.7175824771235049 1.5 1.5 1.95238096
1.7175824771235049 1.5 1.5 1.95238096
0.7419373392055679 0.5 0.5 1.90909091
1.8963659533191415 1.5 1.5 1.76923077
1.8280419279375388 1.5 1.5 1.83333334
0.7419373392055679 0.5 0.5 1.90909091
4.217577206180992 4.0 3.5 1.6451613
1.8626930092376819 1.5 1.5 1.8
1.8626930092376819 1.5 1.5 1.8
1.8626930092376819 1.5 1.5 1.8
1.7175824771235049 1.5 1.5 1.95238096
1.7175824771235049 1.5 1.5 1.95238096
0.8329091186540821 0.5 0.5 1.76923077
0.765467838872946 0.5 0.5 1.86956522
0.7419373392055679 0.5 0.5 1.90909091
1.7923521421894872 1.5 1.5 1.86956522
1.7555569086465337 1.5 1.5 1.90909091
0.7419373392055679 0.5 0.5 1.90909091
0.8754687294777083 0.5 0.5 1.71428572
0.8329091186540821 0.5 0.5 1.76923077
0.765467838872946 0.5 0.5 1.86956522
0.7419373392055679 0.5 0.5 1.90909091
5.670161183585448 5.0 5.5 2.0
0.8329091186540821 0.5 0.5 1.76923077
1.8280419279375388 1.5 1.5 1.83333334
1.7175824771235049 1.5 1.5 1.95238096
1.7175824771235049 1.5 1.5 1.95238096
0.788457350029032 0.5 0.5 1.83333334
0.8329091186540821 0.5 0.5 1.76923077
0.7178397857801238 0.5 0.5 1.95238096
1.6783469850166612 1.5 1.5 2.0

In [26]:
results_df.sort_values(by="implied_odds", ascending=False)

,name,stat,line,dk_line,dk_over_line,dk_under_line,implied_odds
49,Shane Smith,Pitcher Strikeouts,4.0,4.5,2.000000,1.740741,0.614035
801,Justin Steele,Pitcher Strikeouts,5.0,5.5,2.000000,1.769231,0.601232
25,Corbin Burnes,Pitcher Strikeouts,5.0,5.5,2.050000,1.714286,0.587537
781,Rowdy Tellez,Total Bases,0.5,0.5,1.714286,1.952381,0.583333
41,Chad Patrick,Pitcher Strikeouts,3.0,3.5,2.200000,1.625000,0.580519
...,...,...,...,...,...,...,...
137,Logan Gilbert,Pitcher Strikeouts,8.0,7.5,1.740741,2.000000,0.505628
17,Michael Lorenzen,Pitcher Strikeouts,4.0,3.5,1.666667,2.150000,0.503328
868,Tommy Edman,Hits+Runs+RBIs,1.5,1.5,2.000000,1.740741,0.500000
382,Shohei Ohtani,Runs,0.5,0.5,2.000000,1.740741,0.500000
449,Thomas Harrington,Pitcher Strikeouts,3.5,3.5,2.050000,1.740741,0.487805

In [27]:
results_df = results_df[results_df['line'] == results_df['dk_line']]
results_df.sort_values(by='dk_over_line', ascending=True)

,name,stat,line,dk_line,dk_over_line,dk_under_line,implied_odds
781,Rowdy Tellez,Total Bases,0.5,0.5,1.714286,1.952381,0.583333
605,Kyle Isbel,Total Bases,0.5,0.5,1.740741,1.952381,0.574468
668,Jung Hoo Lee,Hits+Runs+RBIs,1.5,1.5,1.769231,1.952381,0.565217
198,Bobby Witt Jr.,Runs,0.5,0.5,1.769231,1.952381,0.565217
197,Bobby Witt Jr.,Total Bases,1.5,1.5,1.769231,1.909091,0.565217
...,...,...,...,...,...,...,...
644,Ryan Jeffers,Hits+Runs+RBIs,1.5,1.5,1.952381,1.769231,0.512195
660,LaMonte Wade Jr.,Hits+Runs+RBIs,1.5,1.5,1.952381,1.769231,0.512195
382,Shohei Ohtani,Runs,0.5,0.5,2.000000,1.740741,0.500000
868,Tommy Edman,Hits+Runs+RBIs,1.5,1.5,2.000000,1.740741,0.500000
449,Thomas Harrington,Pitcher Strikeouts,3.5,3.5,2.050000,1.740741,0.487805

In [28]:
results_df.sort_values(by='dk_over_line', ascending=False)

,name,stat,line,dk_line,dk_over_line,dk_under_line,implied_odds
449,Thomas Harrington,Pitcher Strikeouts,3.5,3.5,2.050000,1.740741,0.487805
868,Tommy Edman,Hits+Runs+RBIs,1.5,1.5,2.000000,1.740741,0.500000
382,Shohei Ohtani,Runs,0.5,0.5,2.000000,1.740741,0.500000
828,Michael Busch,Hits+Runs+RBIs,1.5,1.5,1.952381,1.769231,0.512195
617,Simeon Woods Richardson,Pitcher Strikeouts,4.5,4.5,1.952381,1.800000,0.512195
...,...,...,...,...,...,...,...
788,Jake Rogers,Hits+Runs+RBIs,0.5,0.5,1.769231,1.952381,0.565217
613,MJ Melendez,Total Bases,0.5,0.5,1.769231,1.909091,0.565217
733,Kyle Manzardo,Total Bases,0.5,0.5,1.769231,1.909091,0.565217
605,Kyle Isbel,Total Bases,0.5,0.5,1.740741,1.952381,0.574468
781,Rowdy Tellez,Total Bases,0.5,0.5,1.714286,1.952381,0.583333

In [29]:
import math 
math.sqrt(3)

1.7320508075688772

In [30]:
1 / math.sqrt(3)

0.5773502691896258

In [31]:
1 - (0.487 - (115 / 210 - 0.5))

0.5606190476190477