We'll use this script to compare lines from the two sites.

A reminder that for a double to be a greater value on PrizePicks than DraftKings, 
the two bets must multiply to a value lesser than three.

In [19]:
# from draft_kings import get_dk_data# this will run the script that scrapes the data into the json file we will use
import sys
sys.path.append('..')  # Add the parent directory to the sys.path
from constants import *
from pp_scrape import get_data

In [20]:
import json, csv, math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [21]:
COLLEGE_BASKETBALL = "20"
MLB = "2"
NBA = "7"

# get_dk_data("cbb") # this will run the script that scrapes the data into the json file we will use
get_data(COLLEGE_BASKETBALL) # this will run the script that scrapes the data into the json file we will use

268 0
xx

[{'name': 'Johni Broome',
  'opponent': 'ALST',
  'Points': 20.5,
  'Fantasy Score': 46.5,
  'Pts+Rebs+Asts': 37.5,
  'Pts+Rebs': 33.5,
  'Pts+Asts': 26.5,
  'Rebs+Asts': 14.5},
 {'name': 'Colin Smalls',
  'opponent': 'MSM',
  'Turnovers': 0.5,
  'Pts+Rebs': 10.5,
  'Pts+Asts': 9.5,
  'Pts+Rebs+Asts': 11.5,
  'Points': 8},
 {'name': 'Elijah Stephens',
  'opponent': 'MSM',
  'Pts+Rebs': 12.5,
  'Pts+Rebs+Asts': 16.5,
  'Pts+Asts': 13.5,
  'Rebs+Asts': 7,
  'Fantasy Score': 21.5,
  'Steals': 1.5,
  'Points': 9.5},
 {'name': 'Lincoln Ball',
  'opponent': 'MSM',
  'Rebs+Asts': 7.5,
  'Pts+Rebs+Asts': 12.5,
  'Pts+Asts': 6.5,
  'Assists': 1.5,
  'Pts+Rebs': 11},
 {'name': 'Matt Rogers',
  'opponent': 'MSM',
  'Rebs+Asts': 7,
  'Pts+Rebs': 22.5,
  'Fantasy Score': 27.5,
  'Points': 16.5,
  'Pts+Asts': 18.5,
  'Pts+Rebs+Asts': 23.5},
 {'name': 'Greg Jones',
  'opponent': 'MSM',
  'Pts+Rebs+Asts': 15,
  'Pts+Rebs': 14,
  'Points': 10,
  'Pts+Asts': 11},
 {'name': 'Dola Adebayo',
  'opponent': 'AMER',
  'Fantasy Score': 26.5,
  'Pts+Rebs': 20.5,
  'Pts+Rebs+Asts': 21.5,
  'Points': 13.5,
  'Rebounds': 6.5},
 {'name': 'Dallas Hobbs',
  'opponent': 'AMER',
  'Pts+Rebs': 17,
  'Points': 13,
  'Pts+Rebs+Asts': 20,
  'Steals': 0.5,
  'Turnovers': 2.5,
  'Fantasy Score': 22.5},
 {'name': 'Dailyn Swain',
  'opponent': 'TEX',
  'Assists': 2.5,
  'Rebounds': 6,
  'Pts+Asts': 14.5,
  'Turnovers': 1.5,
  'Points': 12,
  'Rebs+Asts': 8.5,
  'Pts+Rebs+Asts': 20.5,
  'Pts+Rebs': 18,
  'Fantasy Score': 25.5},
 {'name': 'Dayvion McKnight',
  'opponent': 'TEX',
  'Pts+Rebs+Asts': 15.5,
  'Pts+Rebs': 12,
  'Points': 9,
  'Pts+Asts': 12.5,
  'Turnovers': 1.5},
 {'name': 'Marcus Foster',
  'opponent': 'TEX',
  'Rebounds': 6,
  'Pts+Rebs': 13.5,
  'Pts+Rebs+Asts': 15,
  'Pts+Asts': 9,
  'Points': 7.5},
 {'name': 'Ryan Conwell',
  'opponent': 'TEX',
  'Pts+Asts': 21,
  'Assists': 2.5,
  'Pts+Rebs+Asts': 24,
  'Pts+Rebs': 21,
  'Points': 18.5,
  'Fantasy Score': 27.5},
 {'name': 'Zach Freemantle',
  'opponent': 'TEX',
  'Pts+Rebs': 25,
  'Rebounds': 7,
  'Pts+Rebs+Asts': 26.5,
  'Pts+Asts': 19.5,
  'Rebs+Asts': 9,
  'Points': 17.5,
  'Fantasy Score': 31.5},
 {'name': 'Arthur Kaluma',
  'opponent': 'XAV',
  'Fantasy Score': 24.5,
  'Points': 11.5,
  'Pts+Asts': 12.5,
  'Rebs+Asts': 8,
  'Assists': 1.5,
  'Rebounds': 6.5,
  '3-PT Made': 0.5,
  'Pts+Rebs+Asts': 19.5,
  'Pts+Rebs': 18},
 {'name': 'Tre Johnson',
  'opponent': 'XAV',
  'Fantasy Score': 28.5,
  'Rebs+Asts': 6.5,
  'Pts+Rebs': 22,
  'Points': 19,
  'Pts+Rebs+Asts': 25.5,
  'Assists': 3.5,
  'Pts+Asts': 22.5},
 {'name': 'Jordan Pope',
  'opponent': 'XAV',
  'Pts+Rebs+Asts': 14.5,
  'Pts+Rebs': 12.5,
  'Steals': 0.5,
  'Pts+Asts': 11.5,
  'Points': 10},
 {'name': 'Kadin Shedrick',
  'opponent': 'XAV',
  'Points': 8.5,
  'Pts+Rebs': 14,
  'Rebounds': 5.5,
  'Pts+Rebs+Asts': 15},
 {'name': 'Tramon Mark',
  'opponent': 'XAV',
  'Points': 12.5,
  'Pts+Asts': 13.5,
  'Pts+Rebs': 16.5,
  'Rebs+Asts': 6,
  'Pts+Rebs+Asts': 17.5},
 {'name': 'Jackson McAndrew',
  'opponent': 'LOU',
  'Rebs+Asts': 5.5,
  'Pts+Asts': 7.5,
  'Pts+Rebs+Asts': 12.5,
  'Points': 6.5},
 {'name': 'Jamiya Neal',
  'opponent': 'LOU',
  'Pts+Rebs': 18.5,
  'Turnovers': 2.5,
  'Pts+Asts': 16.5,
  'Points': 12.5,
  'Fantasy Score': 24.5,
  '3-PT Made': 1.5,
  'Pts+Rebs+Asts': 22.5},
 {'name': 'Jasen Green',
  'opponent': 'LOU',
  'Points': 7,
  'Pts+Asts': 8.5,
  'Pts+Rebs+Asts': 12.5,
  'Pts+Rebs': 11.5},
 {'name': 'Ryan Kalkbrenner',
  'opponent': 'LOU',
  'Pts+Rebs+Asts': 30.5,
  'Pts+Asts': 22.5,
  'Points': 20.5,
  'Rebs+Asts': 10.5,
  'Pts+Rebs': 29.5,
  'Fantasy Score': 38.5,
  '3-PT Made': 0.5},
 {'name': 'Steven Ashworth',
  'opponent': 'LOU',
  'Rebounds': 4.5,
  'Points': 15,
  'Pts+Rebs': 19.5,
  'Fantasy Score': 29.5,
  'Pts+Rebs+Asts': 25.5,
  'Rebs+Asts': 10.5,
  'Assists': 5.5,
  'Pts+Asts': 22},
 {'name': 'Chucky Hepburn',
  'opponent': 'CREI',
  'Fantasy Score': 31.5,
  'Points': 16.5,
  '3-PT Made': 1.5,
  'Pts+Asts': 21.5,
  'Rebs+Asts': 9.5,
  'Pts+Rebs+Asts': 25.5,
  'Steals': 1.5,
  'Pts+Rebs': 20.5,
  'Assists': 5},
 {'name': "J'Vonne Hadley",
  'opponent': 'CREI',
  'Rebs+Asts': 8.5,
  'Assists': 1.5,
  'Pts+Rebs+Asts': 21,
  'Pts+Rebs': 19,
  'Pts+Asts': 13.5,
  'Points': 12.5},
 {'name': 'Reyne Smith',
  'opponent': 'CREI',
  'Pts+Rebs': 14.5,
  'Pts+Asts': 12.5,
  'Pts+Rebs+Asts': 15.5,
  'Points': 11.5},
 {'name': 'Terrence Edwards Jr.',
  'opponent': 'CREI',
  'Points': 19.5,
  'Rebs+Asts': 7.5,
  'Fantasy Score': 29.5,
  'Pts+Asts': 21.5,
  'Pts+Rebs': 24,
  'Pts+Rebs+Asts': 26.5,
  'Rebounds': 4.5},
 {'name': 'Kezza Giffa',
  'opponent': 'PUR',
  'Points': 14.5,
  'Pts+Rebs': 16.5,
  'Pts+Asts': 16.5,
  'Pts+Rebs+Asts': 19.5},
 {'name': 'Kimani Hamilton',
  'opponent': 'PUR',
  'Pts+Asts': 14.5,
  'Rebs+Asts': 6.5,
  'Pts+Rebs+Asts': 18.5,
  'Pts+Rebs': 16.5,
  'Points': 11.5,
  'Steals': 0.5,
  'Fantasy Score': 20.5},
 {'name': 'Braden Smith',
  'opponent': 'HP',
  'Pts+Rebs': 23.5,
  'Pts+Rebs+Asts': 31.5,
  'Rebs+Asts': 13,
  'Points': 18.5,
  'Turnovers': 2.5,
  'Pts+Asts': 26.5,
  'Fantasy Score': 38.5},
 {'name': 'Trey Kaufman-Renn',
  'opponent': 'HP',
  'Fantasy Score': 35.5,
  'Pts+Asts': 25.5,
  'Points': 23.5,
  'Pts+Rebs+Asts': 32.5,
  'Rebs+Asts': 9,
  'Pts+Rebs': 30.5},
 {'name': 'C.J. Cox',
  'opponent': 'HP',
  'Pts+Rebs+Asts': 9.5,
  'Assists': 0.5,
  'Points': 5.5},
 {'name': 'Fletcher Loyer',
  'opponent': 'HP',
  'Points': 14.5,
  'Pts+Rebs+Asts': 18.5,
  'Pts+Rebs': 17.5,
  'Steals': 0.5,
  'Pts+Asts': 16},
 {'name': 'Myles Colvin', 'opponent': 'HP', 'Points': 5.5},
 {'name': 'Caleb Furst',
  'opponent': 'HP',
  'Pts+Rebs+Asts': 7.5,
  'Rebounds': 4.5},
 {'name': 'Money Williams',
  'opponent': 'WIS',
  'Pts+Rebs+Asts': 18.5,
  'Points': 12.5},
 {'name': 'Brandon Whitney',
  'opponent': 'WIS',
  '3-PT Made': 0.5,
  'Pts+Rebs+Asts': 14.5,
  'Pts+Rebs': 12,
  'Points': 9.5,
  'Pts+Asts': 12,
  'Steals': 0.5},
 {'name': 'John Tonje',
  'opponent': 'MONT',
  'Fantasy Score': 33,
  'Rebounds': 6.5,
  'Pts+Asts': 23.5,
  'Rebs+Asts': 8.5,
  'Pts+Rebs': 28,
  'Pts+Rebs+Asts': 30.5,
  'Steals': 0.5,
  'Points': 21.5},
 {'name': 'Joe Pridgen',
  'opponent': 'WIS',
  'Turnovers': 1.5,
  'Pts+Asts': 10.5,
  'Blocked Shots': 0.5,
  'Points': 9.5,
  'Pts+Rebs+Asts': 16.5,
  'Pts+Rebs': 15.5,
  'Rebs+Asts': 6.5,
  'Steals': 0.5},
 {'name': 'John Blackwell',
  'opponent': 'MONT',
  'Fantasy Score': 26.5,
  '3-PT Made': 1.5,
  'Turnovers': 1.5,
  'Points': 16.5,
  'Rebs+Asts': 7,
  'Pts+Asts': 19,
  'Pts+Rebs+Asts': 24.5,
  'Pts+Rebs': 22},
 {'name': 'Kai Johnson',
  'opponent': 'WIS',
  'Points': 10,
  'Pts+Rebs+Asts': 15,
  'Pts+Asts': 12,
  'Rebs+Asts': 4.5,
  'Steals': 0.5,
  'Pts+Rebs': 13},
 {'name': 'Malik Moore',
  'opponent': 'WIS',
  'Assists': 1.5,
  'Points': 9.5,
  'Pts+Rebs+Asts': 14.5,
  '3-PT Made': 1.5,
  'Steals': 0.5,
  'Pts+Asts': 11.5,
  'Pts+Rebs': 13},
 {'name': "Te'Jon Sawyer",
  'opponent': 'WIS',
  'Pts+Asts': 10,
  'Pts+Rebs+Asts': 14,
  'Rebs+Asts': 5.5,
  'Points': 8.5,
  'Pts+Rebs': 13},
 {'name': 'Kamari McGee',
  'opponent': 'MONT',
  'Turnovers': 0.5,
  'Pts+Asts': 7.5,
  'Pts+Rebs': 9,
  'Pts+Rebs+Asts': 10.5,
  'Points': 6},
 {'name': 'Max Klesmit',
  'opponent': 'MONT',
  'Pts+Asts': 10.5,
  'Points': 8.5,
  'Pts+Rebs+Asts': 13.5,
  'Rebounds': 2.5,
  'Pts+Rebs': 11.5},
 {'name': 'Nolan Winter',
  'opponent': 'MONT',
  'Points': 9,
  'Pts+Rebs': 14,
  'Pts+Asts': 9.5},
 {'name': 'Steven Crowl',
  'opponent': 'MONT',
  'Rebounds': 5.5,
  'Pts+Rebs+Asts': 18.5,
  'Rebs+Asts': 8,
  'Turnovers': 1.5,
  'Points': 10.5,
  'Pts+Asts': 13.5,
  'Pts+Rebs': 16.5},
 {'name': 'Carter Gilmore',
  'opponent': 'MONT',
  'Pts+Asts': 6.5,
  '3-PT Made': 0.5,
  'Pts+Rebs': 7.5},
 {'name': 'Emanuel Sharp',
  'opponent': 'SIUE',
  'Pts+Rebs+Asts': 17.5,
  'Pts+Rebs': 16.5,
  'Pts+Asts': 13.5,
  'Points': 12.5},
 {'name': 'LJ Cryer',
  'opponent': 'SIUE',
  'Points': 15,
  'Fantasy Score': 22.5,
  'Pts+Rebs+Asts': 19.5,
  'Pts+Rebs': 17.5,
  'Rebs+Asts': 4.5,
  'Pts+Asts': 16.5},
 {'name': 'Milos Uzan',
  'opponent': 'SIUE',
  'Points': 12.5,
  'Fantasy Score': 22.5,
  'Rebounds': 2.5,
  'Rebs+Asts': 7,
  'Pts+Rebs+Asts': 19.5,
  'Pts+Rebs': 15.5,
  'Pts+Asts': 16.5},
 {'name': 'Brian Taylor', 'opponent': 'HOU', 'Points': 7},
 {'name': "Ray'Sean Taylor",
  'opponent': 'HOU',
  'Rebs+Asts': 6,
  'Pts+Rebs': 17.5,
  'Pts+Asts': 16.5,
  'Points': 14.5,
  'Pts+Rebs+Asts': 20.5,
  'Fantasy Score': 22.5},
 {'name': 'Ring Malith', 'opponent': 'HOU', 'Points': 8},
 {'name': 'Amarr Knox',
  'opponent': 'AUB',
  'Pts+Asts': 15.5,
  'Turnovers': 1.5,
  'Rebs+Asts': 3.5,
  'Pts+Rebs': 15.5,
  'Pts+Rebs+Asts': 17.5},
 {'name': 'CJ Hines',
  'opponent': 'AUB',
  'Pts+Rebs+Asts': 15.5,
  'Pts+Rebs': 13.5,
  'Pts+Asts': 13.5},
 {'name': 'T.J. Madlock',
  'opponent': 'AUB',
  'Fantasy Score': 23.5,
  'Pts+Rebs': 18,
  'Pts+Rebs+Asts': 20,
  'Points': 11.5,
  'Pts+Asts': 13.5},
 {'name': 'Chad Baker-Mazara',
  'opponent': 'ALST',
  'Pts+Rebs+Asts': 20,
  'Pts+Rebs': 17,
  'Pts+Asts': 16.5,
  'Fantasy Score': 26.5,
  'Rebs+Asts': 6.5},
 {'name': 'Denver Jones',
  'opponent': 'ALST',
  'Pts+Rebs': 14.5,
  'Rebs+Asts': 5.5,
  'Pts+Rebs+Asts': 17,
  'Pts+Asts': 14.5},
 {'name': 'Dylan Cardwell',
  'opponent': 'ALST',
  'Pts+Rebs': 10,
  'Pts+Rebs+Asts': 11.5},
 {'name': 'Miles Kelly',
  'opponent': 'ALST',
  'Pts+Rebs+Asts': 19.5,
  'Pts+Rebs': 18.5,
  'Pts+Asts': 14.5},
 {'name': 'Tahaad Pettiford',
  'opponent': 'ALST',
  'Pts+Rebs': 14.5,
  'Rebs+Asts': 6,
  'Pts+Rebs+Asts': 17,
  'Pts+Asts': 14,
  'Points': 11},
 {'name': 'Chase Hunter',
  'opponent': 'MCNS',
  'Pts+Rebs+Asts': 22.5,
  'Pts+Rebs': 19.5,
  'Rebs+Asts': 6.5,
  'Pts+Asts': 19,
  'Turnovers': 2.5,
  'Rebounds': 3.5,
  'Points': 15.5,
  'Fantasy Score': 27.5},
 {'name': 'Ian Schieffelin',
  'opponent': 'MCNS',
  'Fantasy Score': 28.5,
  'Pts+Rebs+Asts': 23.5,
  'Rebs+Asts': 11.5,
  'Turnovers': 1.5,
  'Pts+Rebs': 21.5,
  'Points': 11.5,
  'Pts+Asts': 14.5},
 {'name': 'Jaeden Zackery',
  'opponent': 'MCNS',
  'Steals': 1.5,
  'Points': 11.5,
  'Pts+Asts': 14.5,
  'Pts+Rebs': 15,
  'Pts+Rebs+Asts': 18.5,
  'Rebounds': 3.5,
  'Rebs+Asts': 6.5},
 {'name': 'Viktor Lakhin',
  'opponent': 'MCNS',
  'Points': 13.5,
  'Fantasy Score': 28.5,
  'Pts+Rebs': 20,
  'Pts+Asts': 15,
  'Rebs+Asts': 8.5,
  'Pts+Rebs+Asts': 21.5},
 {'name': 'Christian Shumate',
  'opponent': 'CLEM',
  'Pts+Rebs+Asts': 16.5,
  'Pts+Asts': 10.5,
  'Points': 10},
 {'name': 'Javohn Garcia',
  'opponent': 'CLEM',
  'Pts+Asts': 12,
  'Pts+Rebs': 14.5,
  'Rebounds': 3.5,
  'Fantasy Score': 20.5,
  'Pts+Rebs+Asts': 16.5,
  'Points': 10.5},
 {'name': 'Quadir Copeland',
  'opponent': 'CLEM',
  'Fantasy Score': 19.5,
  'Points': 8,
  'Pts+Rebs+Asts': 14.5},
 {'name': 'Sincere Parker', 'opponent': 'CLEM', 'Points': 8.5},
 {'name': 'Egor Demin',
  'opponent': 'VCU',
  'Rebounds': 3.5,
  'Rebs+Asts': 7.5,
  'Pts+Rebs': 13.5,
  'Pts+Rebs+Asts': 17.5,
  'Points': 10,
  'Pts+Asts': 14,
  'Fantasy Score': 21.5},
 {'name': 'Richie Saunders',
  'opponent': 'VCU',
  'Rebs+Asts': 5.5,
  'Turnovers': 1.5,
  'Points': 16.5,
  'Pts+Asts': 18,
  'Pts+Rebs+Asts': 22.5,
  'Fantasy Score': 25.5,
  'Rebounds': 4.5,
  'Pts+Rebs': 21.5},
 {'name': 'Jack Clark',
  'opponent': 'BYU',
  'Rebs+Asts': 8,
  'Pts+Rebs': 16.5,
  'Pts+Rebs+Asts': 18,
  'Points': 10,
  'Rebounds': 6.5,
  'Pts+Asts': 11.5,
  'Assists': 1.5},
 {'name': 'Joe Bamisile',
  'opponent': 'BYU',
  'Fantasy Score': 20.5,
  'Pts+Rebs': 18,
  'Rebs+Asts': 5.5,
  '3-PT Made': 1.5,
  'Points': 13.5,
  'Pts+Rebs+Asts': 19.5,
  'Pts+Asts': 15},
 {'name': 'Max Shulga',
  'opponent': 'BYU',
  'Fantasy Score': 29.5,
  'Pts+Rebs+Asts': 24,
  'Pts+Rebs': 20,
  'Rebs+Asts': 9.5,
  'Pts+Asts': 18.5,
  'Turnovers': 1.5,
  'Points': 14.5,
  'Rebounds': 5.5},
 {'name': 'Luke Bamgboye', 'opponent': 'BYU', 'Pts+Rebs+Asts': 9.5},
 {'name': 'Dallin Hall',
  'opponent': 'VCU',
  'Pts+Asts': 10.5,
  'Pts+Rebs': 9.5,
  'Pts+Rebs+Asts': 12.5,
  'Points': 7.5},
 {'name': 'Keba Keita',
  'opponent': 'VCU',
  'Points': 6.5,
  'Pts+Rebs': 14,
  'Pts+Rebs+Asts': 14.5,
  'Rebs+Asts': 7.5,
  'Pts+Asts': 7.5},
 {'name': 'Mawot Mag', 'opponent': 'VCU', 'Points': 5.5},
 {'name': 'Phillip Russell',
  'opponent': 'BYU',
  'Pts+Rebs': 10.5,
  'Pts+Rebs+Asts': 12.5,
  'Points': 8.5,
  'Pts+Asts': 10.5},
 {'name': 'Zeb Jackson', 'opponent': 'BYU', 'Points': 10},
 {'name': 'Graham Ike',
  'opponent': 'UGA',
  'Pts+Rebs': 24.5,
  'Rebounds': 7.5,
  'Pts+Asts': 18.5,
  'Pts+Rebs+Asts': 25.5,
  'Rebs+Asts': 8.5,
  'Fantasy Score': 30.5,
  'Points': 16.5,
  'Steals': 0.5,
  'Turnovers': 1.5},
 {'name': 'Ryan Nembhard',
  'opponent': 'UGA',
  'Fantasy Score': 31.5,
  'Rebs+Asts': 11.5,
  'Pts+Rebs': 13.5,
  'Pts+Rebs+Asts': 22.5,
  'Pts+Asts': 18.5,
  'Assists': 8.5},
 {'name': 'Khalif Battle',
  'opponent': 'UGA',
  'Pts+Rebs': 17.5,
  'Points': 13.5,
  'Pts+Rebs+Asts': 18.5,
  'Rebounds': 3.5,
  'Pts+Asts': 15.5,
  'Turnovers': 1.5},
 {'name': 'Nolan Hickman',
  'opponent': 'UGA',
  'Pts+Rebs+Asts': 14.5,
  'Points': 10.5,
  'Pts+Rebs': 12.5,
  'Pts+Asts': 12.5},
 {'name': 'Asa Newell',
  'opponent': 'GONZ',
  'Rebounds': 6.5,
  'Fantasy Score': 27.5,
  'Points': 15,
  'Pts+Rebs+Asts': 22.5,
  'Steals': 0.5,
  'Pts+Rebs': 21.5,
  'Pts+Asts': 15.5},
 {'name': 'Blue Cain',
  'opponent': 'GONZ',
  'Points': 11,
  'Pts+Asts': 12.5,
  'Pts+Rebs': 16.5,
  'Pts+Rebs+Asts': 17.5},
 {'name': 'Silas Demary Jr.',
  'opponent': 'GONZ',
  'Pts+Rebs+Asts': 22.5,
  'Pts+Asts': 19.5,
  'Fantasy Score': 27.5,
  'Pts+Rebs': 19.5,
  'Points': 15.5,
  'Rebounds': 3.5},
 {'name': 'Tyrin Lawrence', 'opponent': 'GONZ', 'Steals': 0.5},
 {'name': 'Chaz Lanier',
  'opponent': 'WOF',
  'Fantasy Score': 25.5,
  'Pts+Rebs+Asts': 22.5,
  'Points': 17.5,
  'Pts+Asts': 18,
  'Pts+Rebs': 21},
 {'name': 'Felix Okpara',
  'opponent': 'WOF',
  'Points': 6.5,
  'Blocked Shots': 1.5},
 {'name': 'Igor Milicic',
  'opponent': 'WOF',
  'Rebs+Asts': 6.5,
  'Pts+Rebs+Asts': 16.5,
  'Pts+Asts': 11,
  'Pts+Rebs': 14.5},
 {'name': 'Jahmai Mashack', 'opponent': 'WOF', 'Points': 6.5},
 {'name': 'Jordan Gainey',
  'opponent': 'WOF',
  'Pts+Rebs+Asts': 17.5,
  'Points': 11.5,
  '3-PT Made': 1.5,
  'Pts+Asts': 13.5,
  'Rebs+Asts': 5.5,
  'Pts+Rebs': 15.5},
 {'name': 'Zakai Zeigler',
  'opponent': 'WOF',
  'Points': 15.5,
  'Pts+Rebs': 18.5,
  'Pts+Rebs+Asts': 25.5,
  'Rebs+Asts': 10.5,
  'Assists': 7,
  'Fantasy Score': 33.5,
  'Pts+Asts': 23},
 {'name': 'Corey Tripp',
  'opponent': 'TENN',
  'Pts+Rebs': 15.5,
  'Pts+Rebs+Asts': 18.5,
  'Rebs+Asts': 6.5,
  'Steals': 0.5,
  'Pts+Asts': 14.5,
  'Points': 11.5,
  'Turnovers': 2.5},
 {'name': 'Dillon Bailey',
  'opponent': 'TENN',
  'Pts+Asts': 8.5,
  'Rebounds': 2.5,
  'Steals': 0.5,
  'Points': 7.5,
  'Rebs+Asts': 3.5,
  'Pts+Rebs+Asts': 11.5,
  'Pts+Rebs': 10.5},
 {'name': 'Jackson Sivills',
  'opponent': 'TENN',
  'Pts+Rebs': 11.5,
  'Pts+Rebs+Asts': 12.5,
  'Pts+Asts': 8.5,
  'Points': 7.5},
 {'name': 'Kyler Filewich',
  'opponent': 'TENN',
  'Pts+Rebs+Asts': 19.5,
  'Fantasy Score': 22.5,
  'Pts+Rebs': 16.5,
  'Points': 10.5,
  'Rebounds': 6.5},
 {'name': 'D.J. Wagner',
  'opponent': 'KU',
  'Fantasy Score': 20.5,
  'Pts+Asts': 15.5,
  'Pts+Rebs+Asts': 17.5,
  'Points': 11.5,
  'Rebs+Asts': 6,
  'Pts+Rebs': 14.5,
  'Assists': 3.5},
 {'name': 'Johnell Davis',
  'opponent': 'KU',
  'Pts+Rebs': 17.5,
  '3-PT Made': 1.5,
  'Assists': 1.5,
  'Points': 13.5,
  'Steals': 1.5,
  'Pts+Rebs+Asts': 18.5,
  'Pts+Asts': 15.5},
 {'name': 'Trevon Brazile',
  'opponent': 'KU',
  'Fantasy Score': 24.5,
  'Points': 10,
  'Pts+Rebs+Asts': 19.5,
  'Rebounds': 8.5,
  'Rebs+Asts': 9.5,
  'Pts+Rebs': 18.5},
 {'name': 'Dajuan Harris Jr.',
  'opponent': 'ARK',
  'Fantasy Score': 22.5,
  'Points': 8.5,
  'Pts+Rebs+Asts': 17.5,
  'Rebs+Asts': 9,
  'Pts+Asts': 13.5,
  'Assists': 5.5,
  'Rebounds': 3.5,
  'Pts+Rebs': 12.5},
 {'name': 'Hunter Dickinson',
  'opponent': 'ARK',
  'Pts+Asts': 21.5,
  'Assists': 1.5,
  'Points': 19.5,
  'Rebs+Asts': 11.5,
  '3-PT Made': 0.5,
  'Fantasy Score': 36.5,
  'Pts+Rebs+Asts': 31.5,
  'Pts+Rebs': 30},
 {'name': 'KJ Adams Jr.',
  'opponent': 'ARK',
  'Blocked Shots': 0.5,
  'Rebs+Asts': 8.5,
  'Points': 9.5,
  'Pts+Rebs+Asts': 18.5,
  'Pts+Rebs': 16.5},
 {'name': 'Zeke Mayo',
  'opponent': 'ARK',
  'Rebounds': 5.5,
  'Pts+Asts': 16.5,
  'Points': 14.5,
  'Pts+Rebs+Asts': 22.5,
  'Rebs+Asts': 8,
  'Pts+Rebs': 19.5,
  'Fantasy Score': 25.5,
  'Assists': 2.5},
 {'name': 'Pharrel Payne',
  'opponent': 'YALE',
  'Pts+Rebs+Asts': 13.5,
  'Points': 8.5,
  'Pts+Rebs': 13},
 {'name': 'Andersson Garcia',
  'opponent': 'YALE',
  'Rebs+Asts': 9,
  'Pts+Rebs+Asts': 16.5,
  'Pts+Rebs': 15,
  'Points': 7.5,
  'Rebounds': 7},
 {'name': 'Wade Taylor IV',
  'opponent': 'YALE',
  'Fantasy Score': 27.5,
  'Pts+Rebs+Asts': 25,
  'Pts+Asts': 21,
  'Points': 16.5,
  'Rebounds': 3.5,
  'Rebs+Asts': 8,
  'Pts+Rebs': 20.5},
 {'name': 'Henry Coleman III',
  'opponent': 'YALE',
  'Rebounds': 6.5,
  'Pts+Asts': 7.5,
  'Points': 7.5,
  'Pts+Rebs+Asts': 14.5,
  'Rebs+Asts': 6.5},
 {'name': 'Zhuric Phelps',
  'opponent': 'YALE',
  'Fantasy Score': 22.5,
  'Pts+Asts': 15,
  'Points': 13,
  'Pts+Rebs+Asts': 19,
  'Pts+Rebs': 17},
 {'name': 'Bez Mbeng',
  'opponent': 'TXAM',
  'Fantasy Score': 30.5,
  'Pts+Asts': 18.5,
  'Rebs+Asts': 11.5,
  'Assists': 5,
  'Points': 13,
  'Rebounds': 6,
  'Pts+Rebs': 19,
  'Pts+Rebs+Asts': 24.5},
 {'name': 'Nick Townsend',
  'opponent': 'TXAM',
  'Fantasy Score': 29.5,
  'Pts+Asts': 17,
  'Assists': 3.5,
  'Rebounds': 6,
  'Pts+Rebs+Asts': 23,
  'Pts+Rebs': 19.5,
  'Points': 13,
  'Rebs+Asts': 10},
 {'name': 'Casey Simmons',
  'opponent': 'TXAM',
  'Pts+Rebs+Asts': 13,
  'Points': 8,
  'Blocked Shots': 0.5},
 {'name': 'John Poulakidas',
  'opponent': 'TXAM',
  'Pts+Rebs+Asts': 22,
  'Pts+Asts': 18.5,
  'Pts+Rebs': 20,
  'Points': 17},
 {'name': 'Bennett Stirtz',
  'opponent': 'MIZZ',
  'Points': 17.5,
  'Rebounds': 4.5,
  'Fantasy Score': 33.5,
  'Pts+Asts': 22.5,
  'Turnovers': 2.5,
  'Pts+Rebs': 22,
  'Rebs+Asts': 9.5,
  'Pts+Rebs+Asts': 27},
 {'name': 'Daniel Abreu',
  'opponent': 'MIZZ',
  'Points': 7.5,
  'Pts+Rebs+Asts': 11.5,
  'Rebounds': 3.5,
  'Turnovers': 1.5,
  'Pts+Asts': 8.5},
 {'name': 'Mitch Mascari',
  'opponent': 'MIZZ',
  'Pts+Rebs': 10,
  'Pts+Rebs+Asts': 11,
  'Pts+Asts': 8.5,
  '3-PT Made': 1.5,
  'Points': 7.5},
 {'name': 'Tavion Banks',
  'opponent': 'MIZZ',
  'Rebounds': 6,
  'Points': 11.5,
  'Pts+Rebs+Asts': 18.5,
  'Rebs+Asts': 7,
  'Fantasy Score': 24.5,
  'Pts+Asts': 12.5,
  'Pts+Rebs': 17.5},
 {'name': 'Caleb Grill',
  'opponent': 'DRKE',
  'Pts+Rebs': 16,
  'Pts+Rebs+Asts': 17,
  'Rebs+Asts': 4.5,
  'Points': 12.5,
  'Pts+Asts': 13.5,
  'Fantasy Score': 21.5},
 {'name': 'Mark Mitchell',
  'opponent': 'DRKE',
  'Pts+Asts': 15.5,
  'Points': 13.5,
  'Pts+Rebs+Asts': 19.5,
  'Steals': 0.5,
  'Rebs+Asts': 6,
  'Fantasy Score': 22.5,
  'Pts+Rebs': 17.5},
 {'name': 'Tamar Bates',
  'opponent': 'DRKE',
  'Pts+Rebs+Asts': 15,
  'Steals': 0.5,
  'Pts+Rebs': 14.5,
  'Points': 12,
  'Turnovers': 1.5},
 {'name': 'Tony Perkins',
  'opponent': 'DRKE',
  'Turnovers': 1.5,
  'Pts+Rebs+Asts': 13.5,
  'Rebs+Asts': 5.5,
  'Pts+Asts': 10.5,
  'Points': 8,
  'Assists': 2.5,
  'Pts+Rebs': 11},
 {'name': 'Anthony Robinson',
  'opponent': 'DRKE',
  'Pts+Rebs+Asts': 11.5,
  'Turnovers': 1.5,
  'Assists': 2.5,
  'Pts+Rebs': 8.5},
 {'name': 'Dylan Andrews',
  'opponent': 'USU',
  'Pts+Rebs+Asts': 12.5,
  'Pts+Asts': 10.5,
  'Pts+Rebs': 9.5,
  'Assists': 3.5,
  'Points': 7.5},
 {'name': 'Kobe Johnson',
  'opponent': 'USU',
  'Fantasy Score': 21.5,
  'Rebounds': 6,
  'Pts+Asts': 10.5,
  'Assists': 2.5,
  'Rebs+Asts': 9,
  'Points': 8,
  'Pts+Rebs+Asts': 17,
  'Pts+Rebs': 14.5},
 {'name': 'Tyler Bilodeau',
  'opponent': 'USU',
  'Fantasy Score': 22.5,
  'Pts+Rebs+Asts': 19.5,
  'Rebounds': 4.5,
  'Rebs+Asts': 6,
  'Points': 13.5,
  'Pts+Rebs': 18.5,

In [22]:
more_mlb_props = ['Correct Score', 'Most Regular Season Strikeouts',
       'Most Regular Season Hits', 'Most Regular Season Runs', 'Award Winner',
       'Most Regular Season Saves', 'Most Regular Season Home Runs',
       'Pitcher Most Regular Season Wins', 'Most Regular Season Stolen Bases',
       'To Make the Playoffs', 'Division Winner', 'League Winner', 'Winner',
       'Race To 10 Regular Season Wins',
       'Freddie Freeman - 1st Plate Appearance - Exact Result',
       'Shohei Ohtani - 1st Plate Appearance - Exact Result',
       'Seiya Suzuki - 1st Plate Appearance - Exact Result',
       'Kyle Tucker - 1st Plate Appearance - Exact Result',
       'Ian Happ - 1st Plate Appearance - Exact Result',
       'Tommy Edman - 1st Plate Appearance - Exact Result',
       'Run Line - 1st 5 Innings',
       'Both Teams to Score X+ Runs - 1st 5 Innings',
       'Total Runs - 1st 5 Innings', 'Runs - 6th Inning',
       'Runs - 5th Inning', 'Runs - 1st Inning', 'Runs - 4th Inning',
       'Runs - 9th Inning', 'Runs - 7th Inning', 'Runs - 8th Inning',
       'Runs - 3rd Inning', 'Runs - 2nd Inning', 'Race to 3 Runs',
       'Race to 5 Runs', 'Race to 6 Runs', 'Race to 7 Runs', 'Race to 4 Runs']

In [23]:
PROP_LABEL_STRING = "prop_label"
PARTICIPANT_LABEL_STRING = "participant"
CBB_DK_CSV = "draftkings_cbb.csv"


dk_lines = pd.read_csv(CBB_DK_CSV, encoding='latin-1')
# print(dk_lines['category'].value_counts())
# # list the items that appear multiple times
# print(dk_lines[PROP_LABEL_STRING].value_counts()[dk_lines[PROP_LABEL_STRING].value_counts() > 2].keys())
game_props = ["Game Lines", "Team Props", "Halves", "Game Props", "Total", "Innings", "Total Runs - 1st 5 Innings", "Quick Hits", "Game Leaders", "Game Lines", "Total", "Most Points", "Moneyline", "Halves", "Total 1st Half", "Moneyline 1st Half", "Quarters", "Total 1st Quarter", "Moneyline 1st Quarter", "Q1 Player Props"]
# game_props = game_props + more_mlb_props



player_lines = dk_lines[~dk_lines[PROP_LABEL_STRING].isin(game_props)]
player_lines = player_lines[~player_lines[PARTICIPANT_LABEL_STRING].isin(game_props)]
print(player_lines["category"].value_counts())


player_lines

category
Game Props         16429
Halves              7724
Team Props          5169
Game Lines          4227
Player Points       1843
Player Rebounds     1675
Player Assists       836
Player Threes        722
Team Futures         586
Madness Props        130
Buzzer Beaters         5
Awards                 2
Name: count, dtype: int64

C:\Users\Aaron\AppData\Local\Temp\ipykernel_14768\2701158829.py:6: DtypeWarning: Columns (2,4,6) have mixed types. Specify dtype option on import or set low_memory=False.
  dk_lines = pd.read_csv(CBB_DK_CSV, encoding='latin-1')

,providerOutcomeId,providerId,providerOfferId,label,oddsAmerican,oddsDecimal,oddsDecimalDisplay,oddsFractional,line,participant,participantType,main,sortOrder,tags,participants,category,subcategory,prop_label
0,0HC79092702P250_3,2,2_79092702,Mount Saint Marys,-112,1.892857,1.89,25/28,2.5,Mount Saint Marys,Team,True,2499,"['ProgressiveParlayTeamEligible', 'MainPointLi...","[{'id': '42025', 'name': 'Mount Saint Marys', ...",Game Lines,Game,Spread
1,0HC79092702N250_1,2,2_79092702,American,-108,1.925926,1.92,25/27,-2.5,American,Team,True,2501,"['ProgressiveParlayTeamEligible', 'MainPointLi...","[{'id': '41874', 'name': 'American', 'type': '...",Game Lines,Game,Spread
6,0HC79100363P750_3,2,2_79100363,Samford,-115,1.869565,1.86,20/23,7.5,Samford,Team,True,7499,"['ProgressiveParlayTeamEligible', 'MainPointLi...","[{'id': '42759', 'name': 'Samford', 'type': 'T...",Game Lines,Game,Spread
7,0HC79100363N750_1,2,2_79100363,George Mason,-105,1.952381,1.95,20/21,-7.5,George Mason,Team,True,7501,"['ProgressiveParlayTeamEligible', 'MainPointLi...","[{'id': '41752', 'name': 'George Mason', 'type...",Game Lines,Game,Spread
12,0HC79100365P550_3,2,2_79100365,UAB,-115,1.869565,1.86,20/23,5.5,UAB,Team,True,5499,"['ProgressiveParlayTeamEligible', 'MainPointLi...","[{'id': '42938', 'name': 'UAB', 'type': 'Team'}]",Game Lines,Game,Spread
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39623,0QA239000926#187428053_13L92483Q1423432Q2-1,2,239000926,Under 5.5,-160,1.625000,1.62,5/8,None Specified,Under 5.5,Unknown,None Specified,1002,None Specified,"[{'name': 'Under 5.5', 'type': 'Team'}]",Madness Props,Conference Wins,2025 Men's NCAA Tournament Wins by Big East Co...
39624,0QA239000213#187419190_13L92483Q1967007Q2-1,2,239000213,Over 11.5,-105,1.952381,1.95,20/21,None Specified,Over 11.5,Unknown,None Specified,1000,None Specified,"[{'name': 'Over 11.5', 'type': 'Team'}]",Madness Props,Conference Wins,2025 Men's NCAA Tournament Wins by Big Ten Con...
39625,0QA239000213#187419189_13L92483Q1967006Q2-1,2,239000213,Under 11.5,-125,1.800000,1.8,4/5,None Specified,Under 11.5,Unknown,None Specified,1002,None Specified,"[{'name': 'Under 11.5', 'type': 'Team'}]",Madness Props,Conference Wins,2025 Men's NCAA Tournament Wins by Big Ten Con...
39626,0QA238998025#187412425_13L92483Q1576336Q2-1,2,238998025,Over 20.5,-105,1.952381,1.95,20/21,None Specified,Over 20.5,Unknown,None Specified,1000,None Specified,"[{'name': 'Over 20.5', 'type': 'Team'}]",Madness Props,Conference Wins,2025 Men's NCAA Tournament Wins by SEC
39627,0QA238998025#187412424_13L92483Q1576337Q2-1,2,238998025,Under 20.5,-125,1.800000,1.8,4/5,None Specified,Under 20.5,Unknown,None Specified,1002,None Specified,"[{'name': 'Under 20.5', 'type': 'Team'}]",Madness Props,Conference Wins,2025 Men's NCAA Tournament Wins by SEC

In [24]:
print(player_lines['category'].value_counts())

player_lines = player_lines[player_lines['category'].isin(['Batter Props', 'Pitcher Props', 'Player Props', "Player Points", "Player Rebounds", "Player Assists", "Player Threes"])]
player_lines = player_lines[player_lines['participantType'] != 'Team']

print(player_lines['subcategory'].value_counts())
player_lines

category
Game Props         16429
Halves              7724
Team Props          5169
Game Lines          4227
Player Points       1843
Player Rebounds     1675
Player Assists       836
Player Threes        722
Team Futures         586
Madness Props        130
Buzzer Beaters         5
Awards                 2
Name: count, dtype: int64
subcategory
Points      1843
Rebounds    1675
Assists      836
Threes       722
Name: count, dtype: int64

,providerOutcomeId,providerId,providerOfferId,label,oddsAmerican,oddsDecimal,oddsDecimalDisplay,oddsFractional,line,participant,participantType,main,sortOrder,tags,participants,category,subcategory,prop_label
246,0QA239063082#187755609_13L92483Q1-1308371319Q20,2,239063082,6+,-1200,1.083333,1.08,1/12,None Specified,Arthur Kaluma,Unknown,None Specified,10809,['SGP'],"[{'id': '594224', 'name': 'Arthur Kaluma', 'ty...",Player Points,Points,Arthur Kaluma Points
247,0QA239063082#187755610_13L92483Q1-2112887333Q20,2,239063082,8+,-450,1.222222,1.22,2/9,None Specified,Arthur Kaluma,Unknown,None Specified,12210,['SGP'],"[{'id': '594224', 'name': 'Arthur Kaluma', 'ty...",Player Points,Points,Arthur Kaluma Points
248,0QA239063082#187755611_13L92483Q11443424587Q20,2,239063082,10+,-205,1.487805,1.48,20/41,None Specified,Arthur Kaluma,Unknown,None Specified,14811,['SGP'],"[{'id': '594224', 'name': 'Arthur Kaluma', 'ty...",Player Points,Points,Arthur Kaluma Points
249,0QA239063082#187755612_13L92483Q1-1107258587Q20,2,239063082,12+,-105,1.952381,1.95,20/21,None Specified,Arthur Kaluma,Unknown,True,19512,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '594224', 'name': 'Arthur Kaluma', 'ty...",Player Points,Points,Arthur Kaluma Points
250,0QA239063082#187755614_13L92483Q1-1154980963Q20,2,239063082,15+,+240,3.400000,3.40,12/5,None Specified,Arthur Kaluma,Unknown,None Specified,34014,['SGP'],"[{'id': '594224', 'name': 'Arthur Kaluma', 'ty...",Player Points,Points,Arthur Kaluma Points
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5317,0QA239077501#187807551_13L92483Q11515351197Q20,2,239077501,3+,-175,1.571429,1.57,4/7,None Specified,TJ Bamba,Unknown,None Specified,15751,"['SGP', 'MostBalancedGlobalProbability']","[{'id': '520739', 'name': 'TJ Bamba', 'type': ...",Player Assists,Assists,TJ Bamba Assists
5318,0QA239077501#187807552_13L92483Q1-2087120971Q20,2,239077501,4+,+145,2.450000,2.45,29/20,None Specified,TJ Bamba,Unknown,True,24552,"['MostBalancedOdds', 'SGP']","[{'id': '520739', 'name': 'TJ Bamba', 'type': ...",Player Assists,Assists,TJ Bamba Assists
5319,0QA239077501#187807553_13L92483Q1-1920183765Q20,2,239077501,5+,+340,4.400000,4.40,17/5,None Specified,TJ Bamba,Unknown,None Specified,44053,['SGP'],"[{'id': '520739', 'name': 'TJ Bamba', 'type': ...",Player Assists,Assists,TJ Bamba Assists
5320,0QA239077501#187807554_13L92483Q11842436961Q20,2,239077501,6+,+800,9.000000,9.00,8/1,None Specified,TJ Bamba,Unknown,None Specified,90054,['SGP'],"[{'id': '520739', 'name': 'TJ Bamba', 'type': ...",Player Assists,Assists,TJ Bamba Assists
5321,0QA239077501#187807555_13L92483Q1-320102477Q20,2,239077501,7+,+1800,19.000000,19.00,18/1,None Specified,TJ Bamba,Unknown,None Specified,190055,['SGP'],"[{'id': '520739', 'name': 'TJ Bamba', 'type': ...",Player Assists,Assists,TJ Bamba Assists

In [25]:
def get_stat_tracked(player_line):
    return player_line[PROP_LABEL_STRING].replace(player_line[PARTICIPANT_LABEL_STRING], '').replace("O/U", '').strip().lower()

# choose the value closest to a 50/50 split
# TODO: unders
def decide_to_skip(new_val, old_val):
    new_val_odds = 1 / float(new_val["oddsDecimal"])
    old_val_odds = 1 / float(old_val[new_val['stat_tracked'] + '_' + "Over"])

    new_val_diff = abs(new_val_odds - 0.5)
    old_val_diff = abs(old_val_odds - 0.5)

    return new_val_diff > old_val_diff

In [26]:
final_dk_db = {} #dic so we can combine lines for each player

for index, row in player_lines.iterrows():
    row['stat_tracked'] = get_stat_tracked(row)
    if row[PARTICIPANT_LABEL_STRING] not in final_dk_db:
        final_dk_db[row[PARTICIPANT_LABEL_STRING]] = {
            'name': row[PARTICIPANT_LABEL_STRING]
        }
    

    #TODO: integrate
    value = row['label'].replace("+", '').replace("-", '')
    if not value.isdigit():
        if not row['line'] or not row['line'].replace('.', '', 1).isdigit():
            continue
        over_or_under = "Over" if "Over" in row['label'] else "Under"
        final_dk_db[row[PARTICIPANT_LABEL_STRING]][row['stat_tracked']] = float(row['line'])
        final_dk_db[row[PARTICIPANT_LABEL_STRING]][row['stat_tracked'] + '_' + over_or_under] = row['oddsDecimal']
    else:
        if row['stat_tracked'] in final_dk_db[row[PARTICIPANT_LABEL_STRING]]:
            if (decide_to_skip(row, final_dk_db[row[PARTICIPANT_LABEL_STRING]])):
                continue
        value = float(value)
        over_or_under = "Over" if "+" in row['label'] else "Under"
        value = float(row['label'].replace("+", '').replace("-", ''))
        final_dk_db[row[PARTICIPANT_LABEL_STRING]][row['stat_tracked']] = value - 0.5 if over_or_under == "Over" else value + 0.5
        final_dk_db[row[PARTICIPANT_LABEL_STRING]][row['stat_tracked'] + '_' + over_or_under] = row['oddsDecimal']


final_dk_db = pd.DataFrame(final_dk_db).T
final_dk_db

,name,points,points_Over,three pointers made,three pointers made_Over,rebounds,rebounds_Over,assists,assists_Over
Arthur Kaluma,Arthur Kaluma,11.5,1.952381,0.5,1.869565,6.5,1.869565,1.5,1.869565
Dailyn Swain,Dailyn Swain,11.5,1.740741,NaN,NaN,6.5,2.15,2.5,1.8
Dayvion McKnight,Dayvion McKnight,9.5,2.05,1.5,9.5,3.5,2.55,3.5,2.0
Jordan Pope,Jordan Pope,10.5,2.0,1.5,2.3,3.5,2.45,1.5,1.645161
Kadin Shedrick,Kadin Shedrick,9.5,2.15,NaN,NaN,5.5,1.769231,NaN,NaN
...,...,...,...,...,...,...,...,...,...
Sean Moore,Sean Moore,NaN,NaN,NaN,NaN,6.5,2.0,NaN,NaN
Chris Manon,Chris Manon,NaN,NaN,NaN,NaN,3.5,1.769231,NaN,NaN
Jaylen Carey,Jaylen Carey,NaN,NaN,NaN,NaN,4.5,1.869565,NaN,NaN
Jalen Myers,Jalen Myers,NaN,NaN,NaN,NaN,4.5,1.833333,NaN,NaN
Carson Cooper,Carson Cooper,NaN,NaN,NaN,NaN,6.5,2.2,NaN,NaN

In [27]:
final_dk_db.keys()

Index(['name', 'points', 'points_Over', 'three pointers made',
       'three pointers made_Over', 'rebounds', 'rebounds_Over', 'assists',
       'assists_Over'],
      dtype='object')

In [28]:
prizepicks = pd.read_csv("pp_lines.csv")

merged = pd.merge(prizepicks, final_dk_db, on='name')
#get a list of all the column names
cols = merged.columns.tolist()
merged.keys()

Index(['name', 'opponent', 'Points', 'Fantasy Score', 'Pts+Rebs+Asts',
       'Pts+Rebs', 'Pts+Asts', 'Rebs+Asts', 'Turnovers', 'Steals', 'Assists',
       'Rebounds', '3-PT Made', 'Blocked Shots', 'points', 'points_Over',
       'three pointers made', 'three pointers made_Over', 'rebounds',
       'rebounds_Over', 'assists', 'assists_Over'],
      dtype='object')

In [29]:
results = []

for index, row in merged.iterrows():
    # Access the values of each column in the current row
    name = row['name']

    for pp_stat_type in PP_TO_DK_STATS.keys():
        # failsafe 
        if pp_stat_type not in row:
            continue

        if float(row[pp_stat_type]) <= 0:
            continue

        if PP_TO_DK_STATS[pp_stat_type] not in row:
            continue
    
        if float(row[PP_TO_DK_STATS[pp_stat_type]]) <= 0:
            continue

        print("Passed all tests", pp_stat_type, name)

        # Create a dictionary to store the result
        result_dict = {
            'name': name,
            'stat': pp_stat_type,
            'line': row[pp_stat_type],
            'dk_line': float(row[PP_TO_DK_STATS[pp_stat_type]]),
            'dk_over_line': row[PP_TO_DK_STATS[pp_stat_type] + '_Over'],
            'dk_under_line': row[PP_TO_DK_STATS[pp_stat_type] + '_Under'] if PP_TO_DK_STATS[pp_stat_type] + '_Under' in row else 100,
        }

        # Get the dk stat type that corresponds to the current PP stat type
        dk_stat_type = PP_TO_DK_STATS[pp_stat_type]

        # Get the value of the FBref stat type for the current player
        dk_stat_value = row[dk_stat_type]



        # Append the dictionary to the results list
        results.append(result_dict)

results_df = pd.DataFrame(results)
print(results_df.head())


results_df = results_df.dropna()
# results_df = results_df.dropna() 
# # get data types for each column 
results_df

Passed all tests Rebounds Dailyn Swain
Passed all tests Points Dailyn Swain
Passed all tests Assists Dailyn Swain
Passed all tests 3-PT Made Dailyn Swain
Passed all tests Rebounds Dayvion McKnight
Passed all tests Points Dayvion McKnight
Passed all tests Assists Dayvion McKnight
Passed all tests 3-PT Made Dayvion McKnight
Passed all tests Rebounds Marcus Foster
Passed all tests Points Marcus Foster
Passed all tests Assists Marcus Foster
Passed all tests 3-PT Made Marcus Foster
Passed all tests Rebounds Ryan Conwell
Passed all tests Points Ryan Conwell
Passed all tests Assists Ryan Conwell
Passed all tests 3-PT Made Ryan Conwell
Passed all tests Rebounds Zach Freemantle
Passed all tests Points Zach Freemantle
Passed all tests Assists Zach Freemantle
Passed all tests 3-PT Made Zach Freemantle
Passed all tests Rebounds Arthur Kaluma
Passed all tests Points Arthur Kaluma
Passed all tests Assists Arthur Kaluma
Passed all tests 3-PT Made Arthur Kaluma
Passed all tests Rebounds Tre Johnson
Passed all tests Points Tre Johnson
Passed all tests Assists Tre Johnson
Passed all tests 3-PT Made Tre Johnson
Passed all tests Rebounds Jordan Pope
Passed all tests Points Jordan Pope
Passed all tests Assists Jordan Pope
Passed all tests 3-PT Made Jordan Pope
Passed all tests Rebounds Kadin Shedrick
Passed all tests Points Kadin Shedrick
Passed all tests Assists Kadin Shedrick
Passed all tests 3-PT Made Kadin Shedrick
Passed all tests Rebounds Tramon Mark
Passed all tests Points Tramon Mark
Passed all tests Assists Tramon Mark
Passed all tests 3-PT Made Tramon Mark
Passed all tests Rebounds Jackson McAndrew
Passed all tests Points Jackson McAndrew
Passed all tests Assists Jackson McAndrew
Passed all tests 3-PT Made Jackson McAndrew
Passed all tests Rebounds Jamiya Neal
Passed all tests Points Jamiya Neal
Passed all tests Assists Jamiya Neal
Passed all tests 3-PT Made Jamiya Neal
Passed all tests Rebounds Jasen Green
Passed all tests Points Jasen Green
Passed all tests Assists Jasen Green
Passed all tests 3-PT Made Jasen Green
Passed all tests Rebounds Ryan Kalkbrenner
Passed all tests Points Ryan Kalkbrenner
Passed all tests Assists Ryan Kalkbrenner
Passed all tests 3-PT Made Ryan Kalkbrenner
Passed all tests Rebounds Steven Ashworth
Passed all tests Points Steven Ashworth
Passed all tests Assists Steven Ashworth
Passed all tests 3-PT Made Steven Ashworth
Passed all tests Rebounds Chucky Hepburn
Passed all tests Points Chucky Hepburn
Passed all tests Assists Chucky Hepburn
Passed all tests 3-PT Made Chucky Hepburn
Passed all tests Rebounds J'Vonne Hadley
Passed all tests Points J'Vonne Hadley
Passed all tests Assists J'Vonne Hadley
Passed all tests 3-PT Made J'Vonne Hadley
Passed all tests Rebounds Reyne Smith
Passed all tests Points Reyne Smith
Passed all tests Assists Reyne Smith
Passed all tests 3-PT Made Reyne Smith
Passed all tests Rebounds Kezza Giffa
Passed all tests Points Kezza Giffa
Passed all tests Assists Kezza Giffa
Passed all tests 3-PT Made Kezza Giffa
Passed all tests Rebounds Kimani Hamilton
Passed all tests Points Kimani Hamilton
Passed all tests Assists Kimani Hamilton
Passed all tests 3-PT Made Kimani Hamilton
Passed all tests Rebounds Braden Smith
Passed all tests Points Braden Smith
Passed all tests Assists Braden Smith
Passed all tests 3-PT Made Braden Smith
Passed all tests Rebounds Trey Kaufman-Renn
Passed all tests Points Trey Kaufman-Renn
Passed all tests Assists Trey Kaufman-Renn
Passed all tests 3-PT Made Trey Kaufman-Renn
Passed all tests Rebounds C.J. Cox
Passed all tests Points C.J. Cox
Passed all tests Assists C.J. Cox
Passed all tests 3-PT Made C.J. Cox
Passed all tests Rebounds Fletcher Loyer
Passed all tests Points Fletcher Loyer
Passed all tests Assists Fletcher Loyer
Passed all tests 3-PT Made Fletcher Loyer
Passed all tests Rebounds Myles Colvin
Passed all tests Points Myles Colvin
Passed all tests Assists Myles Colvin
Passed all tests 3-PT Made Myles Colvin
Passed all tests Rebounds Caleb Furst
Passed all tests Points Caleb Furst
Passed all tests Assists Caleb Furst
Passed all tests 3-PT Made Caleb Furst
Passed all tests Rebounds Money Williams
Passed all tests Points Money Williams
Passed all tests Assists Money Williams
Passed all tests 3-PT Made Money Williams
Passed all tests Rebounds Brandon Whitney
Passed all tests Points Brandon Whitney
Passed all tests Assists Brandon Whitney
Passed all tests 3-PT Made Brandon Whitney
Passed all tests Rebounds John Tonje
Passed all tests Points John Tonje
Passed all tests Assists John Tonje
Passed all tests 3-PT Made John Tonje
Passed all tests Rebounds Joe Pridgen
Passed all tests Points Joe Pridgen
Passed all tests Assists Joe Pridgen
Passed all tests 3-PT Made Joe Pridgen
Passed all tests Rebounds John Blackwell
Passed all tests Points John Blackwell
Passed all tests Assists John Blackwell
Passed all tests 3-PT Made John Blackwell
Passed all tests Rebounds Kai Johnson
Passed all tests Points Kai Johnson
Passed all tests Assists Kai Johnson
Passed all tests 3-PT Made Kai Johnson
Passed all tests Rebounds Malik Moore
Passed all tests Points Malik Moore
Passed all tests Assists Malik Moore
Passed all tests 3-PT Made Malik Moore
Passed all tests Rebounds Te'Jon Sawyer
Passed all tests Points Te'Jon Sawyer
Passed all tests Assists Te'Jon Sawyer
Passed all tests 3-PT Made Te'Jon Sawyer
Passed all tests Rebounds Kamari McGee
Passed all tests Points Kamari McGee
Passed all tests Assists Kamari McGee
Passed all tests 3-PT Made Kamari McGee
Passed all tests Rebounds Max Klesmit
Passed all tests Points Max Klesmit
Passed all tests Assists Max Klesmit
Passed all tests 3-PT Made Max Klesmit
Passed all tests Rebounds Nolan Winter
Passed all tests Points Nolan Winter
Passed all tests Assists Nolan Winter
Passed all tests 3-PT Made Nolan Winter
Passed all tests Rebounds Steven Crowl
Passed all tests Points Steven Crowl
Passed all tests Assists Steven Crowl
Passed all tests 3-PT Made Steven Crowl
Passed all tests Rebounds Carter Gilmore
Passed all tests Points Carter Gilmore
Passed all tests Assists Carter Gilmore
Passed all tests 3-PT Made Carter Gilmore
Passed all tests Rebounds Emanuel Sharp
Passed all tests Points Emanuel Sharp
Passed all tests Assists Emanuel Sharp
Passed all tests 3-PT Made Emanuel Sharp
Passed all tests Rebounds Milos Uzan
Passed all tests Points Milos Uzan
Passed all tests Assists Milos Uzan
Passed all tests 3-PT Made Milos Uzan
Passed all tests Rebounds Ray'Sean Taylor
Passed all tests Points Ray'Sean Taylor
Passed all tests Assists Ray'Sean Taylor
Passed all tests 3-PT Made Ray'Sean Taylor
Passed all tests Rebounds Ring Malith
Passed all tests Points Ring Malith
Passed all tests Assists Ring Malith
Passed all tests 3-PT Made Ring Malith
Passed all tests Rebounds Chase Hunter
Passed all tests Points Chase Hunter
Passed all tests Assists Chase Hunter
Passed all tests 3-PT Made Chase Hunter
Passed all tests Rebounds Ian Schieffelin
Passed all tests Points Ian Schieffelin
Passed all tests Assists Ian Schieffelin
Passed all tests 3-PT Made Ian Schieffelin
Passed all tests Rebounds Jaeden Zackery
Passed all tests Points Jaeden Zackery
Passed all tests Assists Jaeden Zackery
Passed all tests 3-PT Made Jaeden Zackery
Passed all tests Rebounds Viktor Lakhin
Passed all tests Points Viktor Lakhin
Passed all tests Assists Viktor Lakhin
Passed all tests 3-PT Made Viktor Lakhin
Passed all tests Rebounds Christian Shumate
Passed all tests Points Christian Shumate
Passed all tests Assists Christian Shumate
Passed all tests 3-PT Made Christian Shumate
Passed all tests Rebounds Javohn Garcia
Passed all tests Points Javohn Garcia
Passed all tests Assists Javohn Garcia
Passed all tests 3-PT Made Javohn Garcia
Passed all tests Rebounds Quadir Copeland
Passed all tests Points Quadir Copeland
Passed all tests Assists Quadir Copeland
Passed all tests 3-PT Made Quadir Copeland
Passed all tests Rebounds Sincere Parker
Passed all tests Points Sincere Parker
Passed all tests Assists Sincere Parker
Passed all tests 3-PT Made Sincere Parker
Passed all tests Rebounds Egor Demin
Passed all tests Points Egor Demin
Passed all tests Assists Egor Demin
Passed all tests 3-PT Made Egor Demin
Passed all tests Rebounds Richie Saunders
Passed all tests Points Richie Saunders
Passed all tests Assists Richie Saunders
Passed all tests 3-PT Made Richie Saunders
Passed all tests Rebounds Jack Clark
Passed all tests Points Jack Clark
Passed all tests Assists Jack Clark
Passed all tests 3-PT Made Jack Clark
Passed all tests Rebounds Max Shulga
Passed all tests Points Max Shulga
Passed all tests Assists Max Shulga
Passed all tests 3-PT Made Max Shulga
Passed all tests Rebounds Luke Bamgboye
Passed all tests Points Luke Bamgboye
Passed all tests Assists Luke Bamgboye
Passed all tests 3-PT Made Luke Bamgboye
Passed all tests Rebounds Dallin Hall
Passed all tests Points Dallin Hall
Passed all tests Assists Dallin Hall
Passed all tests 3-PT Made Dallin Hall
Passed all tests Rebounds Keba Keita
Passed all tests Points Keba Keita
Passed all tests Assists Keba Keita
Passed all tests 3-PT Made Keba Keita
Passed all tests Rebounds Mawot Mag
Passed all tests Points Mawot Mag
Passed all tests Assists Mawot Mag
Passed all tests 3-PT Made Mawot Mag
Passed all tests Rebounds Phillip Russell
Passed all tests Points Phillip Russell
Passed all tests Assists Phillip Russell
Passed all tests 3-PT Made Phillip Russell
Passed all tests Rebounds Zeb Jackson
Passed all tests Points Zeb Jackson
Passed all tests Assists Zeb Jackson
Passed all tests 3-PT Made Zeb Jackson
Passed all tests Rebounds Graham Ike
Passed all tests Points Graham Ike
Passed all tests Assists Graham Ike
Passed all tests 3-PT Made Graham Ike
Passed all tests Rebounds Ryan Nembhard
Passed all tests Points Ryan Nembhard
Passed all tests Assists Ryan Nembhard
Passed all tests 3-PT Made Ryan Nembhard
Passed all tests Rebounds Khalif Battle
Passed all tests Points Khalif Battle
Passed all tests Assists Khalif Battle
Passed all tests 3-PT Made Khalif Battle
Passed all tests Rebounds Nolan Hickman
Passed all tests Points Nolan Hickman
Passed all tests Assists Nolan Hickman
Passed all tests 3-PT Made Nolan Hickman
Passed all tests Rebounds Asa Newell
Passed all tests Points Asa Newell
Passed all tests Assists Asa Newell
Passed all tests 3-PT Made Asa Newell
Passed all tests Rebounds Blue Cain
Passed all tests Points Blue Cain
Passed all tests Assists Blue Cain
Passed all tests 3-PT Made Blue Cain
Passed all tests Rebounds Silas Demary Jr.
Passed all tests Points Silas Demary Jr.
Passed all tests Assists Silas Demary Jr.
Passed all tests 3-PT Made Silas Demary Jr.
Passed all tests Rebounds Tyrin Lawrence
Passed all tests Points Tyrin Lawrence
Passed all tests Assists Tyrin Lawrence
Passed all tests 3-PT Made Tyrin Lawrence
Passed all tests Rebounds Chaz Lanier
Passed all tests Points Chaz Lanier
Passed all tests Assists Chaz Lanier
Passed all tests 3-PT Made Chaz Lanier
Passed all tests Rebounds Felix Okpara
Passed all tests Points Felix Okpara
Passed all tests Assists Felix Okpara
Passed all tests 3-PT Made Felix Okpara
Passed all tests Rebounds Jahmai Mashack
Passed all tests Points Jahmai Mashack
Passed all tests Assists Jahmai Mashack
Passed all tests 3-PT Made Jahmai Mashack
Passed all tests Rebounds Jordan Gainey
Passed all tests Points Jordan Gainey
Passed all tests Assists Jordan Gainey
Passed all tests 3-PT Made Jordan Gainey
Passed all tests Rebounds Zakai Zeigler
Passed all tests Points Zakai Zeigler
Passed all tests Assists Zakai Zeigler
Passed all tests 3-PT Made Zakai Zeigler
Passed all tests Rebounds Corey Tripp
Passed all tests Points Corey Tripp
Passed all tests Assists Corey Tripp
Passed all tests 3-PT Made Corey Tripp
Passed all tests Rebounds Dillon Bailey
Passed all tests Points Dillon Bailey
Passed all tests Assists Dillon Bailey
Passed all tests 3-PT Made Dillon Bailey
Passed all tests Rebounds Jackson Sivills
Passed all tests Points Jackson Sivills
Passed all tests Assists Jackson Sivills
Passed all tests 3-PT Made Jackson Sivills
Passed all tests Rebounds Kyler Filewich
Passed all tests Points Kyler Filewich
Passed all tests Assists Kyler Filewich
Passed all tests 3-PT Made Kyler Filewich
Passed all tests Rebounds D.J. Wagner
Passed all tests Points D.J. Wagner
Passed all tests Assists D.J. Wagner
Passed all tests 3-PT Made D.J. Wagner
Passed all tests Rebounds Johnell Davis
Passed all tests Points Johnell Davis
Passed all tests Assists Johnell Davis
Passed all tests 3-PT Made Johnell Davis
Passed all tests Rebounds Trevon Brazile
Passed all tests Points Trevon Brazile
Passed all tests Assists Trevon Brazile
Passed all tests 3-PT Made Trevon Brazile
Passed all tests Rebounds Dajuan Harris Jr.
Passed all tests Points Dajuan Harris Jr.
Passed all tests Assists Dajuan Harris Jr.
Passed all tests 3-PT Made Dajuan Harris Jr.
Passed all tests Rebounds Hunter Dickinson
Passed all tests Points Hunter Dickinson
Passed all tests Assists Hunter Dickinson
Passed all tests 3-PT Made Hunter Dickinson
Passed all tests Rebounds KJ Adams Jr.
Passed all tests Points KJ Adams Jr.
Passed all tests Assists KJ Adams Jr.
Passed all tests 3-PT Made KJ Adams Jr.
Passed all tests Rebounds Zeke Mayo
Passed all tests Points Zeke Mayo
Passed all tests Assists Zeke Mayo
Passed all tests 3-PT Made Zeke Mayo
Passed all tests Rebounds Pharrel Payne
Passed all tests Points Pharrel Payne
Passed all tests Assists Pharrel Payne
Passed all tests 3-PT Made Pharrel Payne
Passed all tests Rebounds Andersson Garcia
Passed all tests Points Andersson Garcia
Passed all tests Assists Andersson Garcia
Passed all tests 3-PT Made Andersson Garcia
Passed all tests Rebounds Wade Taylor IV
Passed all tests Points Wade Taylor IV
Passed all tests Assists Wade Taylor IV
Passed all tests 3-PT Made Wade Taylor IV
Passed all tests Rebounds Henry Coleman III
Passed all tests Points Henry Coleman III
Passed all tests Assists Henry Coleman III
Passed all tests 3-PT Made Henry Coleman III
Passed all tests Rebounds Zhuric Phelps
Passed all tests Points Zhuric Phelps
Passed all tests Assists Zhuric Phelps
Passed all tests 3-PT Made Zhuric Phelps
Passed all tests Rebounds Bez Mbeng
Passed all tests Points Bez Mbeng
Passed all tests Assists Bez Mbeng
Passed all tests 3-PT Made Bez Mbeng
Passed all tests Rebounds Nick Townsend
Passed all tests Points Nick Townsend
Passed all tests Assists Nick Townsend
Passed all tests 3-PT Made Nick Townsend
Passed all tests Rebounds Casey Simmons
Passed all tests Points Casey Simmons
Passed all tests Assists Casey Simmons
Passed all tests 3-PT Made Casey Simmons
Passed all tests Rebounds John Poulakidas
Passed all tests Points John Poulakidas
Passed all tests Assists John Poulakidas
Passed all tests 3-PT Made John Poulakidas
Passed all tests Rebounds Bennett Stirtz
Passed all tests Points Bennett Stirtz
Passed all tests Assists Bennett Stirtz
Passed all tests 3-PT Made Bennett Stirtz
Passed all tests Rebounds Daniel Abreu
Passed all tests Points Daniel Abreu
Passed all tests Assists Daniel Abreu
Passed all tests 3-PT Made Daniel Abreu
Passed all tests Rebounds Mitch Mascari
Passed all tests Points Mitch Mascari
Passed all tests Assists Mitch Mascari
Passed all tests 3-PT Made Mitch Mascari
Passed all tests Rebounds Tavion Banks
Passed all tests Points Tavion Banks
Passed all tests Assists Tavion Banks
Passed all tests 3-PT Made Tavion Banks
Passed all tests Rebounds Caleb Grill
Passed all tests Points Caleb Grill
Passed all tests Assists Caleb Grill
Passed all tests 3-PT Made Caleb Grill
Passed all tests Rebounds Mark Mitchell
Passed all tests Points Mark Mitchell
Passed all tests Assists Mark Mitchell
Passed all tests 3-PT Made Mark Mitchell
Passed all tests Rebounds Tamar Bates
Passed all tests Points Tamar Bates
Passed all tests Assists Tamar Bates
Passed all tests 3-PT Made Tamar Bates
Passed all tests Rebounds Tony Perkins
Passed all tests Points Tony Perkins
Passed all tests Assists Tony Perkins
Passed all tests 3-PT Made Tony Perkins
Passed all tests Rebounds Dylan Andrews
Passed all tests Points Dylan Andrews
Passed all tests Assists Dylan Andrews
Passed all tests 3-PT Made Dylan Andrews
Passed all tests Rebounds Tyler Bilodeau
Passed all tests Points Tyler Bilodeau
Passed all tests Assists Tyler Bilodeau
Passed all tests 3-PT Made Tyler Bilodeau
Passed all tests Rebounds Ian Martinez
Passed all tests Points Ian Martinez
Passed all tests Assists Ian Martinez
Passed all tests 3-PT Made Ian Martinez
Passed all tests Rebounds Sebastian Mack
Passed all tests Points Sebastian Mack
Passed all tests Assists Sebastian Mack
Passed all tests 3-PT Made Sebastian Mack
Passed all tests Rebounds Mason Falslev
Passed all tests Points Mason Falslev
Passed all tests Assists Mason Falslev
Passed all tests 3-PT Made Mason Falslev
Passed all tests Rebounds Skyy Clark
Passed all tests Points Skyy Clark
Passed all tests Assists Skyy Clark
Passed all tests 3-PT Made Skyy Clark
Passed all tests Rebounds Deyton Albury
Passed all tests Points Deyton Albury
Passed all tests Assists Deyton Albury
Passed all tests 3-PT Made Deyton Albury
Passed all tests Rebounds Kadary Richmond
Passed all tests Points Kadary Richmond
Passed all tests Assists Kadary Richmond
Passed all tests 3-PT Made Kadary Richmond
Passed all tests Rebounds Zuby Ejiofor
Passed all tests Points Zuby Ejiofor
Passed all tests Assists Zuby Ejiofor
Passed all tests 3-PT Made Zuby Ejiofor
Passed all tests Rebounds Danny Wolf
Passed all tests Points Danny Wolf
Passed all tests Assists Danny Wolf
Passed all tests 3-PT Made Danny Wolf
Passed all tests Rebounds Vladislav Goldin
Passed all tests Points Vladislav Goldin
Passed all tests Assists Vladislav Goldin
Passed all tests 3-PT Made Vladislav Goldin
Passed all tests Rebounds Nimari Burnett
Passed all tests Points Nimari Burnett
Passed all tests Assists Nimari Burnett
Passed all tests 3-PT Made Nimari Burnett
Passed all tests Rebounds Tre Donaldson
Passed all tests Points Tre Donaldson
Passed all tests Assists Tre Donaldson
Passed all tests 3-PT Made Tre Donaldson
Passed all tests Rebounds Aniwaniwa Tait-Jones
Passed all tests Points Aniwaniwa Tait-Jones
Passed all tests Assists Aniwaniwa Tait-Jones
Passed all tests 3-PT Made Aniwaniwa Tait-Jones
Passed all tests Rebounds Tyler McGhie
Passed all tests Points Tyler McGhie
Passed all tests Assists Tyler McGhie
Passed all tests 3-PT Made Tyler McGhie
Passed all tests Rebounds Hayden Gray
Passed all tests Points Hayden Gray
Passed all tests Assists Hayden Gray
Passed all tests 3-PT Made Hayden Gray
Passed all tests Rebounds Nordin Kapic
Passed all tests Points Nordin Kapic
Passed all tests Assists Nordin Kapic
Passed all tests 3-PT Made Nordin Kapic
Passed all tests Rebounds Elijah Hawkins
Passed all tests Points Elijah Hawkins
Passed all tests Assists Elijah Hawkins
Passed all tests 3-PT Made Elijah Hawkins
Passed all tests Rebounds JT Toppin
Passed all tests Points JT Toppin
Passed all tests Assists JT Toppin
Passed all tests 3-PT Made JT Toppin
Passed all tests Rebounds Bo Montgomery
Passed all tests Points Bo Montgomery
Passed all tests Assists Bo Montgomery
Passed all tests 3-PT Made Bo Montgomery
Passed all tests Rebounds Donovan Newby
Passed all tests Points Donovan Newby
Passed all tests Assists Donovan Newby
Passed all tests 3-PT Made Donovan Newby
Passed all tests Rebounds Norchad Omier
Passed all tests Points Norchad Omier
Passed all tests Assists Norchad Omier
Passed all tests 3-PT Made Norchad Omier
Passed all tests Rebounds VJ Edgecombe
Passed all tests Points VJ Edgecombe
Passed all tests Assists VJ Edgecombe
Passed all tests 3-PT Made VJ Edgecombe
Passed all tests Rebounds Josh Hubbard
Passed all tests Points Josh Hubbard
Passed all tests Assists Josh Hubbard
Passed all tests 3-PT Made Josh Hubbard
Passed all tests Rebounds KeShawn Murphy
Passed all tests Points KeShawn Murphy
Passed all tests Assists KeShawn Murphy
Passed all tests 3-PT Made KeShawn Murphy
Passed all tests Rebounds Cameron Matthews

,name,stat,line,dk_line,dk_over_line,dk_under_line
0,Dailyn Swain,Rebounds,6.0,6.5,2.150000,100
1,Dailyn Swain,Points,12.0,11.5,1.740741,100
2,Dailyn Swain,Assists,2.5,2.5,1.800000,100
5,Dayvion McKnight,Points,9.0,9.5,2.050000,100
8,Marcus Foster,Rebounds,6.0,6.5,2.300000,100
...,...,...,...,...,...,...
849,Jackson Shelstad,Points,15.0,16.5,2.000000,100
852,Keeshawn Barthelemy,Rebounds,2.5,2.5,1.909091,100
855,Keeshawn Barthelemy,3-PT Made,1.5,1.5,1.909091,100
857,Nate Bittle,Points,15.5,15.5,1.909091,100
861,TJ Bamba,Points,10.5,11.5,2.150000,100

In [30]:
from scipy.stats import poisson
from scipy.optimize import minimize

def implied_odds_at_point(draft_kings_line, lambda_):
        # DraftKings line is an integer threshold (either x.5 or x.0, where x.0 has a push opportunity, so be wary)
        # use the pdf function to get the exact probability of the line
        exact_odds = poisson.pmf(draft_kings_line, lambda_)
        return ((1 - poisson.cdf(draft_kings_line, lambda_)) / (1-exact_odds))


def get_implied_odds(pp_line, draft_kings_line, draft_kings_over_line):
    # Function to solve for lambda
    def solve_lambda(lambda_):
        return abs(implied_odds_at_point(draft_kings_line, lambda_) - (1/draft_kings_over_line))

    # Optimize to find lambda
    # essentially, were setting the two sides of the minus sign to be equal
    result = minimize(solve_lambda, x0=[draft_kings_line], bounds=[(0, None)]) 
    lambda_ = result.x[0]
    print(lambda_, pp_line, draft_kings_line, draft_kings_over_line)
    
    # Calculate the probability of exceeding the pp_line
    prob_over_pp_line = (1 - poisson.cdf(pp_line, lambda_)) / (1 - poisson.pmf(pp_line, lambda_))
    return prob_over_pp_line

results_df["implied_odds"] = results_df.apply(lambda row: get_implied_odds(row["line"], row["dk_line"], row["dk_over_line"]), axis=1)

6.447018821441663 6.0 6.5 2.15
12.319976967649543 12.0 11.5 1.74074075
2.9065708054849946 2.5 2.5 1.8
9.57423397770799 9.0 9.5 2.05
6.256244402984918 6.0 6.5 2.3
7.83520763829703 7.5 7.5 1.90909091
18.926543729409254 18.5 18.5 1.90909091
2.863117077642007 2.5 2.5 1.83333334
7.753918352985066 7.0 7.5 1.95238096
18.66772636410719 17.5 18.5 2.0
6.897345089320311 6.5 6.5 1.86956522
11.772859420108013 11.5 11.5 1.95238096
1.7923521421894872 1.5 1.5 1.86956522
0.765467838872946 0.5 0.5 1.86956522
20.397692190815274 19.0 20.5 2.1
3.841083965071309 3.5 3.5 1.86956522
10.66852240015345 10.0 10.5 2.0
6.068236024899497 5.5 5.5 1.76923077
9.399805897016869 8.5 9.5 2.15
12.88149555359085 12.5 12.5 1.90909091
7.505660415323538 6.5 7.5 2.1
12.88149555359085 12.5 12.5 1.90909091
1.7923521421894872 1.5 1.5 1.86956522
7.669249440678442 7.0 7.5 2.0
21.391149465153717 20.5 21.5 2.1
0.7178397857801238 0.5 0.5 1.95238096
4.977532333685147 4.5 4.5 1.8
16.226469798371358 15.0 15.5 1.8
6.068236024899497 5.5 5.5 1.76923077
17.41835926426836 16.5 17.5 2.1
5.465252082275372 5.0 5.5 2.15
1.8963659533191415 1.5 1.5 1.76923077
12.981716117643412 12.5 12.5 1.86956522
1.8963659533191415 1.5 1.5 1.76923077
12.061821526968963 11.5 11.5 1.83333334
14.78519649578814 14.5 14.5 1.95238096
12.061821526968963 11.5 11.5 1.83333334
19.28249186482143 18.5 19.5 2.15
23.958867900834438 23.5 23.5 1.90909091
6.068236024899497 5.5 5.5 1.76923077
15.005247407923601 14.5 14.5 1.86956522
6.12681141350702 5.5 5.5 1.74074075
4.7368954289694765 4.5 4.5 1.95238096
12.981716117643412 12.5 12.5 1.86956522
10.027087196419215 9.5 9.5 1.83333334
0.765467838872946 0.5 0.5 1.86956522
7.035436168501905 6.5 6.5 1.8
22.522467997573198 21.5 22.5 2.05
10.186844242336917 9.5 9.5 1.76923077
17.796404029701378 16.5 17.5 1.95238096
1.8280419279375388 1.5 1.5 1.83333334
10.66852240015345 10.0 10.5 2.0
10.027087196419215 9.5 9.5 1.83333334
1.8963659533191415 1.5 1.5 1.76923077
1.8963659533191415 1.5 1.5 1.76923077
8.928451578800276 8.5 8.5 1.86956522
6.669637071229367 6.0 6.5 2.0
2.863117077642007 2.5 2.5 1.83333334
9.399805897016869 8.5 9.5 2.15
9.399805897016869 9.0 9.5 2.15
5.812839056591394 5.5 5.5 1.90909091
11.372554629968365 10.5 11.5 2.15
12.981716117643412 12.5 12.5 1.86956522
2.863117077642007 2.5 2.5 1.83333334
12.981716117643412 12.5 12.5 1.86956522
15.005247407923601 14.5 14.5 1.86956522
8.264665858771357 8.0 7.5 1.71428572
4.040842197103709 3.5 3.5 1.74074075
16.667853678219128 15.5 16.5 2.0
12.319976967649543 11.5 11.5 1.74074075
3.9442124028444443 3.5 3.5 1.8
11.969270348967404 11.5 11.5 1.86956522
13.889627679894245 13.5 13.5 1.90909091
11.040198297123071 10.0 11.5 2.35
3.8935153109627914 3.5 3.5 1.83333334
11.564488609255324 10.5 11.5 2.05
8.49487757913693 8.0 8.5 2.1
9.484748652446934 8.5 9.5 2.1
3.9442124028444443 3.5 3.5 1.8
10.864250245405545 10.0 10.5 1.90909091
4.800375098028862 4.5 4.5 1.90909091
17.667786415086297 16.5 17.5 2.0
6.967629225010736 6.5 6.5 1.83333334
10.768432327721628 10.0 10.5 1.95238096
1.8280419279375388 1.5 1.5 1.83333334
5.945052113124081 5.5 5.5 1.83333334
15.433159543685719 14.5 15.5 2.1
7.83520763829703 7.5 7.5 1.90909091
7.358505193617779 6.5 7.5 2.2
5.945052113124081 5.5 5.5 1.83333334
9.399805897016869 8.5 9.5 2.15
10.335938734610417 10.0 9.5 1.71428572
7.83520763829703 7.5 7.5 1.90909091
17.539791014138782 16.5 17.5 2.05
9.085482614635092 8.5 8.5 1.8
3.841083965071309 3.5 3.5 1.86956522
14.440926870830003 13.5 14.5 2.1
10.95629568043895 10.5 10.5 1.86956522
6.897345089320311 6.5 6.5 1.86956522
15.905072969345182 15.0 15.5 1.90909091
11.564488609255324 11.0 11.5 2.05
3.841083965071309 3.5 3.5 1.86956522
16.12344965854717 15.5 15.5 1.83333334
17.796404029701378 17.5 17.5 1.95238096
7.505660415323538 6.5 7.5 2.1
6.824396251002376 6.5 6.5 1.90909091
12.150968691187854 11.5 11.5 1.8
1.7923521421894872 1.5 1.5 1.86956522
15.78904291431238 15.5 15.5 1.95238096
7.505660415323538 7.0 7.5 2.1
12.150968691187854 11.5 11.5 1.8
2.863117077642007 2.5 2.5 1.83333334
7.988655580570958 7.5 7.5 1.83333334
7.753918352985066 7.5 7.5 1.95238096
7.035436168501905 6.5 6.5 1.8
10.768432327721628 10.5 10.5 1.95238096
12.150968691187854 11.5 11.5 1.8
3.9442124028444443 3.5 3.5 1.8
14.551457031825056 13.5 14.5 2.05
1.8280419279375388 1.5 1.5 1.83333334
1.9291159847972492 1.5 1.5 1.74074075
9.085482614635092 8.5 8.5 1.8
11.040198297123071 10.0 11.5 2.35
3.9932875508379975 3.5 3.5 1.76923077
9.399805897016869 8.5 9.5 2.15
5.74291150086564 5.5 5.5 1.95238096
20.403889469787245 19.5 19.5 1.76923077
1.8280419279375388 1.5 1.5 1.83333334
0.788457350029032 0.5 0.5 1.83333334
11.040198297123071 9.5 11.5 2.35
5.880156326849378 5.5 5.5 1.86956522
15.005247407923601 14.5 14.5 1.86956522
2.8182433961353617 2.5 2.5 1.86956522
8.928451578800276 8.5 8.5 1.86956522
7.290216699457652 7.0 7.5 2.25
7.913376688296642 7.5 7.5 1.86956522
3.8935153109627914 3.5 3.5 1.83333334
17.41835926426836 16.5 17.5 2.1
6.748572520898498 6.5 6.5 1.95238096
7.753918352985066 7.5 7.5 1.95238096
13.781225722603383 13.0 13.5 1.95238096
6.748572520898498 6.0 6.5 1.95238096
14.235859759921249 13.0 14.5 2.2
5.670161183585448 5.0 5.5 2.0
6.748572520898498 6.0 6.5 1.95238096
13.668114595777501 13.0 13.5 2.0
3.9442124028444443 3.5 3.5 1.8
8.264665858771357 8.0 7.5 1.71428572
18.037769670746712 17.0 17.5 1.86956522
4.920536905342345 4.5 4.5 1.83333334
18.037769670746712 17.5 17.5 1.86956522
3.841083965071309 3.5 3.5 1.86956522
7.913376688296642 7.5 7.5 1.86956522
7.988655580570958 7.5 7.5 1.83333334
1.7175824771235049 1.5 1.5 1.95238096
6.517245791684338 6.0 6.5 2.1
12.150968691187854 11.5 11.5 1.8
12.981716117643412 12.5 12.5 1.86956522
14.440926870830003 13.5 14.5 2.1
12.88149555359085 12.0 12.5 1.90909091
8.199097436462159 8.0 7.5 1.74074075
2.863117077642007 2.5 2.5 1.83333334
7.83520763829703 7.5 7.5 1.90909091
3.7867935133584134 3.5 3.5 1.90909091
4.920536905342345 4.5 4.5 1.83333334
13.993692136413397 13.5 13.5 1.86956522
15.905072969345182 15.5 15.5 1.90909091
11.040198297123071 10.0 11.5 2.35
1.8280419279375388 1.5 1.5 1.83333334
6.447018821441663 6.0 6.5 2.15
14.668015753330797 13.5 14.5 2.0
3.841083965071309 3.5 3.5 1.86956522
1.7555569086465337 1.5 1.5 1.90909091
10.262636064793396 9.5 9.5 1.74074075
2.7718512626756824 2.5 2.5 1.90909091
2.8182433961353617 2.5 2.5 1.86956522
9.484748652446934 8.5 9.5 2.1
8.928451578800276 8.5 8.5 1.86956522
16.325766321655777 16.0 15.5 1.76923077
7.913376688296642 7.5 7.5 1.86956522
16.016423019310537 15.5 15.5 1.86956522
14.140435447406846 13.0 14.5 2.25
3.8935153109627914 3.5 3.5 1.83333334
8.33816085286944 8.0 8.5 2.2
19.93332005806202 19.0 19.5 1.90909091
8.845394925078194 8.5 8.5 1.90909091
1.8626930092376819 1.5 1.5 1.8
11.668363143677938 11.0 11.5 2.0
6.447018821441663 6.0 6.5 2.15
20.292898893819867 20.0 19.5 1.8
3.841083965071309 3.5 3.5 1.86956522
15.108848273436642 15.0 14.5 1.83333334
11.668363143677938 11.0 11.5 2.0
9.855051479840872 9.5 9.5 1.90909091
10.027087196419215 9.5 9.5 1.83333334
6.007694967574557 5.5 5.5 1.8
21.19037800139307 20.5 20.5 1.83333334
4.040842197103709 3.5 3.5 1.74074075
9.484748652446934 8.5 9.5 2.1
1.8626930092376819 1.5 1.5 1.8
12.150968691187854 11.5 11.5 1.8
2.948693427811639 2.5 2.5 1.76923077
11.969270348967404 11.5 11.5 1.86956522
15.78904291431238 15.0 15.5 1.95238096
0.8329091186540821 0.5 0.5 1.76923077
17.02725382127306 16.0 16.5 1.86956522
1.8280419279375388 1.5 1.5 1.83333334
20.806739184309844 20.0 20.5 1.95238096
7.035436168501905 6.5 6.5 1.8
12.981716117643412 13.0 12.5 1.86956522
6.256244402984918 6.0 6.5 2.3
9.399805897016869 8.5 9.5 2.15
5.086018101767217 4.5 4.5 1.74074075
8.928451578800276 8.5 8.5 1.86956522
7.988655580570958 7.5 7.5 1.83333334
13.781225722603383 13.0 13.5 1.95238096
13.260409488640395 12.5 12.5 1.76923077
2.948693427811639 2.5 2.5 1.76923077
12.777118193948427 12.0 12.5 1.95238096
20.93992961821656 20.5 20.5 1.90909091
7.913376688296642 7.5 7.5 1.86956522
14.440926870830003 14.0 14.5 2.1
5.598031069104649 5.0 5.5 2.05
15.208585214662829 15.0 14.5 1.8
4.920536905342345 4.5 4.5 1.83333334
12.981716117643412 12.0 12.5 1.86956522
18.536138868417943 17.5 18.5 2.05
14.78519649578814 14.0 14.5 1.95238096
3.8935153109627914 3.5 3.5 1.83333334
13.993692136413397 13.5 13.5 1.86956522
18.66772636410719 17.5 18.5 2.0
13.448974346712607 12.5 13.5 2.1
3.8935153109627914 3.5 3.5 1.83333334
5.880156326849378 5.5 5.5 1.86956522
12.668229055935377 12.5 12.5 2.0
8.758988312265805 8.0 8.5 1.95238096
19.40439903345446 18.5 19.5 2.1
6.12681141350702 5.5 5.5 1.74074075
21.525759274571335 20.5 21.5 2.05
9.57423397770799 9.0 9.5 2.05
21.263109977020388 20.5 21.5 2.15
15.667929539317244 15.0 15.5 2.0
6.316798179097609 6.0 6.5 2.25
7.913376688296642 7.5 7.5 1.86956522
8.845394925078194 8.5 8.5 1.90909091
11.772859420108013 11.0 11.5 1.95238096
1.7555569086465337 1.5 1.5 1.90909091
12.236949400520594 12.0 11.5 1.76923077
6.824396251002376 6.5 6.5 1.90909091
9.008406969150197 8.5 8.5 1.83333334
17.41835926426836 16.5 17.5 2.1
8.845394925078194 8.5 8.5 1.90909091
4.86153378954624 4.5 4.5 1.86956522
9.484748652446934 9.0 9.5 2.1
14.78519649578814 14.5 14.5 1.95238096
13.170908624945763 13.0 12.5 1.8
11.044851580457083 10.5 10.5 1.83333334
18.260618474827954 18.0 17.5 1.8
15.905072969345182 15.0 15.5 1.90909091
5.529849485487878 5.0 5.5 2.1
2.9065708054849946 2.5 2.5 1.8
9.085482614635092 8.5 8.5 1.8
13.078094018687075 12.5 12.5 1.83333334
15.208585214662829 14.5 14.5 1.8
12.981716117643412 12.5 12.5 1.86956522
12.777118193948427 12.5 12.5 1.95238096
15.005247407923601 14.5 14.5 1.86956522
19.05544113328036 17.5 19.5 2.25
3.8935153109627914 3.5 3.5 1.83333334
12.981716117643412 12.5 12.5 1.86956522
1.8626930092376819 1.5 1.5 1.8
5.945052113124081 5.5 5.5 1.83333334
7.505660415323538 6.5 7.5 2.1
10.262636064793396 10.0 9.5 1.74074075
2.7718512626756824 2.5 2.5 1.90909091
8.845394925078194 8.0 8.5 1.90909091
13.078094018687075 12.5 12.5 1.83333334
11.466049066179181 10.5 11.5 2.1
12.777118193948427 12.0 12.5 1.95238096
18.926543729409254 18.5 18.5 1.90909091
4.920536905342345 4.5 4.5 1.83333334
8.264665858771357 8.0 7.5 1.71428572
7.585201507224583 7.0 7.5 2.05
1.8280419279375388 1.5 1.5 1.83333334
14.440926870830003 13.5 14.5 2.1
17.08794754326748 16.0 17.5 2.25
7.358505193617779 7.0 7.5 2.2
11.372554629968365 10.5 11.5 2.15
1.8280419279375388 1.5 1.5 1.83333334
5.345578064104385 5.0 5.5 2.25
22.323586862534658 22.0 21.5 1.8
6.748572520898498 6.0 6.5 1.95238096
7.753918352985066 7.0 7.5 1.95238096
11.873049273332185 11.5 11.5 1.90909091
6.38030215591763 6.0 6.5 2.2
14.668015753330797 14.0 14.5 2.0
2.9065708054849946 2.5 2.5 1.8
22.323586862534658 21.5 21.5 1.8
6.748572520898498 6.5 6.5 1.95238096
12.359841602280033 12.0 12.5 2.15
14.668015753330797 13.5 14.5 2.0
11.969270348967404 11.5 11.5 1.86956522
6.068236024899497 6.0 5.5 1.76923077
9.484748652446934 8.5 9.5 2.1
12.150968691187854 11.5 11.5 1.8
15.005247407923601 14.5 14.5 1.86956522
3.8935153109627914 3.5 3.5 1.83333334
1.8626930092376819 1.5 1.5 1.8
20.6676237013105 19.5 20.5 2.0
3.9932875508379975 3.5 3.5 1.76923077
4.086968378508133 3.5 3.5 1.71428572
14.440926870830003 13.5 14.5 2.1
3.8935153109627914 3.5 3.5 1.83333334
15.304730396077488 15.0 14.5 1.76923077
8.131341637087413 7.5 7.5 1.76923077
9.57423397770799 9.0 9.5 2.05
6.591322273585759 6.0 6.5 2.05
14.78519649578814 14.5 14.5 1.95238096
7.505660415323538 7.0 7.5 2.1
0.8329091186540821 0.5 0.5 1.76923077
5.529849485487878 5.0 5.5 2.1
16.792775664029435 16.5 16.5 1.95238096
1.8626930092376819 1.5 1.5 1.8
7.988655580570958 7.5 7.5 1.83333334
5.032652824981758 4.5 4.5 1.76923077
15.905072969345182 15.0 15.5 1.90909091
8.199097436462159 8.0 7.5 1.74074075
5.670161183585448 5.0 5.5 2.0
13.668114595777501 13.0 13.5 2.0
4.4853646300651855 4.0 4.5 2.15
19.93332005806202 19.5 19.5 1.90909091
8.131341637087413 8.0 7.5 1.76923077
17.539791014138782 16.5 17.5 2.05
8.414545369395753 8.0 8.5 2.15
13.668114595777501 13.0 13.5 2.0
10.864250245405545 10.5 10.5 1.90909091
10.108391435345183 9.5 9.5 1.8
4.977532333685147 4.5 4.5 1.8
8.264665858771357 8.0 7.5 1.71428572
13.781225722603383 12.5 13.5 1.95238096
2.8182433961353617 2.5 2.5 1.86956522
13.993692136413397 13.5 13.5 1.86956522
11.564488609255324 11.0 11.5 2.05
6.748572520898498 6.5 6.5 1.95238096
16.667853678219128 15.0 16.5 2.0
2.7718512626756824 2.5 2.5 1.90909091
1.7555569086465337 1.5 1.5 1.90909091
15.905072969345182 15.5 15.5 1.90909091
11.372554629968365 10.5 11.5 2.15

In [31]:
results_df.sort_values(by="implied_odds", ascending=False)

,name,stat,line,dk_line,dk_over_line,dk_under_line,implied_odds
333,KJ Adams Jr.,Points,9.5,11.5,2.350000,100,0.663836
849,Jackson Shelstad,Points,15.0,16.5,2.000000,100,0.659883
665,Walter Clayton Jr.,Points,17.5,19.5,2.250000,100,0.626411
361,Bez Mbeng,Points,13.0,14.5,2.200000,100,0.625384
41,Jackson McAndrew,Points,6.5,7.5,2.100000,100,0.622619
...,...,...,...,...,...,...,...
573,Will Pruitt,Points,12.5,12.5,2.000000,100,0.500000
805,Kobe Elvis,Points,8.0,7.5,1.769231,100,0.494769
465,Tyler McGhie,Points,15.0,14.5,1.833333,100,0.493602
744,Mustapha Amzil,Rebounds,6.0,5.5,1.769231,100,0.482056
505,KeShawn Murphy,Points,13.0,12.5,1.869565,100,0.477434

In [32]:
results_df = results_df[results_df['line'] == results_df['dk_line']]
results_df.sort_values(by='dk_over_line', ascending=True)

,name,stat,line,dk_line,dk_over_line,dk_under_line,implied_odds
760,Jaden Bradley,Rebounds,3.5,3.5,1.714286,100,0.583333
172,Chase Hunter,Rebounds,3.5,3.5,1.740741,100,0.574468
177,Ian Schieffelin,Points,11.5,11.5,1.740741,100,0.574468
319,Johnell Davis,3-PT Made,1.5,1.5,1.740741,100,0.574468
580,PJ Haggerty,Rebounds,5.5,5.5,1.740741,100,0.574468
...,...,...,...,...,...,...,...
277,Chaz Lanier,Points,17.5,17.5,1.952381,100,0.512195
353,Henry Coleman III,Points,7.5,7.5,1.952381,100,0.512195
781,Liam McNeeley,Points,16.5,16.5,1.952381,100,0.512195
352,Henry Coleman III,Rebounds,6.5,6.5,1.952381,100,0.512195
573,Will Pruitt,Points,12.5,12.5,2.000000,100,0.500000

In [33]:
results_df.sort_values(by='dk_over_line', ascending=False)

,name,stat,line,dk_line,dk_over_line,dk_under_line,implied_odds
573,Will Pruitt,Points,12.5,12.5,2.000000,100,0.500000
781,Liam McNeeley,Points,16.5,16.5,1.952381,100,0.512195
326,Dajuan Harris Jr.,Assists,5.5,5.5,1.952381,100,0.512195
353,Henry Coleman III,Points,7.5,7.5,1.952381,100,0.512195
293,Zakai Zeigler,Points,15.5,15.5,1.952381,100,0.512195
...,...,...,...,...,...,...,...
97,Myles Colvin,Points,5.5,5.5,1.740741,100,0.574468
484,Bo Montgomery,Rebounds,3.5,3.5,1.740741,100,0.574468
319,Johnell Davis,3-PT Made,1.5,1.5,1.740741,100,0.574468
177,Ian Schieffelin,Points,11.5,11.5,1.740741,100,0.574468
760,Jaden Bradley,Rebounds,3.5,3.5,1.714286,100,0.583333

In [34]:
import math 
math.sqrt(3)

1.7320508075688772

In [35]:
1 / math.sqrt(3)

0.5773502691896258

In [36]:
1 - (0.487 - (115 / 210 - 0.5))

0.5606190476190477