# Introduction

In [ ]:
import soccerdata as sd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

TEST_PRINT = False
def test_print(x):
    if TEST_PRINT:
        if isinstance(x, pd.DataFrame):
            print(x.head())
        elif isinstance(x, pd.Series):
            print(x.head())
        elif isinstance(x, np.ndarray):
            print(x[:5])
        elif isinstance(x, list):
            print(x[:5])
        else:
            print(x)

[06/28/25 22:24:11] INFO     No custom team name replacements found. You can configure these in       ]8;id=415506;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_config.py\_config.py]8;;\:]8;id=431774;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_config.py#90\90]8;;\
                             C:\Users\Aaron\soccerdata\config\teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    ]8;id=321991;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_config.py\_config.py]8;;\:]8;id=146346;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_config.py#196\196]8;;\
                             C:\Users\Aaron\soccerdata\config\league_dict.json.

# Import Data

In [3]:
# Create scraper class instance
fbref = sd.FBref(seasons=[2425], leagues=['GER-Bundesliga'])

[06/28/25 22:24:17] INFO     Saving cached data to C:\Users\Aaron\soccerdata\data\FBref              ]8;id=565524;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=875989;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\_common.py#263\263]8;;\

In [4]:
team_stats = fbref.read_team_season_stats()
player_stats = fbref.read_player_season_stats(stat_type='standard')
player_stats

c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py:159: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(dfs)
c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py:159: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(dfs)

                                                      nation    pos age  born  \

league         season team      player
GER-Bundesliga 2425   Augsburg  Alexis Claude-Maurice    FRA  MF,FW  26  1998
                                Arne Engels              BEL  MF,FW  20  2003
                                Arne Maier               GER     MF  25  1999
                                Cedric Zesiger           SUI     DF  26  1998
                                Chrislain Matsima        FRA     DF  22  2002
...                                                      ...    ...  ..   ...
                      Wolfsburg Ridle Baku               GER  FW,MF  26  1998
                                Salih Özcan              TUR     MF  26  1998
                                Sebastiaan Bornauw       BEL     DF  25  1999
                                Tiago Tomás              POR  FW,MF  22  2002
                                Yannick Gerhardt         GER  MF,DF  30  1994

                                                      Playing Time         \
                                                                MP Starts
league         season team      player
GER-Bundesliga 2425   Augsburg  Alexis Claude-Maurice           28     25
                                Arne Engels                      1      1
                                Arne Maier                      28      7
                                Cedric Zesiger                  15     15
                                Chrislain Matsima               30     28
...                                                            ...    ...
                      Wolfsburg Ridle Baku                      15     14
                                Salih Özcan                     11      3
                                Sebastiaan Bornauw              15      8
                                Tiago Tomás                     32     23
                                Yannick Gerhardt                29     15

                                                                  Performance  \
                                                        Min   90s         Gls
league         season team      player
GER-Bundesliga 2425   Augsburg  Alexis Claude-Maurice  2109  23.4           9
                                Arne Engels              79   0.9           0
                                Arne Maier              938  10.4           0
                                Cedric Zesiger         1221  13.6           0
                                Chrislain Matsima      2551  28.3           1
...                                                     ...   ...         ...
                      Wolfsburg Ridle Baku             1170  13.0           2
                                Salih Özcan             353   3.9           0
                                Sebastiaan Bornauw      788   8.8           2
                                Tiago Tomás            1884  20.9           6
                                Yannick Gerhardt       1518  16.9           1

                                                           ... Per 90 Minutes  \
                                                      Ast  ...            Gls
league         season team      player                     ...
GER-Bundesliga 2425   Augsburg  Alexis Claude-Maurice   2  ...           0.38
                                Arne Engels             0  ...            0.0
                                Arne Maier              0  ...            0.0
                                Cedric Zesiger          2  ...            0.0
                                Chrislain Matsima       1  ...           0.04
...                                                    ..  ...            ...
                      Wolfsburg Ridle Baku              1  ...           0.15
                                Salih Özcan             0  ...            0.0
                                Sebastiaan Bornauw      1  ...           0.23
                                Tiago Tomás             1  ...           0.29
                                Yannick Gerhardt        1  ...           0.06

                                                                         \
                                                        Ast   G+A  G-PK
league         season team      player
GER-Bundesliga 2425   Augsburg  Alexis Claude-Maurice  0.09  0.47  0.38
                                Arne Engels             0.0   0.0   0.0
                                Arne Maier              0.0   0.0   0.0
                                Cedric Zesiger         0.15  0.15   0.0
                                Chrislain Matsima      0.04  0.07  0.04
...                                                     ...   ...   ...
                      Wolfsburg Ridle Baku             0.08  0.23  0.15
                                Salih Özcan             0.0   0.0   0.0
                                Sebastiaan Bornauw     0.11  0.34  0.23
                                Tiago Tomás            0.05  0.33  0.29
                                Yannick Gerhardt       0.06  0.12  0.06

                                                                          \
                                                      G+A-PK    xG   xAG
league         season team      player
GER-Bundesliga 2425   Augsburg  Alexis Claude-Maurice   0.47   0.2  0.05
                                Arne Engels              0.0  0.45   0.0
                                Arne Maier               0.0  0.15  0.14
                                Cedric Zesiger          0.15  0.09  0.09
                                Chrislain Matsima       0.07  0.06  0.01
...                                                      ...   ...   ...
                      Wolfsburg Ridle Baku              0.23  0.11   0.1
                                Salih Özcan              0.0  0.03   0.2
                                Sebastiaan Bornauw      0.34  0.14  0.06
                                Tiago Tomás             0.33  0.26  0.13
                                Yannick Gerhardt        0.12  0.07  0.01


                                                      xG+xAG  npxG npxG+xAG
league         season team      player
GER-Bundesliga 2425   Augsburg  Alexis Claude-Maurice   0.25   0.2     0.25
                                Arne Engels             0.45  0.45     0.45
                                Arne Maier              0.29  0.15     0.29
                                Cedric Zesiger          0.18  0.09     0.18
                                Chrislain Matsima       0.07  0.06     0.07
...                                                      ...   ...      ...
                      Wolfsburg Ridle Baku              0.21  0.11     0.21
                                Salih Özcan             0.23  0.03     0.23
                                Sebastiaan Bornauw       0.2  0.14      0.2
                                Tiago Tomás             0.38  0.26     0.38
                                Yannick Gerhardt        0.08  0.07     0.08

[492 rows x 33 columns]

In [5]:
player_match_stats = fbref.read_player_match_stats(stat_type='summary')
player_match_stats

c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py:159: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(dfs)

[06/28/25 22:24:20] INFO     [1/308] Retrieving game with id=d42e53df                                  ]8;id=148425;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=940605;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [2/308] Retrieving game with id=967de8db                                  ]8;id=998208;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=904602;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [3/308] Retrieving game with id=3750f4ea                                  ]8;id=227230;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=189410;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [4/308] Retrieving game with id=a64e4ea4                                  ]8;id=399849;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=45127;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [5/308] Retrieving game with id=b549a198                                  ]8;id=807379;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=78701;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:21] INFO     [6/308] Retrieving game with id=02dc2f7e                                  ]8;id=147408;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=714930;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [7/308] Retrieving game with id=cd173a0a                                  ]8;id=783186;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=711201;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [8/308] Retrieving game with id=26a137cc                                  ]8;id=420917;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=378808;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:22] INFO     [9/308] Retrieving game with id=48886f11                                  ]8;id=683787;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=441518;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [10/308] Retrieving game with id=ce5d1374                                 ]8;id=821154;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=234153;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [11/308] Retrieving game with id=d31a8f27                                 ]8;id=761731;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=347267;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [12/308] Retrieving game with id=20afc3a6                                 ]8;id=199500;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=435376;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:23] INFO     [13/308] Retrieving game with id=7e2bdec0                                 ]8;id=814675;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=311042;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [14/308] Retrieving game with id=20df1da5                                 ]8;id=820282;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=404826;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [15/308] Retrieving game with id=378509f5                                 ]8;id=588452;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=360504;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [16/308] Retrieving game with id=0f6a93b4                                 ]8;id=707632;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=39779;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:24] INFO     [17/308] Retrieving game with id=c11acc1b                                 ]8;id=693756;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=430711;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [18/308] Retrieving game with id=19bab96c                                 ]8;id=458216;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=940952;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [19/308] Retrieving game with id=c19c18dc                                 ]8;id=733999;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=387158;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [20/308] Retrieving game with id=5ad7fdc3                                 ]8;id=662553;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=976304;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:25] INFO     [21/308] Retrieving game with id=571e17c9                                 ]8;id=730968;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=488361;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [22/308] Retrieving game with id=e7b9f373                                 ]8;id=868139;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=317472;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [23/308] Retrieving game with id=728afee1                                 ]8;id=883817;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=345188;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [24/308] Retrieving game with id=5496aa43                                 ]8;id=240718;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=115283;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:26] INFO     [25/308] Retrieving game with id=c0bc9354                                 ]8;id=886409;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=17405;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [26/308] Retrieving game with id=d0ee2c59                                 ]8;id=883678;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=525418;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [27/308] Retrieving game with id=253ece9e                                 ]8;id=401601;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=18465;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [28/308] Retrieving game with id=72461171                                 ]8;id=611069;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=287007;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:27] INFO     [29/308] Retrieving game with id=b8e02820                                 ]8;id=854833;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=386397;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [30/308] Retrieving game with id=71024b44                                 ]8;id=675099;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=667151;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [31/308] Retrieving game with id=157d560f                                 ]8;id=470225;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=556956;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [32/308] Retrieving game with id=204b5cf0                                 ]8;id=896299;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=161707;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:28] INFO     [33/308] Retrieving game with id=f4a4421c                                 ]8;id=65160;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=498866;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [34/308] Retrieving game with id=f247334b                                 ]8;id=675906;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=39935;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [35/308] Retrieving game with id=4e23f1b6                                 ]8;id=629775;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=123969;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [36/308] Retrieving game with id=ddfcf507                                 ]8;id=906989;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=331584;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:29] INFO     [37/308] Retrieving game with id=bf284236                                 ]8;id=439111;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=144074;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [38/308] Retrieving game with id=ea3571c5                                 ]8;id=616234;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=569632;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [39/308] Retrieving game with id=c2910931                                 ]8;id=572053;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=252408;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [40/308] Retrieving game with id=a1a2f716                                 ]8;id=283841;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=965874;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:30] INFO     [41/308] Retrieving game with id=fc9efe43                                 ]8;id=556526;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=531517;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [42/308] Retrieving game with id=98d6a4cb                                 ]8;id=212185;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=107169;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [43/308] Retrieving game with id=d72309cf                                 ]8;id=484370;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=750017;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [44/308] Retrieving game with id=a0e9bb68                                 ]8;id=91439;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=129603;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:31] INFO     [45/308] Retrieving game with id=791f7734                                 ]8;id=202179;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=172410;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [46/308] Retrieving game with id=dd751497                                 ]8;id=309423;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=571839;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [47/308] Retrieving game with id=ecd2d8d1                                 ]8;id=511088;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=346618;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [48/308] Retrieving game with id=cb256282                                 ]8;id=270077;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=575956;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [49/308] Retrieving game with id=48a230e5                                 ]8;id=421504;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=986402;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:32] INFO     [50/308] Retrieving game with id=5716e53f                                 ]8;id=156257;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=21511;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [51/308] Retrieving game with id=b6ae6f08                                 ]8;id=360231;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=768074;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [52/308] Retrieving game with id=47b6b5b9                                 ]8;id=485170;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=436015;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [53/308] Retrieving game with id=8f593aee                                 ]8;id=364245;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=979142;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:33] INFO     [54/308] Retrieving game with id=122852eb                                 ]8;id=495661;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=188956;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [55/308] Retrieving game with id=3a6031d4                                 ]8;id=787300;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=543249;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [56/308] Retrieving game with id=7562a0c2                                 ]8;id=609090;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=754816;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [57/308] Retrieving game with id=19da909f                                 ]8;id=740510;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=643135;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:34] INFO     [58/308] Retrieving game with id=e0c0a8fe                                 ]8;id=203230;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=717083;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [59/308] Retrieving game with id=70f3717a                                 ]8;id=208901;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=617907;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [60/308] Retrieving game with id=1766e653                                 ]8;id=81769;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=238696;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [61/308] Retrieving game with id=11e680f6                                 ]8;id=90540;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=985708;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:35] INFO     [62/308] Retrieving game with id=49aa197e                                 ]8;id=83401;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=849516;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [63/308] Retrieving game with id=afaee823                                 ]8;id=147754;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=780099;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [64/308] Retrieving game with id=ad43a11c                                 ]8;id=390459;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=728868;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [65/308] Retrieving game with id=5c672984                                 ]8;id=282820;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=794785;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:36] INFO     [66/308] Retrieving game with id=e12d2336                                 ]8;id=814099;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=439127;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [67/308] Retrieving game with id=75894bbc                                 ]8;id=155822;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=819027;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [68/308] Retrieving game with id=1cd904a3                                 ]8;id=878777;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=338343;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [69/308] Retrieving game with id=7c95858c                                 ]8;id=110980;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=884772;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:37] INFO     [70/308] Retrieving game with id=47698a8f                                 ]8;id=334103;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=843181;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [71/308] Retrieving game with id=fc665c18                                 ]8;id=58092;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=298084;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [72/308] Retrieving game with id=90526971                                 ]8;id=770334;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=722326;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [73/308] Retrieving game with id=c803a5eb                                 ]8;id=777348;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=797534;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:38] INFO     [74/308] Retrieving game with id=61af44e4                                 ]8;id=813992;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=809045;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [75/308] Retrieving game with id=7756d7d5                                 ]8;id=853160;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=428271;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [76/308] Retrieving game with id=f5fc1b23                                 ]8;id=495320;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=781626;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [77/308] Retrieving game with id=2e0fc0d2                                 ]8;id=262776;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=945909;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:39] INFO     [78/308] Retrieving game with id=a51846c1                                 ]8;id=184126;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=749177;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [79/308] Retrieving game with id=41c73b44                                 ]8;id=626634;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=108342;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [80/308] Retrieving game with id=86485b52                                 ]8;id=344601;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=115606;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [81/308] Retrieving game with id=b9ce1157                                 ]8;id=54127;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=190563;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [82/308] Retrieving game with id=05b458bf                                 ]8;id=768454;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=833284;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:40] INFO     [83/308] Retrieving game with id=50ab5485                                 ]8;id=724848;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=869528;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [84/308] Retrieving game with id=ff7bcb61                                 ]8;id=104270;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=71327;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [85/308] Retrieving game with id=639bf27f                                 ]8;id=832275;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=777944;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [86/308] Retrieving game with id=213e9aea                                 ]8;id=94020;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=222297;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:41] INFO     [87/308] Retrieving game with id=58ac698f                                 ]8;id=859322;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=90807;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [88/308] Retrieving game with id=67fa64af                                 ]8;id=332027;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=114083;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [89/308] Retrieving game with id=27da1c68                                 ]8;id=225032;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=27118;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [90/308] Retrieving game with id=2155226b                                 ]8;id=889949;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=717835;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:42] INFO     [91/308] Retrieving game with id=797e3d3e                                 ]8;id=850259;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=68253;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [92/308] Retrieving game with id=72699490                                 ]8;id=513932;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=335766;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [93/308] Retrieving game with id=b410a6e3                                 ]8;id=688116;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=261689;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [94/308] Retrieving game with id=b5f40472                                 ]8;id=577213;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=525670;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:43] INFO     [95/308] Retrieving game with id=573e0883                                 ]8;id=999619;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=700205;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [96/308] Retrieving game with id=9552b88a                                 ]8;id=309339;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=726443;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [97/308] Retrieving game with id=16895d71                                 ]8;id=310944;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=73831;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [98/308] Retrieving game with id=b0221e69                                 ]8;id=850271;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=268080;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:44] INFO     [99/308] Retrieving game with id=eb577d48                                 ]8;id=764582;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=122903;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [100/308] Retrieving game with id=5c8b9990                                ]8;id=793790;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=851821;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [101/308] Retrieving game with id=b1e5b315                                ]8;id=50130;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=803712;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [102/308] Retrieving game with id=77d36005                                ]8;id=32677;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=325233;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:45] INFO     [103/308] Retrieving game with id=358ea55d                                ]8;id=873284;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=765868;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [104/308] Retrieving game with id=b0c93fa3                                ]8;id=371007;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=795618;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [105/308] Retrieving game with id=19910993                                ]8;id=821789;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=813655;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [106/308] Retrieving game with id=61c993b3                                ]8;id=669020;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=118260;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:46] INFO     [107/308] Retrieving game with id=055831dc                                ]8;id=5090;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=947999;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [108/308] Retrieving game with id=16d2485c                                ]8;id=301903;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=161384;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [109/308] Retrieving game with id=41b2c9a7                                ]8;id=717413;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=589304;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [110/308] Retrieving game with id=aff85c23                                ]8;id=427978;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=417424;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [111/308] Retrieving game with id=73bf4f3e                                ]8;id=448313;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=388722;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:47] INFO     [112/308] Retrieving game with id=4442b38e                                ]8;id=329663;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=445568;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [113/308] Retrieving game with id=975c1d76                                ]8;id=757870;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=644700;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [114/308] Retrieving game with id=5b484005                                ]8;id=301229;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=77806;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [115/308] Retrieving game with id=326bf78c                                ]8;id=371881;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=858899;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:48] INFO     [116/308] Retrieving game with id=3b2c1622                                ]8;id=381106;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=8636;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [117/308] Retrieving game with id=4c76fa51                                ]8;id=85420;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=805747;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [118/308] Retrieving game with id=3142b1ac                                ]8;id=540210;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=50590;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [119/308] Retrieving game with id=b2439369                                ]8;id=57190;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=605723;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:49] INFO     [120/308] Retrieving game with id=9082168d                                ]8;id=21310;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=125431;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [121/308] Retrieving game with id=dc3aa7be                                ]8;id=699938;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=237608;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [122/308] Retrieving game with id=f9c6643f                                ]8;id=176687;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=940816;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [123/308] Retrieving game with id=171e1d37                                ]8;id=539872;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=156878;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:50] INFO     [124/308] Retrieving game with id=cf85934f                                ]8;id=628147;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=259459;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [125/308] Retrieving game with id=406ac14d                                ]8;id=79634;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=826242;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [126/308] Retrieving game with id=7f0b7508                                ]8;id=498336;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=606108;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [127/308] Retrieving game with id=b1590970                                ]8;id=112501;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=684231;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:51] INFO     [128/308] Retrieving game with id=1b681fd7                                ]8;id=266592;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=11892;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [129/308] Retrieving game with id=0e787c0f                                ]8;id=758811;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=72812;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [130/308] Retrieving game with id=8d956d1f                                ]8;id=407949;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=229816;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [131/308] Retrieving game with id=9d56a702                                ]8;id=599733;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=353204;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:52] INFO     [132/308] Retrieving game with id=446a9815                                ]8;id=201181;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=563152;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [133/308] Retrieving game with id=3a05d86e                                ]8;id=768121;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=908781;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [134/308] Retrieving game with id=adeb37a5                                ]8;id=648243;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=868981;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [135/308] Retrieving game with id=6948e2d4                                ]8;id=755581;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=256813;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [136/308] Retrieving game with id=54ce0559                                ]8;id=405635;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=194961;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:53] INFO     [137/308] Retrieving game with id=3e4b6950                                ]8;id=585071;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=366939;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [138/308] Retrieving game with id=95b5760f                                ]8;id=236849;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=212973;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [139/308] Retrieving game with id=f3b5b40c                                ]8;id=614411;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=302952;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [140/308] Retrieving game with id=606b4f3d                                ]8;id=651561;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=770865;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:54] INFO     [141/308] Retrieving game with id=319e48db                                ]8;id=743071;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=96308;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [142/308] Retrieving game with id=7ff87749                                ]8;id=948725;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=362370;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [143/308] Retrieving game with id=e99a4554                                ]8;id=902142;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=224305;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [144/308] Retrieving game with id=ca3024b8                                ]8;id=11751;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=585008;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:55] INFO     [145/308] Retrieving game with id=826e71bd                                ]8;id=387340;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=839507;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [146/308] Retrieving game with id=0967d02c                                ]8;id=728438;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=922929;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [147/308] Retrieving game with id=bffe5cc0                                ]8;id=284805;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=711485;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [148/308] Retrieving game with id=1f4078fa                                ]8;id=270657;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=536558;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:56] INFO     [149/308] Retrieving game with id=31d47dd3                                ]8;id=959828;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=212068;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [150/308] Retrieving game with id=0ed57a99                                ]8;id=149024;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=701903;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [151/308] Retrieving game with id=081e6d08                                ]8;id=837929;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=27753;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [152/308] Retrieving game with id=dbe65fff                                ]8;id=899528;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=57289;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:57] INFO     [153/308] Retrieving game with id=44a88ae4                                ]8;id=146727;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=335951;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [154/308] Retrieving game with id=005a65f4                                ]8;id=631821;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=102291;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [155/308] Retrieving game with id=05f318cc                                ]8;id=206308;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=437444;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [156/308] Retrieving game with id=f702b3ab                                ]8;id=839248;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=126945;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [157/308] Retrieving game with id=14522bc5                                ]8;id=638133;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=289766;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:58] INFO     [158/308] Retrieving game with id=fac01a25                                ]8;id=916249;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=581725;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [159/308] Retrieving game with id=3bf36d69                                ]8;id=709387;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=947060;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [160/308] Retrieving game with id=e057d531                                ]8;id=208259;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=787067;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:24:59] INFO     [161/308] Retrieving game with id=abafaba1                                ]8;id=77865;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=716807;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [162/308] Retrieving game with id=10062a04                                ]8;id=520517;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=854815;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [163/308] Retrieving game with id=fd026179                                ]8;id=286592;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=133896;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [164/308] Retrieving game with id=be9e8dad                                ]8;id=180066;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=78718;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [165/308] Retrieving game with id=11d1c71c                                ]8;id=632069;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=630735;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:00] INFO     [166/308] Retrieving game with id=f4b1b7e1                                ]8;id=748166;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=219703;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [167/308] Retrieving game with id=e1972a42                                ]8;id=93922;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=496347;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [168/308] Retrieving game with id=15fd87e3                                ]8;id=459787;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=243688;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [169/308] Retrieving game with id=cfcc6770                                ]8;id=777985;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=233447;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:01] INFO     [170/308] Retrieving game with id=3b329c8a                                ]8;id=26024;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=481526;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [171/308] Retrieving game with id=77f7b50a                                ]8;id=160506;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=501070;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [172/308] Retrieving game with id=5d31cfeb                                ]8;id=896545;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=43891;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [173/308] Retrieving game with id=5b710b34                                ]8;id=688110;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=370404;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:02] INFO     [174/308] Retrieving game with id=db02399e                                ]8;id=641762;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=559689;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [175/308] Retrieving game with id=54a09715                                ]8;id=941090;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=144984;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [176/308] Retrieving game with id=b18bceea                                ]8;id=545686;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=229117;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [177/308] Retrieving game with id=138b9d28                                ]8;id=928884;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=452673;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:03] INFO     [178/308] Retrieving game with id=616b4ea5                                ]8;id=647064;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=181362;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [179/308] Retrieving game with id=2861d451                                ]8;id=656483;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=340096;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [180/308] Retrieving game with id=be216889                                ]8;id=173170;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=369977;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [181/308] Retrieving game with id=dede20b2                                ]8;id=272339;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=186689;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:04] INFO     [182/308] Retrieving game with id=3a6ba600                                ]8;id=834107;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=86769;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [183/308] Retrieving game with id=02b849f8                                ]8;id=667550;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=635462;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [184/308] Retrieving game with id=a3887d2e                                ]8;id=980711;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=384127;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [185/308] Retrieving game with id=cf6b4de4                                ]8;id=97216;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=785998;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:05] INFO     [186/308] Retrieving game with id=cff7de63                                ]8;id=268360;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=725417;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [187/308] Retrieving game with id=853e68b5                                ]8;id=512682;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=297776;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [188/308] Retrieving game with id=521f766a                                ]8;id=668739;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=828546;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [189/308] Retrieving game with id=827c2291                                ]8;id=23547;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=804502;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:06] INFO     [190/308] Retrieving game with id=594320d9                                ]8;id=186068;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=837764;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [191/308] Retrieving game with id=451156e0                                ]8;id=389339;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=21369;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [192/308] Retrieving game with id=5da24f91                                ]8;id=919350;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=37613;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [193/308] Retrieving game with id=75d89be3                                ]8;id=4208;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=185306;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:07] INFO     [194/308] Retrieving game with id=de63fff0                                ]8;id=993051;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=866268;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [195/308] Retrieving game with id=6ed0551d                                ]8;id=85549;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=581388;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [196/308] Retrieving game with id=a7eaacdb                                ]8;id=745713;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=416460;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [197/308] Retrieving game with id=ee260489                                ]8;id=654884;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=916330;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:08] INFO     [198/308] Retrieving game with id=e8d6223f                                ]8;id=991834;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=661640;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [199/308] Retrieving game with id=47e68da4                                ]8;id=51079;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=927763;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [200/308] Retrieving game with id=937a7c71                                ]8;id=855666;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=175614;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [201/308] Retrieving game with id=93560e55                                ]8;id=743757;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=426747;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:09] INFO     [202/308] Retrieving game with id=9f784f25                                ]8;id=889886;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=422124;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [203/308] Retrieving game with id=c6fc28ec                                ]8;id=800141;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=485760;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [204/308] Retrieving game with id=cec14305                                ]8;id=306622;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=444909;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [205/308] Retrieving game with id=a994aa80                                ]8;id=826412;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=554642;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [206/308] Retrieving game with id=26c7700f                                ]8;id=653026;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=478897;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:10] INFO     [207/308] Retrieving game with id=9420a8fb                                ]8;id=949605;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=181292;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [208/308] Retrieving game with id=2359b29d                                ]8;id=308454;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=568300;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [209/308] Retrieving game with id=4b05dd9f                                ]8;id=444280;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=513991;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [210/308] Retrieving game with id=3771f9a8                                ]8;id=661462;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=300260;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:11] INFO     [211/308] Retrieving game with id=b63f6c52                                ]8;id=953999;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=782684;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [212/308] Retrieving game with id=e49b66ef                                ]8;id=816503;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=711523;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [213/308] Retrieving game with id=e96a9875                                ]8;id=10558;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=639734;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [214/308] Retrieving game with id=445a72d7                                ]8;id=840404;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=441332;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:12] INFO     [215/308] Retrieving game with id=a928bf8e                                ]8;id=790155;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=739981;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [216/308] Retrieving game with id=f7cc643f                                ]8;id=287788;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=125184;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [217/308] Retrieving game with id=d430e70c                                ]8;id=601065;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=516543;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [218/308] Retrieving game with id=dfa28f9b                                ]8;id=245057;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=311488;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:13] INFO     [219/308] Retrieving game with id=52386e22                                ]8;id=909853;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=512942;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [220/308] Retrieving game with id=2a1c7c5d                                ]8;id=851895;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=568033;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [221/308] Retrieving game with id=55cb7968                                ]8;id=375576;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=680617;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [222/308] Retrieving game with id=ce8580f0                                ]8;id=211388;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=850566;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [223/308] Retrieving game with id=51b3b077                                ]8;id=652379;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=973053;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:14] INFO     [224/308] Retrieving game with id=da418224                                ]8;id=265091;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=410547;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [225/308] Retrieving game with id=ee204929                                ]8;id=401713;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=855860;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [226/308] Retrieving game with id=4be7cdcb                                ]8;id=429314;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=266708;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [227/308] Retrieving game with id=33e651f0                                ]8;id=171375;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=201622;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:15] INFO     [228/308] Retrieving game with id=b1beeafe                                ]8;id=840073;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=254143;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [229/308] Retrieving game with id=abc689ba                                ]8;id=904969;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=961791;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [230/308] Retrieving game with id=aaf55506                                ]8;id=487015;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=809441;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [231/308] Retrieving game with id=ed2f2d83                                ]8;id=835364;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=245141;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:16] INFO     [232/308] Retrieving game with id=c34cbccf                                ]8;id=286940;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=916477;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [233/308] Retrieving game with id=df0b5d3c                                ]8;id=225805;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=600715;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [234/308] Retrieving game with id=fb471c62                                ]8;id=958377;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=912492;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [235/308] Retrieving game with id=b2dc2e55                                ]8;id=839626;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=327910;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [236/308] Retrieving game with id=1ab0ff43                                ]8;id=556610;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=72181;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:17] INFO     [237/308] Retrieving game with id=f17b1ac5                                ]8;id=294964;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=46076;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [238/308] Retrieving game with id=bc35ebf6                                ]8;id=539075;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=82603;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [239/308] Retrieving game with id=ac5e7e15                                ]8;id=737693;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=672665;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [240/308] Retrieving game with id=9cc7f833                                ]8;id=804551;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=387865;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:18] INFO     [241/308] Retrieving game with id=45215cba                                ]8;id=739035;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=552415;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [242/308] Retrieving game with id=170ac3bc                                ]8;id=955098;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=505317;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [243/308] Retrieving game with id=f1ea8b17                                ]8;id=454255;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=469983;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [244/308] Retrieving game with id=6420938b                                ]8;id=980085;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=220628;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:19] INFO     [245/308] Retrieving game with id=b223187e                                ]8;id=908215;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=317623;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [246/308] Retrieving game with id=5bb8bb3d                                ]8;id=393177;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=359975;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [247/308] Retrieving game with id=0cae3543                                ]8;id=109811;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=477286;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [248/308] Retrieving game with id=dbdc6ab0                                ]8;id=832938;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=561851;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:20] INFO     [249/308] Retrieving game with id=541c3057                                ]8;id=250968;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=520680;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [250/308] Retrieving game with id=109281c0                                ]8;id=430824;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=419853;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [251/308] Retrieving game with id=567410c5                                ]8;id=462704;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=874451;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [252/308] Retrieving game with id=4d106cd0                                ]8;id=795065;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=987118;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [253/308] Retrieving game with id=279f61ea                                ]8;id=994051;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=678416;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:21] INFO     [254/308] Retrieving game with id=448aadc2                                ]8;id=371377;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=509540;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [255/308] Retrieving game with id=90ff09ad                                ]8;id=742064;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=722691;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [256/308] Retrieving game with id=7909fa1f                                ]8;id=368601;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=898583;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [257/308] Retrieving game with id=3ffde43a                                ]8;id=733429;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=151908;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:22] INFO     [258/308] Retrieving game with id=caf45775                                ]8;id=24784;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=457623;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [259/308] Retrieving game with id=05cfe672                                ]8;id=619619;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=199809;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [260/308] Retrieving game with id=734c51b1                                ]8;id=20081;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=572168;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [261/308] Retrieving game with id=fa069898                                ]8;id=362867;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=250636;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:23] INFO     [262/308] Retrieving game with id=20ecf347                                ]8;id=657989;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=436033;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [263/308] Retrieving game with id=16677768                                ]8;id=882852;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=751014;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [264/308] Retrieving game with id=e6a0bf3c                                ]8;id=611182;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=698588;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [265/308] Retrieving game with id=000fb8fc                                ]8;id=707406;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=978335;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:24] INFO     [266/308] Retrieving game with id=2730ce86                                ]8;id=402234;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=947317;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [267/308] Retrieving game with id=8fc6caf7                                ]8;id=357470;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=150406;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [268/308] Retrieving game with id=d894af02                                ]8;id=799980;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=642551;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [269/308] Retrieving game with id=96810141                                ]8;id=256706;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=701353;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:25] INFO     [270/308] Retrieving game with id=44f5146c                                ]8;id=98394;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=878983;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [271/308] Retrieving game with id=7aff3a58                                ]8;id=718656;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=117834;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [272/308] Retrieving game with id=c8ec6e9b                                ]8;id=468112;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=482939;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [273/308] Retrieving game with id=b7fb0f38                                ]8;id=103783;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=977748;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:26] INFO     [274/308] Retrieving game with id=c27495e8                                ]8;id=592846;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=604172;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [275/308] Retrieving game with id=8c788caa                                ]8;id=448158;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=963081;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [276/308] Retrieving game with id=eda7cf54                                ]8;id=520173;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=410644;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [277/308] Retrieving game with id=d8e56aa9                                ]8;id=896603;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=108998;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [278/308] Retrieving game with id=7b2f198b                                ]8;id=150160;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=608713;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:27] INFO     [279/308] Retrieving game with id=58168f30                                ]8;id=744430;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=624738;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [280/308] Retrieving game with id=99708bc3                                ]8;id=78372;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=649149;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [281/308] Retrieving game with id=f7ead844                                ]8;id=941321;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=884530;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [282/308] Retrieving game with id=66ab948b                                ]8;id=136452;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=597698;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:28] INFO     [283/308] Retrieving game with id=332c0ad2                                ]8;id=268802;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=814815;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [284/308] Retrieving game with id=922a1743                                ]8;id=158870;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=267395;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [285/308] Retrieving game with id=0ae221aa                                ]8;id=510411;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=752889;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [286/308] Retrieving game with id=c306cc96                                ]8;id=241416;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=144487;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:29] INFO     [287/308] Retrieving game with id=96a2ca0c                                ]8;id=955705;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=624277;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [288/308] Retrieving game with id=52b3b191                                ]8;id=297336;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=352151;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [289/308] Retrieving game with id=8848ad08                                ]8;id=379608;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=770787;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [290/308] Retrieving game with id=ec9d955b                                ]8;id=265866;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=625800;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:30] INFO     [291/308] Retrieving game with id=77e2bfdb                                ]8;id=654202;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=639269;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [292/308] Retrieving game with id=54765c32                                ]8;id=816073;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=843959;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [293/308] Retrieving game with id=93fc8379                                ]8;id=662986;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=449256;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [294/308] Retrieving game with id=d240d0af                                ]8;id=86683;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=266443;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:31] INFO     [295/308] Retrieving game with id=1d23b7b3                                ]8;id=27772;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=230912;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [296/308] Retrieving game with id=fe0fd091                                ]8;id=751525;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=239765;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [297/308] Retrieving game with id=fe881f9c                                ]8;id=833443;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=795086;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [298/308] Retrieving game with id=3201dcb5                                ]8;id=748847;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=17046;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:32] INFO     [299/308] Retrieving game with id=1bb6490a                                ]8;id=258997;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=507753;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [300/308] Retrieving game with id=b4e069ab                                ]8;id=799192;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=859413;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [301/308] Retrieving game with id=8600012e                                ]8;id=967463;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=825090;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [302/308] Retrieving game with id=6509021f                                ]8;id=643669;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=32703;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:33] INFO     [303/308] Retrieving game with id=0d8a2ebf                                ]8;id=57040;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=307713;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [304/308] Retrieving game with id=1e213908                                ]8;id=283845;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=806051;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [305/308] Retrieving game with id=e457ba22                                ]8;id=235503;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=141169;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [306/308] Retrieving game with id=f8aa5a5b                                ]8;id=867654;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=803;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

[06/28/25 22:25:34] INFO     [307/308] Retrieving game with id=ea16299e                                ]8;id=690610;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=821642;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

                    INFO     [308/308] Retrieving game with id=933eae7f                                ]8;id=740798;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=92863;file://c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py#816\816]8;;\

c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py:1221: UserWarning: Different columns found for [['2024-08-23 Gladbach-Leverkusen']] and [['2025-05-22 Heidenheim-Elversberg']].

The following columns are missing in [['2024-08-23 Gladbach-Leverkusen']]: ('Carries', 'Carries'), ('Carries', 'PrgC'), ('Expected', 'npxG'), ('Expected', 'xAG'), ('Expected', 'xG'), ('Passes', 'Att'), ('Passes', 'Cmp'), ('Passes', 'Cmp%'), ('Passes', 'PrgP'), ('Performance', 'Blocks'), ('Performance', 'Tkl'), ('Performance', 'Touches'), ('SCA', 'GCA'), ('SCA', 'SCA'), ('Take-Ons', 'Att'), ('Take-Ons', 'Succ').

The following columns are missing in [['2025-05-22 Heidenheim-Elversberg']]: ('Performance', 'Crs'), ('Performance', 'Fld'), ('Performance', 'Fls'), ('Performance', 'OG'), ('Performance', 'Off'), ('Performance', 'PKcon'), ('Performance', 'PKwon'), ('Performance', 'TklW').

The columns of the dataframe with the most columns will be used.
  warnings.warn(
c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py:1221: UserWarning: Different columns found for [['2024-08-23 Gladbach-Leverkusen']] and [['2025-05-22 Heidenheim-Elversberg']].

The following columns are missing in [['2024-08-23 Gladbach-Leverkusen']]: ('Carries', 'Carries'), ('Carries', 'PrgC'), ('Expected', 'npxG'), ('Expected', 'xAG'), ('Expected', 'xG'), ('Passes', 'Att'), ('Passes', 'Cmp'), ('Passes', 'Cmp%'), ('Passes', 'PrgP'), ('Performance', 'Blocks'), ('Performance', 'Tkl'), ('Performance', 'Touches'), ('SCA', 'GCA'), ('SCA', 'SCA'), ('Take-Ons', 'Att'), ('Take-Ons', 'Succ').

The following columns are missing in [['2025-05-22 Heidenheim-Elversberg']]: ('Performance', 'Crs'), ('Performance', 'Fld'), ('Performance', 'Fls'), ('Performance', 'OG'), ('Performance', 'Off'), ('Performance', 'PKcon'), ('Performance', 'PKwon'), ('Performance', 'TklW').

The columns of the dataframe with the most columns will be used.
  warnings.warn(
c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py:1221: UserWarning: Different columns found for [['2024-08-23 Gladbach-Leverkusen']] and [['2025-05-26 Elversberg-Heidenheim']].

The following columns are missing in [['2024-08-23 Gladbach-Leverkusen']]: ('Carries', 'Carries'), ('Carries', 'PrgC'), ('Expected', 'npxG'), ('Expected', 'xAG'), ('Expected', 'xG'), ('Passes', 'Att'), ('Passes', 'Cmp'), ('Passes', 'Cmp%'), ('Passes', 'PrgP'), ('Performance', 'Blocks'), ('Performance', 'Tkl'), ('Performance', 'Touches'), ('SCA', 'GCA'), ('SCA', 'SCA'), ('Take-Ons', 'Att'), ('Take-Ons', 'Succ').

The following columns are missing in [['2025-05-26 Elversberg-Heidenheim']]: ('Performance', 'Crs'), ('Performance', 'Fld'), ('Performance', 'Fls'), ('Performance', 'OG'), ('Performance', 'Off'), ('Performance', 'PKcon'), ('Performance', 'PKwon'), ('Performance', 'TklW').

The columns of the dataframe with the most columns will be used.
  warnings.warn(
c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py:1221: UserWarning: Different columns found for [['2024-08-23 Gladbach-Leverkusen']] and [['2025-05-26 Elversberg-Heidenheim']].

The following columns are missing in [['2024-08-23 Gladbach-Leverkusen']]: ('Carries', 'Carries'), ('Carries', 'PrgC'), ('Expected', 'npxG'), ('Expected', 'xAG'), ('Expected', 'xG'), ('Passes', 'Att'), ('Passes', 'Cmp'), ('Passes', 'Cmp%'), ('Passes', 'PrgP'), ('Performance', 'Blocks'), ('Performance', 'Tkl'), ('Performance', 'Touches'), ('SCA', 'GCA'), ('SCA', 'SCA'), ('Take-Ons', 'Att'), ('Take-Ons', 'Succ').

The following columns are missing in [['2025-05-26 Elversberg-Heidenheim']]: ('Performance', 'Crs'), ('Performance', 'Fld'), ('Performance', 'Fls'), ('Performance', 'OG'), ('Performance', 'Off'), ('Performance', 'PKcon'), ('Performance', 'PKwon'), ('Performance', 'TklW').

The columns of the dataframe with the most columns will be used.
  warnings.warn(
c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py:1274: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)
c:\Users\Aaron\AppData\Local\Programs\Python\Python310\lib\site-packages\soccerdata\fbref.py:1274: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(dfs)

                                                                                       jersey_number  \

league         season game                             team             player
GER-Bundesliga 2425   2024-08-23 Gladbach-Leverkusen   Bayer Leverkusen Aleix García              24
                                                                        Amine Adli                21
                                                                        Edmond Tapsoba            12
                                                                        Florian Wirtz             10
                                                                        Granit Xhaka              34
...                                                                                              ...
                      2025-05-26 Elversberg-Heidenheim Heidenheim       Niklas Dorsch             39
                                                                        Omar Traoré               23
                                                                        Patrick Mainka             6
                                                                        Paul Wanner               10
                                                                        Tim Siersleben             4

                                                                                       nation  \

league         season game                             team             player
GER-Bundesliga 2425   2024-08-23 Gladbach-Leverkusen   Bayer Leverkusen Aleix García      ESP
                                                                        Amine Adli        MAR
                                                                        Edmond Tapsoba    BFA
                                                                        Florian Wirtz     GER
                                                                        Granit Xhaka      SUI
...                                                                                       ...
                      2025-05-26 Elversberg-Heidenheim Heidenheim       Niklas Dorsch     GER
                                                                        Omar Traoré       GER
                                                                        Patrick Mainka    GER
                                                                        Paul Wanner       GER
                                                                        Tim Siersleben    GER

                                                                                       pos  \

league         season game                             team             player
GER-Bundesliga 2425   2024-08-23 Gladbach-Leverkusen   Bayer Leverkusen Aleix García    CM
                                                                        Amine Adli      FW
                                                                        Edmond Tapsoba  CB
                                                                        Florian Wirtz   AM
                                                                        Granit Xhaka    CM
...                                                                                     ..
                      2025-05-26 Elversberg-Heidenheim Heidenheim       Niklas Dorsch   MF
                                                                        Omar Traoré     RW
                                                                        Patrick Mainka  CB
                                                                        Paul Wanner     MF
                                                                        Tim Siersleben  CB

                                                                                           age  \

league         season game                             team             player
GER-Bundesliga 2425   2024-08-23 Gladbach-Leverkusen   Bayer Leverkusen Aleix García    27-056
                                                                        Amine Adli      24-105
                                                                        Edmond Tapsoba  25-203
                                                                        Florian Wirtz   21-112
                                                                        Granit Xhaka    31-331
...                                                                                        ...
                      2025-05-26 Elversberg-Heidenheim Heidenheim       Niklas Dorsch   27-131
                                                                        Omar Traoré     27-111
                                                                        Patrick Mainka  30-201
                                                                        Paul Wanner     19-154
                                                                        Tim Siersleben  25-078

                                                                                       min  \

league         season game                             team             player
GER-Bundesliga 2425   2024-08-23 Gladbach-Leverkusen   Bayer Leverkusen Aleix García     9
                                                                        Amine Adli       9
                                                                        Edmond Tapsoba  90
                                                                        Florian Wirtz   90
                                                                        Granit Xhaka    90
...                                                                                     ..
                      2025-05-26 Elversberg-Heidenheim Heidenheim       Niklas Dorsch   13
                                                                        Omar Traoré     90
                                                                        Patrick Mainka  90
                                                                        Paul Wanner     13
                                                                        Tim Siersleben  90

                                                                                       Performance  \
                                                                                               Gls
league         season game                             team             player
GER-Bundesliga 2425   2024-08-23 Gladbach-Leverkusen   Bayer Leverkusen Aleix García             0
                                                                        Amine Adli               0
                                                                        Edmond Tapsoba           0
                                                                        Florian Wirtz            2
                                                                        Granit Xhaka             1
...                                                                                            ...
                      2025-05-26 Elversberg-Heidenheim Heidenheim       Niklas Dorsch            0
                                                                        Omar Traoré              0
                                                                        Patrick Mainka           0
                                                                        Paul Wanner              0
                                                                        Tim Siersleben           0

                                                                                            \
                                                                                       Ast
league         season game                             team             player
GER-Bundesliga 2425   2024-08-23 Gladbach-Leverkusen   Bayer Leverkusen Aleix García     0
                                                                        Amine Adli       0
                                                                        Edmond Tapsoba   0
                                                                        Florian Wirtz    0
                                                                        Granit Xhaka     0
...                                                                                     ..
                      2025-05-26 Elversberg-Heidenheim Heidenheim       Niklas Dorsch    0
                                                                        Omar Traoré      0
                                                                        Patrick Mainka   0
                                                                        Paul Wanner      1
                                                                        Tim Siersleben   0

                                                                                           \
                                                                                       PK
league         season game                             team             player
GER-Bundesliga 2425   2024-08-23 Gladbach-Leverkusen   Bayer Leverkusen Aleix García    0
                                                                        Amine Adli      0
                                                                        Edmond Tapsoba  0
                                                                        Florian Wirtz   0
                                                                        Granit Xhaka    0
...                                                                                    ..
                      2025-05-26 Elversberg-Heidenheim Heidenheim       Niklas Dorsch   0
                                                                        Omar Traoré     0
                                                                        Patrick Mainka  0
                                                                        Paul Wanner     0
                                                                        Tim Siersleben  0

                                                                                              \
                                                                                       PKatt
league         season game                             team             player
GER-Bundesliga 2425   2024-08-23 Gladbach-Leverkusen   Bayer Leverkusen Aleix García       0
                                                                        Amine Adli         0
                                                                        Edmond Tapsoba     0
                                                                        Florian Wirtz      1
                                                                        Granit Xhaka       0
...                                                                                      ...
                      2025-05-26 Elversberg-Heidenheim Heidenheim       Niklas Dorsch      0
                                                                        Omar Traoré        0
                                                                        Patrick Mainka     0
                                                                        Paul Wanner        0
                                                                        Tim Siersleben     0

                                                                                           \
                                                                                       Sh
league         season game                             team             player
GER-Bundesliga 2425   2024-08-23 Gladbach-Leverkusen   Bayer Leverkusen Aleix García    0
                                                                        Amine Adli      1
                                                                        Edmond Tapsoba  1
                                                                        Florian Wirtz   3
                                                                        Granit Xhaka    2
...                                                                                    ..
                      2025-05-26 Elversberg-Heidenheim Heidenheim       Niklas Dorsch   0
                                                                        Omar Traoré     0
                                                                        Patrick Mainka  1
                                                                        Paul Wanner     0
                                                                        Tim Siersleben  1

                                                                                        ...  \
                                                                                        ...
league         season game                             team             player          ...
GER-Bundesliga 2425   2024-08-23 Gladbach-Leverkusen   Bayer Leverkusen Aleix García    ...
                                                                        Amine Adli      ...
                                                                        Edmond Tapsoba  ...
                                                                        Florian Wirtz   ...
                                                                        Granit Xhaka    ...
...                                                                                     ...
                      2025-05-26 Elversberg-Heidenheim Heidenheim       Niklas Dorsch   ...
                                                                        Omar Traoré     ...
                                                                        Patrick Mainka  ...
                                                                        Paul Wanner     ...
                                                                        Tim Siersleben  ...

                                                                                         SCA  \
                                                                                         GCA
league         season game                             team             player
GER-Bundesliga 2425   2024-08-23 Gladbach-Leverkusen   Bayer Leverkusen Aleix García       0
                                                                        Amine Adli         0
                                                                        Edmond Tapsoba     0
                                                                        Florian Wirtz      1
                                                                        Granit Xhaka       0
...                                                                                      ...
                      2025-05-26 Elversberg-Heidenheim Heidenheim       Niklas Dorsch   <NA>
                                                                        Omar Traoré     <NA>
                                                                        Patrick Mainka  <NA>
                                                                        Paul Wanner     <NA>
                                                                        Tim Siersleben  <NA>

                                                                                       Passes  \
                                                                                          Cmp
league         season game                             team             player
GER-Bundesliga 2425   2024-08-23 Gladbach-Leverkusen   Bayer Leverkusen Aleix García       24
                                                                        Amine Adli          7
                                                                        Edmond Tapsoba     67
                                                                        Florian Wirtz      48
                                                                        Granit Xhaka       98
...                                                                                       ...
                      2025-05-26 Elversberg-Heidenheim Heidenheim       Niklas Dorsch    <NA>
                                                                        Omar Traoré      <NA>
                                                                        Patrick Mainka   <NA>
                                                                        Paul Wanner      <NA>
                                                                        Tim Siersleben   <NA>

                                                                                              \
                                                                                         Att
league         season game                             team             player
GER-Bundesliga 2425   2024-08-23 Gladbach-Leverkusen   Bayer Leverkusen Aleix García      27
                                                                        Amine Adli         8
                                                                        Edmond Tapsoba    77
                                                                        Florian Wirtz     67
                                                                        Granit Xhaka     104
...                                                                                      ...
                      2025-05-26 Elversberg-Heidenheim Heidenheim       Niklas Dorsch   <NA>
                                                                        Omar Traoré     <NA>
                                                                        Patrick Mainka  <NA>
                                                                        Paul Wanner     <NA>
                                                                        Tim Siersleben  <NA>

                                                                                              \
                                                                                        Cmp%
league         season game                             team             player
GER-Bundesliga 2425   2024-08-23 Gladbach-Leverkusen   Bayer Leverkusen Aleix García    88.9
                                                                        Amine Adli      87.5
                                                                        Edmond Tapsoba  87.0
                                                                        Florian Wirtz   71.6
                                                                        Granit Xhaka    94.2
...                                                                                      ...
                      2025-05-26 Elversberg-Heidenheim Heidenheim       Niklas Dorsch   <NA>
                                                                        Omar Traoré     <NA>
                                                                        Patrick Mainka  <NA>
                                                                        Paul Wanner     <NA>
                                                                        Tim Siersleben  <NA>

                                                                                              \
                                                                                        PrgP
league         season game                             team             player
GER-Bundesliga 2425   2024-08-23 Gladbach-Leverkusen   Bayer Leverkusen Aleix García       1
                                                                        Amine Adli         2
                                                                        Edmond Tapsoba     8
                                                                        Florian Wirtz      7
                                                                        Granit Xhaka      13
...                                                                                      ...
                      2025-05-26 Elversberg-Heidenheim Heidenheim       Niklas Dorsch   <NA>

In [6]:
import csv
# go get data from a csv file saved a folder backwards
with open('../D1.csv', 'r') as f:
    reader = csv.reader(f)
    live_odds = list(reader)
# convert to dataframe
live_odds = pd.DataFrame(live_odds[1:], columns=live_odds[0])
live_odds

,ï»¿Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,D1,23/08/2024,19:30,M'gladbach,Leverkusen,2,3,A,0,2,...,1.86,2.04,1.87,2.06,1.96,2.08,1.91,1.96,1.91,2.07
1,D1,24/08/2024,14:30,Augsburg,Werder Bremen,2,2,D,2,1,...,1.88,2.05,1.88,2.04,1.88,2.06,1.86,2.03,1.9,2.1
2,D1,24/08/2024,14:30,Freiburg,Stuttgart,3,1,H,1,1,...,1.95,1.98,1.95,1.97,1.98,2.09,1.87,2,1.95,2.04
3,D1,24/08/2024,14:30,Hoffenheim,Holstein Kiel,3,2,H,2,0,...,2.03,1.9,1.99,1.93,2.16,1.95,2.02,1.86,2,1.95
4,D1,24/08/2024,14:30,Mainz,Union Berlin,1,1,D,0,0,...,2.1,1.83,2.11,1.83,2.13,1.85,2.07,1.81,2.18,1.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,D1,17/05/2025,14:30,Hoffenheim,Bayern Munich,0,4,A,0,1,...,1.75,2.05,1.81,2.09,1.87,2.13,1.82,2.02,1.92,2.06
302,D1,17/05/2025,14:30,Mainz,Leverkusen,2,2,D,1,0,...,1.86,2.04,1.89,2.03,1.9,2.08,1.86,2.03,1.85,2.16
303,D1,17/05/2025,14:30,M'gladbach,Wolfsburg,0,1,A,0,0,...,2.04,1.86,2.03,1.88,2.04,1.9,2.01,1.85,2.07,1.9
304,D1,17/05/2025,14:30,RB Leipzig,Stuttgart,2,3,A,2,1,...,1.91,1.99,1.92,2.01,1.98,2.03,1.92,1.93,2.04,1.94
305,D1,17/05/2025,14:30,St Pauli,Bochum,0,2,A,0,1,...,1.97,1.93,1.98,1.94,1.98,1.97,1.93,1.92,1.99,1.99

In [7]:
# Lastly, were going to get player transfer value data

# Paramter Generation by Manipulating the way Data is Stored

In [19]:
game_logs_by_player = dict()
# player_match_stats = player_match_stats.reset_index()
# player_match_stats.columns.values[:5] = ['league', 'player_id', 'match_info', 'team', 'player_name']

for _, match in player_match_stats.iterrows():
    # print(match)
    # print(match.keys())
    player_name = match['player'].item()
    print(player_name)
    if player_name not in game_logs_by_player.keys():
        game_logs_by_player[player_name] = []
    game_logs_by_player[player_name].append(match)

game_logs_by_player["Harry Kane"]

Aleix García
Amine Adli
Edmond Tapsoba
Florian Wirtz
Granit Xhaka
Jeremie Frimpong
Jonas Hofmann
Jonathan Tah
Lukáš Hrádecký
Martin Terrier
Piero Hincapié
Robert Andrich
Victor Boniface
Álex Grimaldo
Alassane Pléa
Fabio Chiarodia
Franck Honorat
Joe Scally
Jonas Omlin
Julian Weigl
Kevin Stöger
Ko Itakura
Luca Netz
Nathan N'Goumou
Nico Elvedi
Philipp Sander
Rocco Reitz
Stefan Lainer
Tim Kleindienst
Tomáš Čvančara
Arne Engels
Arne Maier
Dimitris Giannoulis
Elvis Rexhbeçaj
Fredrik Jensen
Jeffrey Gouweleeuw
Keven Schlotterbeck
Mads Pedersen
Marius Wolf
Maximilian Bauer
Nediljko Labrović
Niklas Dorsch
Phillip Tietz
Samuel Essende
Steve Mounié
Tim Breithaupt
Anthony Jung
Felix Agu
Jens Stage
Justin Njinmah
Keke Maximilian Topp
Leonardo Bittencourt
Marco Friedl
Marco Grüll
Marvin Ducksch
Michael Zetterer
Miloš Veljković
Mitchell Weiser
Niklas Stark
Romano Schmid
Senne Lynen
Skelly Alvero
Donyell Malen
Emre Can
Felix Nmecha
Gio Reyna
Gregor Kobel
Jamie Gittens
Julian Brandt
Julian Ryerson
Karim Adeyemi
Marcel Sabitzer
Maximilian Beier
Nico Schlotterbeck
Niklas Süle
Pascal Groß
Ramy Bensebaini
Waldemar Anton
Ansgar Knauff
Arthur Theate
Can Uzun
Ellyes Skhiri
Fares Chaïbi
Hugo Ekitike
Hugo Larsson
Igor Matanovic
Kevin Trapp
Mario Götze
Niels Nkounkou
Omar Marmoush
Oscar Højlund
Rasmus Kristensen
Robin Koch
Tuta
Christian Günter
Florent Muslija
Florian Müller
Ifechukwu Ogbus
Junior Adamu
Lucas Höler
Lukas Kübler
Matthias Ginter
Max Rosenfelder
Maximilian Eggestein
Merlin Röhl
Patrick Osterhage
Philipp Lienhart
Ritsu Doan
Roland Sallai
Vincenzo Grifo
Alexander Nübel
Angelo Stiller
Anrie Chase
Atakan Karazor
Chris Führich
Deniz Undav
Enzo Millot
Ermedin Demirović
Fabian Rieder
Frans Krätzig
Jamie Leweling
Julian Chabot
Justin Diehl
Maximilian Mittelstädt
Nick Woltemade
Pascal Stenzel
Adam Hložek
Alexander Prass
Andrej Kramarić
Anton Stach
Dennis Geiger
Florian Grillitsch
Grischa Prömel
Jacob Bruun Larsen
Kevin Akpoguma
Marius Bülter
Max Moerstedt
Mergim Berisha
Oliver Baumann
Pavel Kadeřábek
Stanley N'Soki
Tim Drexler
Alexander Bernhardsson
Andu Kelati
Benedikt Pichler
Finn Porath
Jann-Fiete Arp
Lewis Holtby
Magnus Knudsen
Marco Komenda
Marko Ivezić
Marvin Schulz
Nicolai Remberg
Patrick Erras
Shuto Machino
Timo Becker
Timon Weiner
Tymoteusz Puchacz
Andreas Hanche-Olsen
Anthony Caci
Armindo Sieb
Dominik Kohr
Jonathan Burkardt
Kaishu Sano
Karim Onisiwo
Lee Jae-sung
Maxim Leitsch
Nadiem Amiri
Nelson Weiper
Paul Nebel
Phillipp Mwene
Robin Zentner
Stefan Bell
András Schäfer
Benedict Hollerbach
Christopher Trimmel
Danilho Doekhi
Diogo Leite
Frederik Rønnow
Janik Haberer
Jordan Pefok
Kevin Vogt
Leopold Querfeld
Lucas Tousart
László Bénes
Rani Khedira
Robin Gosens
Tim Skarke
Yorbe Vertessen
Aliou Badara Baldé
Anthony Losilla
Erhan Mašović
Felix Passlack
Ibrahima Sissoko
Jakov Medić
Lukas Daschner
Mats Pannewig
Matúš Bero
Maximilian Wittek
Moritz Broschinski
Myron Boadu
Patrick Drewes
Philipp Hofmann
Samuel Bamba
Tim Oermann
Amadou Haidara
Antonio Nusa
Benjamin Henrichs
Benjamin Šeško
Castello Lukeba
Christoph Baumgartner
David Raum
Kevin Kampl
Loïs Openda
Lukas Klostermann
Mohamed Simakan
Nicolas Seiwald
Péter Gulácsi
Willi Orban
Xavi Simons
Yussuf Poulsen
Adrian Beck
Benedikt Gimber
Jan Schöppner
Jonas Föhrenbach
Kevin Müller
Lennard Maloney
Luca Kerber
Léo Scienza
Marnon Busch
Marvin Pieringer
Mathias Honsak
Maximilian Breunig
Omar Traoré
Patrick Mainka
Paul Wanner
Sirlord Conteh
Carlo Boukhalfa
Connor Metcalfe
Elias Saad
Eric Smith
Hauke Wahl
Jackson Irvine
Johannes Eggestein
Karol Mets
Lars Ritzka
Manolis Saliakas
Morgan Guilavogui
Nikola Vasilj
Oladapo Afolayan
Philipp Treu
Robert Wagner
Aleksandar Pavlovic
Alphonso Davies
Dayot Upamecano
Eric Dier
Harry Kane
Jamal Musiala
Joshua Kimmich
Kim Min-jae
Kingsley Coman
Manuel Neuer
Michael Olise
Sacha Boey
Serge Gnabry
Thomas Müller
Cedric Zesiger
Jakub Kamiński
Jonas Wind
Kamil Grabara
Kevin Behrens
Kilian Fischer
Lovro Majer
Mattias Svanberg
Maximilian Arnold
Patrick Wimmer
Ridle Baku
Sebastiaan Bornauw
Tiago Tomás
Yannick Gerhardt
Adam Dźwigała
Andreas Albers
Carlo Boukhalfa
Connor Metcalfe
Elias Saad
Eric Smith
Hauke Wahl
Jackson Irvine
Johannes Eggestein
Karol Mets
Lars Ritzka
Morgan Guilavogui
Nikola Vasilj
Oladapo Afolayan
Philipp Treu
Robert Wagner
András Schäfer
Benedict Hollerbach
Danilho Doekhi
Diogo Leite
Frederik Rønnow
Janik Haberer
Jeong Woo-yeong
Jordan Pefok
Kevin Vogt
Leopold Querfeld
Lucas Tousart
László Bénes
Rani Khedira
Tim Skarke
Tom Rothe
Yorbe Vertessen
Aliou Badara Baldé
Anthony Losilla
Dani de Wit
Erhan Mašović
Felix Passlack
Ibrahima Sissoko
Jakov Medić
Lukas Daschner
Mats Pannewig
Matúš Bero
Maximilian Wittek
Moritz Broschinski
Myron Boadu
Patrick Drewes
Philipp Hofmann
Tim Oermann
Alassane Pléa
Franck Honorat
Joe Scally
Jonas Omlin
Julian Weigl
Kevin Stöger
Ko Itakura
Luca Netz
Nathan N'Goumou
Nico Elvedi
Philipp Sander
Robin Hack
Rocco Reitz
Stefan Lainer
Tim Kleindienst
Tomáš Čvančara
Ansgar Knauff
Arthur Theate
Can Uzun
Ellyes Skhiri
Fares Chaïbi
Hugo Ekitike
Hugo Larsson
Igor Matanovic
Kevin Trapp
Mario Götze
Niels Nkounkou
Nnamdi Collins
Omar Marmoush
Rasmus Kristensen
Robin Koch
Tuta
Adam Hložek
Alexander Prass
Andrej Kramarić
Anton Stach
Dennis Geiger
Florian Micheler
Grischa Prömel
Haris Tabakovic
Jacob Bruun Larsen
Kevin Akpoguma
Marius Bülter
Mergim Berisha
Oliver Baumann
Pavel Kadeřábek
Robin Hranáč
Tim Drexler
Alexander Bernhardsson
Armin Gigovic
Benedikt Pichler
Carl Johansson
Finn Porath
Jann-Fiete Arp
Lasse Rosenboom
Lewis Holtby
Magnus Knudsen
Marco Komenda
Max Geschwill
Nicolai Remberg
Patrick Erras
Shuto Machino
Timo Becker
Timon Weiner
Bence Dárdai
Cedric Zesiger
Jakub Kamiński
Jonas Wind
Kamil Grabara
Kilian Fischer
Lovro Majer
Mattias Svanberg
Maximilian Arnold
Patrick Wimmer
Ridle Baku
Salih Özcan
Sebastiaan Bornauw
Tiago Tomás
Yannick Gerhardt
Aleix García
Amine Adli
Arthur
Edmond Tapsoba
Florian Wirtz
Granit Xhaka
Jeremie Frimpong
Jonathan Tah
Martin Terrier
Matej Kovar
Nathan Tella
Patrik Schick
Piero Hincapié
Victor Boniface
Álex Grimaldo
Amadou Haidara
Antonio Nusa
Arthur Vermeeren
Benjamin Henrichs
Benjamin Šeško
Castello Lukeba
Christoph Baumgartner
David Raum
El Chadaille Bitshiabu
Kevin Kampl
Loïs Openda
Lukas Klostermann
Nicolas Seiwald
Péter Gulácsi
Xavi Simons
Yussuf Poulsen
Andreas Hanche-Olsen
Anthony Caci
Armindo Sieb
Aymen Barkok
Dominik Kohr
Hong Hyunseok
Jonathan Burkardt
Kaishu Sano
Lee Jae-sung
Maxim Leitsch
Nadiem Amiri
Nikolas Veratschnig
Phillipp Mwene
Robin Zentner
Silvan Widmer
Stefan Bell
Alexander Nübel
Angelo Stiller
Anrie Chase
Atakan Karazor
Chris Führich
Deniz Undav
El Bilal Touré
Enzo Millot
Ermedin Demirović
Fabian Rieder
Jamie Leweling
Josha Vagnoman
Julian Chabot
Maximilian Mittelstädt
Pascal Stenzel
Ramon Hendriks
Donyell Malen
Emre Can
Felix Nmecha
Gregor Kobel
Jamie Gittens
Julian Brandt
Julian Ryerson
Karim Adeyemi
Marcel Sabitzer
Maximilian Beier
Nico Schlotterbeck
Niklas Süle
Pascal Groß
Ramy Bensebaini
Waldemar Anton
Anthony Jung
Felix Agu
Jens Stage
Justin Njinmah
Keke Maximilian Topp
Marco Friedl
Marco Grüll
Marvin Ducksch
Michael Zetterer
Mitchell Weiser
Niklas Stark
Romano Schmid
Senne Lynen
Aleksandar Pavlovic
Dayot Upamecano
Harry Kane
Jamal Musiala
Joshua Kimmich
João Palhinha
Kim Min-jae
Kingsley Coman
Konrad Laimer
Leon Goretzka
Manuel Neuer
Mathys Tel
Michael Olise
Raphaël Guerreiro
Serge Gnabry
Thomas Müller
Christian Günter
Eren Dinkçi
Florian Müller
Ifechukwu Ogbus
Jordy Makengo
Junior Adamu
Lucas Höler
Lukas Kübler
Max Rosenfelder
Maximilian Eggestein
Merlin Röhl
Patrick Osterhage
Philipp Lienhart
Ritsu Doan
Roland Sallai
Vincenzo Grifo
Arne Maier
Dimitris Giannoulis
Elvis Rexhbeçaj
Fredrik Jensen
Jeffrey Gouweleeuw
Keven Schlotterbeck
Kristijan Jakić
Mads Pedersen
Marius Wolf
Mert Kömür
Nediljko Labrović
Phillip Tietz
Ruben Vargas
Samuel Essende
Steve Mounié
Tim Breithaupt
Adrian Beck
Benedikt Gimber
Jan Schöppner
Jonas Föhrenbach
Kevin Müller
Lennard Maloney
Luca Kerber
Léo Scienza
Marvin Pieringer
Mathias Honsak
Maximilian Breunig
Omar Traoré
Patrick Mainka
Paul Wanner
Sirlord Conteh
Tim Siersleben
Donyell Malen
Emre Can
Felix Nmecha
Gregor Kobel
Jamie Gittens
Julian Brandt
Julian Ryerson
Karim Adeyemi
Marcel Sabitzer
Maximilian Beier
Niklas Süle
Pascal Groß
Ramy Bensebaini
Serhou Guirassy
Waldemar Anton
Yan Couto
Adrian Beck
Benedikt Gimber
Jan Schöppner
Jonas Föhrenbach
Kevin Müller
Lennard Maloney
Léo Scienza
Marvin Pieringer
Mathias Honsak
Maximilian Breunig
Mikkel Kaufmann
Niklas Dorsch
Omar Traoré
Patrick Mainka
Paul Wanner
Sirlord Conteh
Aliou Badara Baldé
Dani de Wit
Erhan Mašović
Felix Passlack
Ibrahima Sissoko
Jakov Medić
Koji Miyoshi
Lukas Daschner
Matúš Bero
Maximilian Wittek
Moritz Broschinski
Moritz-Broni Kwarteng
Myron Boadu
Patrick Drewes
Philipp Hofmann
Samuel Bamba
Christian Günter
Eren Dinkçi
Junior Adamu
Kiliann Sildillia
Lucas Höler
Lukas Kübler
Matthias Ginter
Max Rosenfelder
Maximilian Eggestein
Merlin Röhl
Nicolas Höfler
Noah Atubolu
Patrick Osterhage
Philipp Lienhart
Ritsu Doan
Vincenzo Grifo
Alassane Pléa
Florian Neuhaus
Franck Honorat
Joe Scally
Jonas Omlin
Julian Weigl
Kevin Stöger
Ko Itakura
Luca Netz
Nathan N'Goumou
Nico Elvedi
Philipp Sander
Robin Hack
Rocco Reitz
Tim Kleindienst
Tomáš Čvančara
Alexander Nübel
Angelo Stiller
Anrie Chase
Anthony Rouault
Atakan Karazor
Chris Führich
Dan-Axel Zagadou
Deniz Undav
El Bilal Touré
Enzo Millot
Ermedin Demirović
Fabian Rieder
Jamie Leweling
Josha Vagnoman
Julian Chabot
Maximilian Mittelstädt
Aleix García
Amine Adli
Edmond Tapsoba
Florian Wirtz
Granit Xhaka
Jeremie Frimpong
Jonathan Tah
Lukáš Hrádecký
Martin Terrier
Nathan Tella
Nordi Mukiele
Patrik Schick
Piero Hincapié
Robert Andrich
Victor Boniface
Álex Grimaldo
Alexander Prass
Andrej Kramarić
Anton Stach
Dennis Geiger
Florian Grillitsch
Jacob Bruun Larsen
Kevin Akpoguma
Marius Bülter
Max Moerstedt
Mergim Berisha
Oliver Baumann
Pavel Kadeřábek
Tim Drexler
Tom Bischof
Umut Tohumcu
Valentin Gendrey
Alphonso Davies
Dayot Upamecano
Harry Kane
Jamal Musiala
Joshua Kimmich
João Palhinha
Kim Min-jae
Kingsley Coman
Konrad Laimer
Manuel Neuer
Mathys Tel
Michael Olise
Raphaël Guerreiro
Sacha Boey
Serge Gnabry
Thomas Müller
Armin Gigovic
Benedikt Pichler
Carl Johansson
Dominik Javorček
Finn Porath
Jann-Fiete Arp
Lasse Rosenboom
Lewis Holtby
Magnus Knudsen
Max Geschwill
Nicolai Remberg
Patrick Erras
Shuto Machino
Timo Becker
Timon Weiner
Tymoteusz Puchacz
Amadou Haidara
Antonio Nusa
Arthur Vermeeren
Benjamin Henrichs
Benjamin Šeško
Castello Lukeba
Christoph Baumgartner
David Raum
El Chadaille Bitshiabu
Kevin Kampl
Loïs Openda
Lukas Klostermann
Lutsharel Geertruida
Péter Gulácsi
Xavi Simons
Yussuf Poulsen
Aljoscha Kemlein
András Schäfer
Benedict Hollerbach
Danilho Doekhi
Diogo Leite
Frederik Rønnow
Janik Haberer
Jeong Woo-yeong
Jordan Pefok
Kevin Vogt
Leopold Querfeld
László Bénes
Rani Khedira
Tim Skarke
Tom Rothe
Yorbe Vertessen
Ansgar Knauff
Arthur Theate
Aurele Amenda
Ellyes Skhiri
Fares Chaïbi
Hugo Ekitike
Hugo Larsson
Igor Matanovic
Kauã Santos
Kevin Trapp
Mario Götze
Niels Nkounkou
Omar Marmoush
Rasmus Kristensen
Robin Koch
Tuta
Aster Vranckx
Cedric Zesiger
Jakub Kamiński
Jonas Wind
Kamil Grabara
Kevin Behrens
Kilian Fischer
Konstantinos Koulierakis
Mattias Svanberg
Maximilian Arnold
Mohamed Amoura
Patrick Wimmer
Ridle Baku
Salih Özcan
Sebastiaan Bornauw
Tiago Tomás
Arne Maier
Dimitris Giannoulis
Elvis Rexhbeçaj
Frank Onyeka
Henri Koudossou
Jeffrey Gouweleeuw
Keven Schlotterbeck
Kristijan Jakić
Mads Pedersen
Marius Wolf
Maximilian Bauer
Nediljko Labrović
Phillip Tietz
Ruben Vargas
Samuel Essende
Yusuf Kabadayı
Adam Dźwigała
Andreas Albers
Carlo Boukhalfa
Elias Saad
Eric Smith
Hauke Wahl
Jackson Irvine
Johannes Eggestein
Karol Mets
Lars Ritzka
Manolis Saliakas
Morgan Guilavogui
Nikola Vasilj
Oladapo Afolayan
Philipp Treu
Robert Wagner
Anthony Caci
Armindo Sieb
Aymen Barkok
Dominik Kohr
Hong Hyunseok
Jonathan Burkardt
Kaishu Sano
Karim Onisiwo
Lee Jae-sung
Maxim Leitsch
Moritz Jenz
Nadiem Amiri
Paul Nebel
Phillipp Mwene
Robin Zentner
Silvan Widmer
Anthony Jung
Derrick Köhn
Felix Agu
Jens Stage
Julián Malatini
Justin Njinmah
Keke Maximilian Topp
Marco Friedl
Marco Grüll
Marvin Ducksch
Michael Zetterer
Mitchell Weiser
Niklas Stark
Romano Schmid
Senne Lynen
Skelly Alvero
Arne Maier
Dimitris Giannoulis
Elvis Rexhbeçaj
Frank Onyeka
Fredrik Jensen
Jeffrey Gouweleeuw
Keven Schlotterbeck
Kristijan Jakić
Marius Wolf
Maximilian Bauer
Nediljko Labrović
Phillip Tietz
Ruben Vargas
Samuel Essende
Steve Mounié
Yusuf Kabadayı
Andreas Hanche-Olsen
Anthony Caci
Armindo Sieb
Aymen Barkok
Dominik Kohr
Hong Hyunseok
Jonathan Burkardt
Kaishu Sano
Karim Onisiwo
Maxim Leitsch
Moritz Jenz
Nadiem Amiri
Phillipp Mwene
Robin Zentner
Silvan Widmer
Anthony Losilla
Dani de Wit
Erhan Mašović
Felix Passlack
Ibrahima Sissoko
Jakov Medić
Lukas Daschner
Mats Pannewig
Matúš Bero
Maximilian Wittek
Moritz Broschinski
Moritz-Broni Kwarteng
Myron Boadu
Patrick Drewes
Philipp Hofmann
Andu Kelati
Armin Gigovic
Benedikt Pichler
Carl Johansson
Finn Porath
Jann-Fiete Arp
Lasse Rosenboom
Lewis Holtby
Magnus Knudsen
Max Geschwill
Nicolai Remberg
Shuto Machino
Steven Skrzybski
Timo Becker
Timon Weiner
Tymoteusz Puchacz
Ansgar Knauff
Arthur Theate
Ellyes Skhiri
Fares Chaïbi
Hugo Ekitike
Hugo Larsson
Igor Matanovic
Jean Mattéo Bahoya
Junior Dina Ebimbe
Kauã Santos
Mahmoud Dahoud
Niels Nkounkou
Omar Marmoush
Rasmus Kristensen
Robin Koch
Tuta
Alassane Pléa
Florian Neuhaus
Joe Scally
Julian Weigl
Kevin Stöger
Ko Itakura
Luca Netz
Moritz Nicolas
Nathan N'Goumou
Nico Elvedi
Philipp Sander
Robin Hack
Rocco Reitz
Tim Kleindienst
Tomáš Čvančara
Christian Günter
Eren Dinkçi
Florent Muslija
Johan Manzambi
Jordy Makengo
Junior Adamu
Lucas Höler
Lukas Kübler
Matthias Ginter
Maximilian Eggestein
Noah Atubolu
Noah Weißhaupt
Patrick Osterhage
Philipp Lienhart
Ritsu Doan
Vincenzo Grifo
Benedikt Gimber
Jan Schöppner
Jonas Föhrenbach
Kevin Müller
Lennard Maloney
Léo Scienza
Marnon Busch
Marvin Pieringer
Mathias Honsak
Maximilian Breunig
Niklas Dorsch
Omar Traoré
Patrick Mainka
Paul Wanner
Sirlord Conteh
Stefan Schimmer
Adam Hložek
Alexander Prass
Andrej Kramarić
Anton Stach
Haris Tabakovic
Jacob Bruun Larsen
Kevin Akpoguma
Marius Bülter
Mergim Berisha
Oliver Baumann
Pavel Kadeřábek
Robin Hranáč
Tim Drexler
Tom Bischof
Umut Tohumcu
Valentin Gendrey
András Schäfer
Benedict Hollerbach
Christopher Trimmel
Danilho Doekhi
Diogo Leite
Frederik Rønnow
Janik Haberer
Jeong Woo-yeong
Jordan Pefok
Kevin Vogt
Leopold Querfeld
László Bénes
Rani Khedira
Tim Skarke
Tom Rothe
Yorbe Vertessen
Aleksandar Pavlovic
Alphonso Davies
Dayot Upamecano
Harry Kane
Jamal Musiala
Joshua Kimmich
João Palhinha
Kim Min-jae
Kingsley Coman
Konrad Laimer
Leroy Sané
Michael Olise
Raphaël Guerreiro
Serge Gnabry
Sven Ulreich
Thomas Müller
Amos Pieper
Anthony Jung
Derrick Köhn
Felix Agu
Jens Stage
Julián Malatini
Keke Maximilian Topp
Marco Grüll
Marvin Ducksch
Michael Zetterer
Mitchell Weiser
Niklas Stark
Olivier Deman
Romano Schmid
Senne Lynen
Skelly Alvero
Aleix García
Amine Adli
Edmond Tapsoba
Exequiel Palacios
Florian Wirtz
Granit Xhaka
Jeanuël Belocian
Jeremie Frimpong
Jonathan Tah
Lukáš Hrádecký
Martin Terrier
Nordi Mukiele
Patrik Schick
Piero Hincapié
Victor Boniface
Álex Grimaldo
Aster Vranckx
Cedric Zesiger
Denis Vavro
Jakub Kamiński
Kamil Grabara
Kilian Fischer
Konstantinos Koulierakis
Mattias Svanberg
Maximilian Arnold
Mohamed Amoura
Patrick Wimmer
Ridle Baku
Salih Özcan
Sebastiaan Bornauw
Tiago Tomás
Yannick Gerhardt
Amadou Haidara
André Silva
Antonio Nusa
Arthur Vermeeren
Benjamin Henrichs
Benjamin Šeško
Christoph Baumgartner
David Raum
Loïs Openda
Lukas Klostermann
Lutsharel Geertruida
Nicolas Seiwald
Péter Gulácsi
Willi Orban
Xavi Simons
Yussuf Poulsen
Adam Dźwigała
Carlo Boukhalfa
Connor Metcalfe
Elias Saad
Eric Smith
Hauke Wahl
Jackson Irvine
Johannes Eggestein
Karol Mets
Manolis Saliakas
Morgan Guilavogui
Nikola Vasilj
Oladapo Afolayan
Philipp Treu
Scott Banks
Donyell Malen
Emre Can
Felix Nmecha
Gregor Kobel
Jamie Gittens
Julian Brandt
Julian Ryerson
Karim Adeyemi
Marcel Sabitzer
Nico Schlotterbeck
Niklas Süle
Pascal Groß
Ramy Bensebaini
Serhou Guirassy
Waldemar Anton
Yan Couto
Alexander Nübel
Angelo Stiller
Anrie Chase
Anthony Rouault
Atakan Karazor
Chris Führich
Dan-Axel Zagadou
Deniz Undav
El Bilal Touré
Enzo Millot
Ermedin Demirović
Fabian Rieder
Jamie Leweling
Josha Vagnoman
Julian Chabot
Maximilian Mittelstädt
Aliou Badara Baldé
Anthony Losilla
Dani de Wit
Felix Passlack
Ibrahima Sissoko
Jakov Medić
Koji Miyoshi
Matúš Bero
Maximilian Wittek
Moritz Broschinski
Moritz-Broni Kwarteng
Myron Boadu
Patrick Drewes
Philipp Hofmann
Tim Oermann
Emre Can
Felix Nmecha
Gregor Kobel
Jamie Gittens
Julian Brandt
Julian Ryerson
Julien Duranville
Karim Adeyemi
Maximilian Beier
Nico Schlotterbeck
Niklas Süle
Pascal Groß
Ramy Bensebaini
Serhou Guirassy
Waldemar Anton
Yan Couto
Amine Adli
Edmond Tapsoba
Exequiel Palacios
Florian Wirtz
Granit Xhaka
Jeanuël Belocian
Jeremie Frimpong
Jonathan Tah
Lukáš Hrádecký
Martin Terrier
Nathan Tella
Piero Hincapié
Robert Andrich
Victor Boniface
Álex Grimaldo
Aleksandar Pavlovic
Alphonso Davies
Dayot Upamecano
Harry Kane
Jamal Musiala
Joshua Kimmich
Kim Min-jae
Kingsley Coman
Konrad Laimer
Leroy Sané
Manuel Neuer
Michael Olise
Raphaël Guerreiro
Serge Gnabry
Thomas Müller
Christian Günter
Eren Dinkçi
Florent Muslija
Junior Adamu
Lucas Höler
Lukas Kübler
Matthias Ginter
Maximilian Eggestein
Michael Gregoritsch
Nicolas Höfler
Noah Atubolu
Noah Weißhaupt
Patrick Osterhage
Philipp Lienhart
Ritsu Doan
Vincenzo Grifo
Adam Dźwigała
Andreas Albers
Carlo Boukhalfa
Connor Metcalfe
Danel Sinani
Elias Saad
Eric Smith
Hauke Wahl
Jackson Irvine
Johannes Eggestein
Karol Mets
Manolis Saliakas
Nikola Vasilj
Oladapo Afolayan
Philipp Treu
Scott Banks
Alassane Pléa
Joe Scally
Julian Weigl
Kevin Stöger
Ko Itakura
Luca Netz
Marvin Friedrich
Moritz Nicolas
Nathan N'Goumou
Nico Elvedi
Philipp Sander
Robin Hack
Rocco Reitz
Tim Kleindienst
Tomáš Čvančara
András Schäfer
Benedict Hollerbach
Christopher Trimmel
Danilho Doekhi
Diogo Leite
Frederik Rønnow
Janik Haberer
Jeong Woo-yeong
Jordan Pefok
Kevin Vogt
Leopold Querfeld
László Bénes
Rani Khedira
Tim Skarke
Tom Rothe
Yorbe Vertessen
Adrian Beck
Benedikt Gimber
Jan Schöppner
Jonas Föhrenbach
Kevin Müller
Lennard Maloney
Luca Kerber
Marnon Busch
Marvin Pieringer
Maximilian Breunig
Mikkel Kaufmann
Niklas Dorsch
Omar Traoré
Patrick Mainka
Paul Wanner
Andreas Hanche-Olsen
Anthony Caci
Armindo Sieb
Aymen Barkok
Dominik Kohr
Hong Hyunseok
Jonathan Burkardt
Kaishu Sano
Lee Jae-sung
Moritz Jenz
Nelson Weiper
Paul Nebel
Phillipp Mwene
Robin Zentner
Silvan Widmer
Stefan Bell
Chrislain Matsima
Dimitris Giannoulis
Elvis Rexhbeçaj
Frank Onyeka
Fredrik Jensen
Henri Koudossou
Jeffrey Gouweleeuw
Keven Schlotterbeck
Kristijan Jakić
Marius Wolf
Maximilian Bauer
Nediljko Labrović
Phillip Tietz
Ruben Vargas
Steve Mounié
Yusuf Kabadayı
Amadou Haidara
Antonio Nusa
Arthur Vermeeren
Benjamin Henrichs
Benjamin Šeško
Castello Lukeba
Christoph Baumgartner
David Raum
El Chadaille Bitshiabu
Loïs Openda
Lutsharel Geertruida
Nicolas Seiwald
Péter Gulácsi
Willi Orban
Xavi Simons
Yussuf Poulsen
Alexander Nübel
Angelo Stiller
Anthony Rouault
Atakan Karazor
Chris Führich
Deniz Undav
El Bilal Touré
Enzo Millot
Ermedin Demirović
Fabian Rieder
Jamie Leweling
Josha Vagnoman
Julian Chabot
Maximilian Mittelstädt
Nick Woltemade
Pascal Stenzel
Aster Vranckx
Cedric Zesiger
Jakub Kamiński
Jonas Wind
Kamil Grabara
Kevin Behrens
Kilian Fischer
Konstantinos Koulierakis
Mattias Svanberg
Maximilian Arnold
Mohamed Amoura
Ridle Baku
Salih Özcan
Sebastiaan Bornauw
Tiago Tomás
Adam Hložek
Alexander Prass
Anton Stach
Florian Grillitsch
Jacob Bruun Larsen
Kevin Akpoguma
Marius Bülter
Max Moerstedt
Mergim Berisha
Oliver Baumann
Pavel Kadeřábek
Stanley N'Soki
Tim Drexler
Tom Bischof
Umut Tohumcu
Valentin Gendrey
Amos Pieper
Anthony Jung
Derrick Köhn
Felix Agu
Jens Stage
Julián Malatini
Keke Maximilian Topp
Marco Grüll
Marvin Ducksch
Michael Zetterer

[level_0                                                  256
 index                                                    256
 league                                        GER-Bundesliga
 season                                                  2425
 game                      2024-08-25 Wolfsburg-Bayern Munich
 team                                           Bayern Munich
 player                                            Harry Kane
 jersey_number                                              9
 nation                                                   ENG
 pos                                                       FW
 age                                                   31-028
 min                                                       90
 Performance    Gls                                         0
                Ast                                         1
                PK                                          0
                PKatt                                       0
                Sh                                          2
                SoT                                         1
                CrdY                                        1
                CrdR                                        0
                Touches                                    29
                Tkl                                         0
                Int                                         0
                Blocks                                      2
 Expected       xG                                        0.2
                npxG                                      0.2
                xAG                                       0.4
 SCA            SCA                                         4
                GCA                                         1
 Passes         Cmp                                        15
                Att                                        19
                Cmp%                                     78.9
                PrgP                                        3
 Carries        Carries                                    13
                PrgC                                        1
 Take-Ons       Att                                         2
                Succ                                        1
 game_id                                             48886f11
 Name: 256, dtype: object,
 level_0                                                 500
 index                                                   500
 league                                       GER-Bundesliga
 season                                                 2425
 game                      2024-09-01 Bayern Munich-Freiburg
 team                                          Bayern Munich
 player                                           Harry Kane
 jersey_number                                             9
 nation                                                  ENG
 pos                                                      FW
 age                                                  31-035
 min                                                      90
 Performance    Gls                                        1
                Ast                                        0
                PK                                         1
                PKatt                                      1
                Sh                                         2
                SoT                                        0
                CrdY                                       0
                CrdR                                       0
                Touches                                   35
                Tkl                                        0
                Int                                        0
                Blocks                                     0
 Expected       xG                                       0.8
                npxG                                     0.1
                xAG                                      0.0
 SCA            SCA                                        3
                GCA                                        1
 Passes         Cmp                                       21
                Att                                       26
                Cmp%                                    80.8
                PrgP                                       3
 Carries        Carries                                   19
                PrgC                                       0
 Take-Ons       Att                                        1
                Succ                                       1
 game_id                                            c11acc1b
 Name: 500, dtype: object,
 level_0                                                      692
 index                                                        692
 league                                            GER-Bundesliga
 season                                                      2425
 game                      2024-09-14 Holstein Kiel-Bayern Munich
 team                                               Bayern Munich
 player                                                Harry Kane
 jersey_number                                                  9
 nation                                                       ENG
 pos                                                           FW
 age                                                       31-048
 min                                                           90
 Performance    Gls                                             3
                Ast                                             1
                PK                                              1
                PKatt                                           1
                Sh                                              5
                SoT                                             2
                CrdY                                            0
                CrdR                                            0
                Touches                                        35
                Tkl                                             1
                Int                                             0
                Blocks                                          0
 Expected       xG                                            1.3
                npxG                                          0.5
                xAG                                           0.3
 SCA            SCA                                             7
                GCA                                             2
 Passes         Cmp                                            19
                Att                                            21
                Cmp%                                         90.5
                PrgP                                            6
 Carries        Carries                                        25
                PrgC                                            2
 Take-Ons       Att                                             6
                Succ                                            2
 game_id                                                 728afee1
 Name: 692, dtype: object,
 level_0                                                     1010
 index                                                       1010
 league                                            GER-Bundesliga
 season                                                      2425
 game                      2024-09-21 Werder Bremen-Bayern Munich
 team                                               Bayern Munich
 player                                                Harry Kane
 jersey_number                                                  9
 nation                                                       ENG
 pos                                                           FW
 age                                                       31-055
 min                                                           75
 Performance    Gls                                             1
                Ast                                             2
                PK                                              0
                PKatt                                           0
                Sh                                              7
                SoT                                             2
                CrdY                                            0
                CrdR                                            0
                Touches                                        36
                Tkl                                             1
                Int                                             0
                Blocks                                          0
 Expected       xG                                            0.5
                npxG                                          0.5
                xAG                                           0.6
 SCA            SCA                                             4
                GCA                                             3
 Passes         Cmp                                            22
                Att                                            26
                Cmp%                                         84.6
                PrgP                                            6
 Carries        Carries                                        20
                PrgC                                            1
 Take-Ons       Att                                             1
                Succ                                            0
 game_id                                                 f4a4421c
 Name: 1010, dtype: object,
 level_0                                                  1183
 index                                                    1183
 league                                         GER-Bundesliga
 season                                                   2425
 game                      2024-09-28 Bayern Munich-Leverkusen
 team                                            Bayern Munich
 player                                             Harry Kane
 jersey_number                                               9
 nation                                                    ENG
 pos                                                        FW
 age                                                    31-062
 min                                                        85
 Performance    Gls                                          0
                Ast                                          0
                PK                                           0
                PKatt                                        0
                Sh                                           0
                SoT                                          0
                CrdY                                         0
                CrdR                                         0
                Touches                                     18
                Tkl                                          0
                Int                                          0
                Blocks                                       0
 Expected       xG                                         0.0
                npxG                                       0.0
                xAG                                        0.1
 SCA            SCA                                          2
                GCA                                          0
 Passes         Cmp                                         10
                Att                                         14
                Cmp%                                      71.4
                PrgP                                         0
 Carries        Carries                                     12
                PrgC                                         0
 Take-Ons       Att                                          1
                Succ                                         0
 game_id                                              ea3571c5
 Name: 1183, dtype: object,
 level_0                                                      1606
 index                                                        1606
 league                                             GER-Bundesliga
 season                                                       2425
 game                      2024-10-06 Eint Frankfurt-Bayern Munich
 team                                                Bayern Munich
 player                                                 Harry Kane
 jersey_number                                                   9
 nation                                                        ENG
 pos                                                            FW
 age                                                        31-070
 min                                                            71
 Performance    Gls                                              0
                Ast                                              1
                PK                                               0
                PKatt                                            0
                Sh                                               2
                SoT                                              0
                CrdY                                             0
                CrdR                                             0
                Touches                                         32
                Tkl                                              0
                Int                                              0
                Blocks                                           1
 Expected       xG                                             0.2
                npxG                                           0.2
                xAG                                            0.0
 SCA            SCA                                              3
                GCA                                              1
 Passes         Cmp                                             22
                Att                                             27
                Cmp%                                          81.5
                PrgP                                             2
 Carries        Carries                                         13
                PrgC                                             2
 Take-Ons       Att                                              0
                Succ                                             0
 game_id                                                  47b6b5b9
 Name: 1606, dtype: object,
 level_0                                                 1731
 index                                                   1731
 league                                        GER-Bundesliga
 season                                                  2425
 game                      2024-10-19 Bayern Munich-Stuttgart
 team                                           Bayern Munich
 player                                            Harry Kane
 jersey_number                                              9
 nation                                                   ENG
 pos                                                       FW
 age                                                   31-083
 min                                                       90
 Performance    Gls                                         3
                Ast                                         0
                PK                                          0
                PKatt                                       0
                Sh                                         10
                SoT                                         5
                CrdY                                        0
                CrdR                                        0
                Touches                                    41
                Tkl                                         0
                Int                                         0
                Blocks                                      0
 Expected       xG                                        2.3
                npxG                                      2.3
                xAG                                       0.1
 SCA            SCA                                         6
                GCA                                         2
 Passes         Cmp                                        23
                Att                                        26
                Cmp%                                     88.5
                PrgP                                        6
 Carries        Carries                                    26
                PrgC                                        3
 Take-Ons       Att                                         5
                Succ                                        4
 game_id                                             7562a0c2
 Name: 1731, dtype: object,
 level_0                                              2167
 index                                                2167
 league                                     GER-Bundesliga
 season                                               2425
 game                      2024-10-27 Bochum-Bayern Munich
 team                                        Bayern Munich
 player                                         Harry Kane
 jersey_number                                           9
 nation                                                ENG
 pos                                                    FW
 age                                                31-091
 min                                                    68
 Performance    Gls                                      1
                Ast                                      0
                PK                                       0
                PKatt                                    0
                Sh                                       2
                SoT                                      1
                CrdY                                     0
                CrdR                                     0
                Touches                                 19
                Tkl                                      0
                Int                                      0
                Blocks                                   0
 Expected       xG                                     0.2
                npxG                                   0.2
                xAG                                    0.0
 SCA            SCA                                      1
                GCA                                      1
 Passes         Cmp                                      9
                Att                                     11
                Cmp%                                  81.8
                PrgP                                     0
 Carries        Carries                                  9
                PrgC                                     0
 Take-Ons       Att                                      0
                Succ                                     0
 game_id                                          47698a8f
 Name: 2167, dtype: object,
 level_0                                                    2293
 index                                                      2293
 league                                           GER-Bundesliga
 season                                                     2425
 game                      2024-11-02 Bayern Munich-Union Berlin
 team                                              Bayern Munich
 player                                               Harry Kane
 jersey_number                                                 9